'use client';
import {useEffect,useMemo,useState}from'react';
import {useRouter}from'next/navigation';
import type{Playbook,PlaybookSystem}from'@/lib/playbook';
import {createPersonalSystemTag,createPlaybookSeries,deletePlaybookSeries,duplicateSystemIntoSeries,listPersonalSystemTags,listPlaybookSeries,listSeriesMembership,setPlaybookSystemSeries,updatePlaybookSeries,type PersonalSystemTag,type PlaybookSeries}from'@/lib/playbook-series';
export default function PlaybookSeriesManager({playbook,systems,onChanged}:{playbook:Playbook;systems:PlaybookSystem[];onChanged?:()=>void}){const r=useRouter();const[series,setSeries]=useState<PlaybookSeries[]>([]),[tags,setTags]=useState<PersonalSystemTag[]>([]),[membership,setMembership]=useState<Record<string,string>>({});const[filter,setFilter]=useState('');async function load(){const[a,b,c]=await Promise.all([listPlaybookSeries(playbook.id),listPersonalSystemTags(),listSeriesMembership(playbook.id)]);setSeries(a);setTags(b);setMembership(c)}useEffect(()=>{load()},[playbook.id]);
async function addSeries(){const name=prompt('Nom de la série ?');if(!name?.trim())return;const selected=prompt('Tags séparés par des virgules (facultatif) ?','')?.split(',').map(x=>x.trim()).filter(Boolean)||[];for(const t of selected)await createPersonalSystemTag(t);await createPlaybookSeries(playbook.id,name,selected);load()}
async function addTag(){const n=prompt('Nouveau tag de jeu ?\nEx: Pick top, Pick side, Pick non porteur, Post up, 1v1, Pick the picker, Spanish');if(n?.trim()){await createPersonalSystemTag(n);load()}}
const visible=useMemo(()=>systems.filter(s=>!filter||s.tags?.includes(filter)||series.find(x=>x.id===membership[s.id])?.tags.includes(filter)),[systems,filter,series,membership]);
return <section style={{background:'#fff',border:'1px solid #e5e5e5',borderRadius:12,padding:16,margin:'14px 0'}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><h3 style={{marginRight:'auto'}}>Séries & tags du Playbook</h3><select value={filter} onChange={e=>setFilter(e.target.value)}><option value=''>Tous les tags</option>{tags.map(t=><option key={t.id}>{t.name}</option>)}</select><button onClick={addTag}>+ Tag</button><button onClick={addSeries}>+ Série</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginTop:12}}>{series.map(sr=><div key={sr.id} style={{border:'1px solid #ddd',borderRadius:10,padding:10}}><div style={{display:'flex'}}><b style={{flex:1}}>{sr.name}</b><button title='Renommer' onClick={async()=>{const n=prompt('Renommer la série',sr.name);if(n){await updatePlaybookSeries(sr.id,{name:n});load()}}}>✎</button><button title='Modifier les tags de la série' onClick={async()=>{const raw=prompt('Tags de la série, séparés par des virgules',sr.tags.join(', '));if(raw===null)return;const next=raw.split(',').map(x=>x.trim()).filter(Boolean);for(const t of next)await createPersonalSystemTag(t);await updatePlaybookSeries(sr.id,{tags:next});await load();onChanged?.()}}>🏷</button><button onClick={async()=>{if(confirm('Supprimer la série ? Les systèmes restent dans la bibliothèque privée.')){await deletePlaybookSeries(sr.id);load()}}}>×</button></div><div style={{display:'flex',flexWrap:'wrap',gap:4,margin:'7px 0'}}>{sr.tags.map(t=><span key={t} style={{fontSize:11,background:'#f3e3b4',padding:'3px 6px',borderRadius:99}}>{t}</span>)}</div>{visible.filter(s=>membership[s.id]===sr.id).map(s=><div key={s.id} style={{display:'flex',gap:5,alignItems:'center',padding:'5px 0',borderTop:'1px solid #eee'}}><span style={{flex:1}}>{s.title}</span><button title='Dupliquer puis modifier dans DESSIN' onClick={async()=>{const x=await duplicateSystemIntoSeries(s,sr.id);r.push(`/plaquette?mode=edit&return=systeme`);}}>⧉</button></div>)}</div>)}</div><div style={{marginTop:12}}><b>Systèmes du Playbook</b>{visible.map(s=><div key={s.id} style={{display:'grid',gridTemplateColumns:'1fr 220px',gap:8,padding:'6px 0'}}><span>{s.title} <small>{(s.tags||[]).join(' · ')}</small></span><select value={membership[s.id]||''} onChange={async e=>{await setPlaybookSystemSeries(s.id,e.target.value||null);load();onChanged?.()}}><option value=''>Sans série</option>{series.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>)}</div></section>}
