import { NextRequest, NextResponse } from "next/server";

type TeamChoice={name:string;url:string};
type Game={sourceKey:string;round:string;date:string;time:string;homeAway:"home"|"away"|"unknown";opponent:string;ourScore:number|null;opponentScore:number|null};
const MONTHS:Record<string,string>={janv:"01",févr:"02",mars:"03",avr:"04",mai:"05",juin:"06",juil:"07",août:"08",sept:"09",oct:"10",nov:"11",déc:"12"};
function text(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim()}
function abs(href:string){return new URL(href,"https://competitions.ffbb.com").toString()}
function teamChoices(html:string):TeamChoice[]{const out=new Map<string,TeamChoice>();const re=/<a[^>]+href=["']([^"']*\/equipes\/\d+[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const name=text(m[2]);if(name&&name.length<120)out.set(abs(m[1]),{name,url:abs(m[1])})}return [...out.values()]}
function isoDate(raw:string){const m=raw.toLowerCase().match(/(\d{1,2})\s+([a-zéû\.]+)(?:\s+(\d{4}))?/i);if(!m)return raw;const key=Object.keys(MONTHS).find(k=>m[2].startsWith(k));if(!key)return raw;const y=m[3]||String(new Date().getFullYear());return `${y}-${MONTHS[key]}-${m[1].padStart(2,"0")}`}
function parseTeamPage(html:string,url:string){const t=text(html);const team=(t.match(/#\s*([^#]{2,80}?)\s+(?:NATIONALE|REGIONALE|RÉGIONALE|DEPARTEMENTALE|DÉPARTEMENTALE|PRÉ|PRE|U\d|Calendrier)/i)?.[1]||t.match(/club\s+[^ ]+\s+équipe\s+([^#]{2,70})/i)?.[1]||"Équipe FFBB").trim();const competition=(t.match(/((?:NATIONALE|REGIONALE|RÉGIONALE|DEPARTEMENTALE|DÉPARTEMENTALE|PRÉ|PRE)[^|]{2,100})\s+FEDE/i)?.[1]||t.match(/\|\s*([A-Z0-9 -]{2,35})\s*\|\s*Poule/i)?.[1]||"Compétition FFBB").trim();const pool=t.match(/Poule\s+([A-Z0-9-]+)/i)?.[1]||"";const phase=new URL(url).searchParams.get("phase")||"";const matches:Game[]=[];const re=/#(\d+)\s+(J\d+)?\s*(\d{1,2}\s+(?:janv\.?|févr\.?|mars|avr\.?|mai|juin|juil\.?|août|sept\.?|oct\.?|nov\.?|déc\.?)(?:\s+\d{4})?)\s+(\d{1,2}h\d{2})\s+(Domicile|Extérieur)\s+([^#]{2,100}?)(?=#\d+|Datas de l'équipe|Classement officiel|$)/gi;let m;while((m=re.exec(t))){const tail=m[6].trim();const sm=tail.match(/^(.*?)(\d{2,3})(\d{2,3})$/);let opponent=tail,ourScore:null|number=null,opponentScore:null|number=null;if(sm){opponent=sm[1].trim();const a=Number(sm[2]),b=Number(sm[3]);if(m[5].toLowerCase().startsWith("dom")){ourScore=a;opponentScore=b}else{ourScore=b;opponentScore=a}}matches.push({sourceKey:m[1],round:m[2]||"",date:isoDate(m[3]),time:m[4].replace("h",":"),homeAway:m[5].toLowerCase().startsWith("dom")?"home":"away",opponent,ourScore,opponentScore})}
 const rankText=t.includes("Classement officiel")?t.slice(t.indexOf("Classement officiel"),t.indexOf("Classement officiel")+2500):"";return {mode:"team",team,competition,pool,phase,sourceUrl:url,matches,classementText:rankText,updatedAt:new Date().toISOString()}}
export async function GET(req:NextRequest){const url=req.nextUrl.searchParams.get("url")||"";if(!/^https:\/\/competitions\.ffbb\.com\//i.test(url))return NextResponse.json({error:"Lien FFBB invalide"},{status:400});try{const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 MyBasket/1.0","accept-language":"fr-FR,fr;q=.9"},cache:"no-store"});if(!r.ok)throw new Error(`FFBB ${r.status}`);const html=await r.text();if(/\/equipes\/\d+/i.test(new URL(url).pathname))return NextResponse.json(parseTeamPage(html,url));const teams=teamChoices(html);return NextResponse.json({mode:"choose-team",sourceUrl:url,teams,updatedAt:new Date().toISOString()})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Lecture FFBB impossible"},{status:502})}}
