import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin-server";

const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]!));
async function allowed(supabase:any,userId:string,cohortId:string){const[{data:i},{data:p}]=await Promise.all([supabase.from("training_instructors").select("id").eq("cohort_id",cohortId).eq("user_id",userId).maybeSingle(),supabase.from("profiles").select("platform_role").eq("id",userId).maybeSingle()]);return !!i||["ceo","superadmin"].includes(String(p?.platform_role||""))}
async function sendMail(to:string,subject:string,html:string,attachment:string,filename:string){const key=process.env.RESEND_API_KEY;if(!key)return false;const from=process.env.MYBASKET_EMAIL_FROM||"MyBasket <notifications@mybasket.fr>";const content=Buffer.from(attachment,"utf8").toString("base64");const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[to],subject,html,attachments:[{filename,content}]})});return r.ok}
function documentHtml(candidate:any,structure:any,cohort:any,template:string,subject:string,extra:string){
 const primary=structure?.document_primary_color||"#6B1A2C",secondary=structure?.document_secondary_color||"#D4A24C",name=`${candidate.first_name||""} ${candidate.last_name||""}`.trim()||candidate.email||"Candidat";
 const title=subject||({convocation:"Convocation",attestation:"Attestation de formation",inscription:"Fiche d'inscription",relance:"Pièces administratives manquantes",custom:"Courrier"} as any)[template]||"Document";
 const logo=structure?.logo_url?`<img src="${esc(structure.logo_url)}" style="max-width:120px;max-height:55px;object-fit:contain;background:white;padding:4px;border-radius:6px">`:`<b>MYBASKET</b>`;
 const text=template==="convocation"?`Nous vous confirmons votre convocation dans le cadre de la formation <b>${esc(cohort?.name||"")}</b>.`:template==="attestation"?`Nous attestons que <b>${esc(name)}</b> est inscrit(e) à la formation <b>${esc(cohort?.name||"")}</b>.`:template==="relance"?`Votre dossier administratif nécessite encore votre attention. Merci de transmettre les pièces manquantes indiquées par l'institution.`:template==="inscription"?`Cette fiche récapitule les informations enregistrées pour votre inscription.`:extra||"";
 return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:0}*{box-sizing:border-box}body{font-family:Arial;margin:0;padding:34mm 15mm 18mm;color:#292123;font-size:11px;position:relative}body:before{content:"";position:absolute;left:0;right:0;top:0;height:26mm;background:${primary}}.head{position:absolute;top:7mm;left:15mm;right:15mm;color:#fff;display:flex;justify-content:space-between;align-items:center}.rule{position:absolute;top:26mm;left:0;right:0;height:2mm;background:${secondary}}h1{color:${primary};font-size:23px;margin:0 0 8mm}.card{border-left:4px solid ${secondary};background:#faf7f7;padding:12px 14px;margin:7mm 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:5mm}.field{border-bottom:1px solid #d9cdd0;padding:5px 0}.field small{display:block;color:#847478;text-transform:uppercase;font-size:7px;font-weight:bold;margin-bottom:3px}.body{line-height:1.6;margin-top:8mm}.footer{position:absolute;bottom:8mm;left:15mm;right:15mm;border-top:1px solid #e5dade;padding-top:3mm;color:#85767a;font-size:8px}</style></head><body><div class="head"><div>${logo}</div><b>${esc(structure?.name||"Institution")}</b></div><div class="rule"></div><h1>${esc(title)}</h1><div class="card"><div class="grid"><div class="field"><small>Candidat</small>${esc(name)}</div><div class="field"><small>Email</small>${esc(candidate.email)}</div><div class="field"><small>Club / structure</small>${esc(candidate.club_name)}</div><div class="field"><small>N° licence</small>${esc(candidate.license_number)}</div><div class="field"><small>Formation</small>${esc(cohort?.name)}</div><div class="field"><small>Date</small>${new Date().toLocaleDateString("fr-FR")}</div></div></div><div class="body">${text}${extra&&template!=="custom"?`<p>${esc(extra).replace(/\n/g,"<br>")}</p>`:""}</div><div class="footer">${esc(structure?.name||"")} · Document généré par MyBasket</div></body></html>`;
}
export async function POST(request:Request){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Non connecté"},{status:401});
 const body=await request.json(),candidateId=String(body.candidateId||"");const admin=createAdminClient();if(!admin)return NextResponse.json({error:"Service Supabase indisponible"},{status:500});
 const{data:c}=await admin.from("training_candidates").select("*,training_cohorts(id,name,institution_id)").eq("id",candidateId).maybeSingle();if(!c)return NextResponse.json({error:"Candidat introuvable"},{status:404});
 if(!(await allowed(supabase,user.id,c.cohort_id)))return NextResponse.json({error:"Accès refusé"},{status:403});
 if(body.action==="status"){const requestId=String(body.requestId||""),status=String(body.status||"missing");const{data:existing}=await admin.from("training_document_submissions").select("id,current_version").eq("candidate_id",candidateId).eq("request_id",requestId).maybeSingle();if(status==="missing"){if(existing)await admin.from("training_document_submissions").delete().eq("id",existing.id);return NextResponse.json({ok:true})}const payload={candidate_id:candidateId,request_id:requestId,status,current_version:existing?.current_version||1,submitted_at:new Date().toISOString()};const q=existing?await admin.from("training_document_submissions").update(payload).eq("id",existing.id):await admin.from("training_document_submissions").insert(payload);if(q.error)return NextResponse.json({error:q.error.message},{status:400});return NextResponse.json({ok:true})}
 const cohort=(c as any).training_cohorts;let structure:any=null;if(cohort?.institution_id){const q=await admin.from("institutional_structures").select("name,logo_url,document_primary_color,document_secondary_color").eq("id",cohort.institution_id).maybeSingle();structure=q.data}
 const template=String(body.template||"convocation"),subject=String(body.subject||""),extra=String(body.body||"");const html=documentHtml(c,structure,cohort,template,subject,extra),filename=`${template}-${String(c.last_name||"candidat").replace(/[^a-z0-9_-]/gi,"-")}.html`;
 let sent=false;if(body.sendEmail===true&&c.email)sent=await sendMail(c.email,subject||"Formation MyBasket",`<p>Bonjour ${esc(c.first_name||"")},</p><p>Vous trouverez en pièce jointe votre document relatif à votre formation.</p>`,html,filename);
 await admin.from("training_candidate_document_history").insert({candidate_id:candidateId,document_type:template,title:subject||template,recipient_email:c.email||null,sent_by_email:sent,created_by:user.id});
 return new NextResponse(html,{headers:{"Content-Type":"text/html; charset=utf-8","Content-Disposition":`attachment; filename="${filename}"`,"X-MyBasket-Mail-Sent":sent?"1":"0"}});
}
