import React from "react";
import {Document,Page,Text,View,Image,StyleSheet} from "@react-pdf/renderer";
import type {PlayerNotebookSnapshot} from "@/lib/institutionnel/player-notebook-data";

export type PoleExitSection="identity"|"pathway"|"measurements"|"attendance"|"parent"|"basket"|"performance";
const ALL:PoleExitSection[]=["identity","pathway","measurements","attendance","parent","basket","performance"];
const B="#6B1A2C",G="#D4A24C",INK="#211A1C",M="#746B6D",L="#E6DDD8",BG="#F8F4F1";
const s=StyleSheet.create({page:{padding:34,fontFamily:"Helvetica",fontSize:9,color:INK},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderBottomWidth:1,borderBottomColor:L,paddingBottom:12,marginBottom:18},logo:{width:80,height:55,objectFit:"contain"},eyebrow:{fontSize:7,color:G,fontFamily:"Helvetica-Bold",letterSpacing:1.2},h1:{fontSize:22,color:B,fontFamily:"Helvetica-Bold",marginTop:3},h2:{fontSize:12,color:B,fontFamily:"Helvetica-Bold",marginTop:14,marginBottom:7},muted:{fontSize:8,color:M,lineHeight:1.4},row:{flexDirection:"row",gap:7},card:{borderWidth:1,borderColor:L,borderRadius:6,padding:9,marginBottom:7},metric:{flex:1,borderWidth:1,borderColor:L,borderRadius:6,padding:8},metricLabel:{fontSize:6.5,color:M},metricValue:{fontSize:13,color:B,fontFamily:"Helvetica-Bold",marginTop:3},table:{borderWidth:1,borderColor:L},tr:{flexDirection:"row",borderBottomWidth:1,borderBottomColor:L},th:{backgroundColor:BG,color:B,fontFamily:"Helvetica-Bold"},cell:{flex:1,padding:6},comment:{borderLeftWidth:4,borderLeftColor:B,backgroundColor:BG,padding:9,marginBottom:8},footer:{position:"absolute",bottom:18,left:34,right:34,borderTopWidth:1,borderTopColor:L,paddingTop:5,flexDirection:"row",justifyContent:"space-between",fontSize:6.5,color:M}});
const fmt=(d?:string|null)=>{if(!d)return "—";const p=d.slice(0,10).split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:d};
function Footer({at}:{at:string}){return <View style={s.footer} fixed><Text>MYBASKET · DOSSIER DE SORTIE PÔLE</Text><Text>Généré le {fmt(at)}</Text></View>}
function Header({st,p}:{st:any,p:any}){return <View style={s.header}><View>{st.logo_url?<Image src={st.logo_url} style={s.logo}/>:<Text style={{color:B,fontFamily:"Helvetica-Bold"}}>{st.short_name||st.name}</Text>}</View><View style={{alignItems:"flex-end"}}><Text style={s.eyebrow}>DOSSIER DE SORTIE PÔLE</Text><Text style={s.h1}>{p.first_name} {p.last_name}</Text><Text style={s.muted}>{st.name}</Text></View></View>}
export function PoleExitPdf({snapshot,sections=ALL}:{snapshot:PlayerNotebookSnapshot;sections?:PoleExitSection[]}){
 const on=(k:PoleExitSection)=>sections.includes(k),p:any=snapshot.player,st:any=snapshot.structure,seasons:any[]=snapshot.seasons as any[],entries:any[]=snapshot.entries as any[],ms:any[]=snapshot.measurements as any[],sessions:any[]=snapshot.attendanceSessions as any[],records:any[]=snapshot.attendanceRecords as any[],comments:any[]=snapshot.comments as any[],parent:any=snapshot.parentContext||{},tracking:any=(snapshot as any).poleTracking||null;
 const active=entries.find(e=>e.season_id===snapshot.activeSeasonId)||entries.at(-1)||{};const last=ms.at(-1)||{};
 const presence=seasons.map(se=>{const ss=sessions.filter(x=>x.season_id===se.id),ids=new Set(ss.map(x=>x.id)),rr=records.filter(x=>x.season_id===se.id&&ids.has(x.session_id)),present=rr.filter(x=>x.status==="present").length;return {label:se.season_label,present,absent:rr.filter(x=>x.status==="absent").length,excused:rr.filter(x=>x.status==="excused").length,rate:rr.length?Math.round(present/rr.length*100):null}}).filter(x=>x.present+x.absent+x.excused>0);
 return <Document title={`Dossier de sortie - ${p.first_name} ${p.last_name}`}>
  <Page size="A4" style={s.page}><Header st={st} p={p}/>
   {on("identity")&&<><Text style={s.h2}>Identité & situation actuelle</Text><View style={s.row}><View style={s.metric}><Text style={s.metricLabel}>DATE DE NAISSANCE</Text><Text style={s.metricValue}>{fmt(p.birthdate)}</Text></View><View style={s.metric}><Text style={s.metricLabel}>CATÉGORIE</Text><Text style={s.metricValue}>{active.category||p.category||"—"}</Text></View><View style={s.metric}><Text style={s.metricLabel}>POSTE</Text><Text style={s.metricValue}>{active.position_label||"—"}</Text></View></View><View style={[s.card,{marginTop:8}]}><Text>Club actuel : {active.club_name||p.club_name||"—"}</Text><Text>Email : {p.email||"—"}</Text><Text>Téléphone : {p.phone||"—"}</Text></View></>}
   {on("pathway")&&<><Text style={s.h2}>Parcours</Text><View style={s.table}><View style={[s.tr,s.th]}><Text style={s.cell}>Saison</Text><Text style={s.cell}>Club / structure</Text><Text style={s.cell}>Catégorie</Text></View>{entries.map((e:any)=><View style={s.tr} key={e.id}><Text style={s.cell}>{seasons.find(x=>x.id===e.season_id)?.season_label||"—"}</Text><Text style={s.cell}>{e.club_name||"—"}</Text><Text style={s.cell}>{e.category||"—"}</Text></View>)}</View></>}
   {on("measurements")&&<><Text style={s.h2}>Dernières mesures</Text><View style={s.row}><View style={s.metric}><Text style={s.metricLabel}>TAILLE</Text><Text style={s.metricValue}>{last.height_cm?`${last.height_cm} cm`:"—"}</Text></View><View style={s.metric}><Text style={s.metricLabel}>POIDS</Text><Text style={s.metricValue}>{last.weight_kg?`${last.weight_kg} kg`:"—"}</Text></View><View style={s.metric}><Text style={s.metricLabel}>ENVERGURE</Text><Text style={s.metricValue}>{last.wingspan_cm?`${last.wingspan_cm} cm`:"—"}</Text></View></View></>}
   <Footer at={snapshot.generatedAt}/></Page>
  {(on("attendance")||on("parent"))&&<Page size="A4" style={s.page}><Header st={st} p={p}/>
   {on("attendance")&&<><Text style={s.h2}>Assiduité / convocations</Text><View style={s.table}><View style={[s.tr,s.th]}><Text style={s.cell}>Saison</Text><Text style={s.cell}>Présent</Text><Text style={s.cell}>Excusé</Text><Text style={s.cell}>Absent</Text><Text style={s.cell}>Taux</Text></View>{presence.map(x=><View style={s.tr} key={x.label}><Text style={s.cell}>{x.label}</Text><Text style={s.cell}>{x.present}</Text><Text style={s.cell}>{x.excused}</Text><Text style={s.cell}>{x.absent}</Text><Text style={s.cell}>{x.rate==null?"—":`${x.rate}%`}</Text></View>)}</View></>}
   {on("parent")&&<><Text style={s.h2}>Contexte familial / scolaire</Text><View style={s.card}><Text>Responsable 1 : {parent.guardian1_name||"—"} {parent.guardian1_relation?`· ${parent.guardian1_relation}`:""}</Text><Text>{parent.guardian1_email||""} {parent.guardian1_phone||""}</Text></View><View style={s.card}><Text>Responsable 2 : {parent.guardian2_name||"—"} {parent.guardian2_relation?`· ${parent.guardian2_relation}`:""}</Text><Text>{parent.guardian2_email||""} {parent.guardian2_phone||""}</Text></View>{parent.school_context&&<View style={s.card}><Text style={{fontFamily:"Helvetica-Bold",color:B}}>Contexte scolaire</Text><Text style={s.muted}>{parent.school_context}</Text></View>}</>}
   <Footer at={snapshot.generatedAt}/></Page>}
  {(on("basket")||on("performance"))&&<Page size="A4" style={s.page}><Header st={st} p={p}/>
   {on("performance")&&tracking&&<><Text style={s.h2}>Synthèse sportive</Text><View style={s.row}><View style={s.metric}><Text style={s.metricLabel}>MATCHS</Text><Text style={s.metricValue}>{tracking.games||0}</Text></View><View style={s.metric}><Text style={s.metricLabel}>PTS / MATCH</Text><Text style={s.metricValue}>{tracking.games?(tracking.pts/tracking.games).toFixed(1):"—"}</Text></View><View style={s.metric}><Text style={s.metricLabel}>REB / MATCH</Text><Text style={s.metricValue}>{tracking.games?(tracking.reb/tracking.games).toFixed(1):"—"}</Text></View><View style={s.metric}><Text style={s.metricLabel}>PD / MATCH</Text><Text style={s.metricValue}>{tracking.games?(tracking.ast/tracking.games).toFixed(1):"—"}</Text></View></View><View style={[s.card,{marginTop:8}]}><Text>Présence : {tracking.presenceRate==null?"—":`${tracking.presenceRate}%`} · Charge 7 jours : {tracking.load7||0} · Clips liés : {tracking.clips||0}</Text></View></>}
   {on("basket")&&<><Text style={s.h2}>Évaluations & observations basket</Text>{comments.length?comments.map((c:any)=><View style={s.comment} key={c.id}><Text style={{fontFamily:"Helvetica-Bold",color:B}}>{fmt(c.comment_date)} · {c.author_name||"Staff"}</Text>{c.profile_text&&<Text>Profil : {c.profile_text}</Text>}{c.strengths_text&&<Text>Points forts : {c.strengths_text}</Text>}{c.improvement_text&&<Text>Axes : {c.improvement_text}</Text>}{c.projection_text&&<Text>Projection : {c.projection_text}</Text>}{c.free_comment&&<Text>Commentaire : {c.free_comment}</Text>}</View>):<View style={s.card}><Text style={s.muted}>Aucune observation partageable.</Text></View>}</>}
   <Footer at={snapshot.generatedAt}/></Page>}
 </Document>
}
