"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type P={id:string;firstName?:string;lastName?:string;num?:string|number;poste?:string;posteSecondaire?:string;photo?:string;taille?:string;mainDominante?:string};
type T={id:string;name?:string;logo?:string;players?:P[]};
export type ScoutCard={playerId:string;profile:string;profile2?:string;notes:string};
export type ScoutStat={id:string;metric:string;limit:number};
export type ScoutBoardValue={scoutTeamId?:string;identity?:string;offense?:string;defense?:string;depthChart?:Record<string,string[]>;importantStats?:ScoutStat[];playerCards?:ScoutCard[]};
type Agg={id:string;games:number;pts:number;reb:number;off_reb:number;def_reb:number;ast:number;stl:number;blk:number;turnovers:number;p2m:number;p2a:number;p3m:number;p3a:number;ftm:number;fta:number;min:number};
type Zone={zone:string,made:number,att:number};
const METRICS=[['pts','Meilleurs marqueurs'],['off_reb','Meilleurs rebondeurs offensifs'],['reb','Meilleurs rebondeurs'],['ast','Meilleurs passeurs'],['p3pct','Meilleurs shooteurs à 3 pts'],['p2pct','Meilleur % à 2 pts'],['ftpct','Meilleur % aux lancers'],['stl','Meilleurs intercepteurs'],['turnovers','Pertes de balle']];
const PROFILES=['🎯 Shooteur','⚡ Driver','🧠 Créateur','🔄 P&R Handler','💪 Physique','🧲 Rebondeur','🏀 Post-up','🛡️ Défenseur','🚀 Slasher','🔥 Scoreur'];
const n=(v:any)=>Number(v)||0, avg=(v:number,g:number)=>(g?v/g:0), pct=(m:number,a:number)=>(a?100*m/a:0);
const label=(p?:P)=>p?[p.firstName,p.lastName].filter(Boolean).join(' ')||`Joueur ${p.num??''}`:'Joueur';
export default function ScoutingBoard({value,onChange,scoutTeams,myTeam,date,systems,onAddSystem}:{value:ScoutBoardValue;onChange:(v:Partial<ScoutBoardValue>)=>void;scoutTeams:T[];myTeam?:T;date?:string;systems:any[];onAddSystem:()=>void}){
 const sb=createClient(); const [agg,setAgg]=useState<Record<string,Agg>>({}); const [zones,setZones]=useState<Record<string,Zone[]>>({}); const team=scoutTeams.find(t=>t.id===value.scoutTeamId); const players=team?.players||[];
 const [loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;(async()=>{if(!team){setAgg({});setZones({});return} setLoading(true); const {data:matches}=await sb.from('match_stats').select('id').eq('team_id',team.id); const ids=(matches||[]).map((x:any)=>x.id); if(!ids.length){if(live){setAgg({});setZones({});setLoading(false)}return}
 const [{data:ps},{data:actions}]=await Promise.all([sb.from('match_player_stats').select('*').in('match_id',ids),sb.from('match_actions').select('player_id,shot_zone_id,shot_result').in('match_id',ids)]); const map:Record<string,Agg>={}; for(const r of ps||[]){const id=String((r as any).player_id||'');if(!id)continue;const a=map[id]||{id,games:0,pts:0,reb:0,off_reb:0,def_reb:0,ast:0,stl:0,blk:0,turnovers:0,p2m:0,p2a:0,p3m:0,p3a:0,ftm:0,fta:0,min:0};a.games++; for(const k of ['pts','reb','off_reb','def_reb','ast','stl','blk','turnovers','p2m','p2a','p3m','p3a','ftm','fta','min'] as const)(a as any)[k]+=n((r as any)[k]??(r as any)[k==='turnovers'?'to':k]);map[id]=a}
 const zm:Record<string,Record<string,Zone>>={};for(const r of actions||[]){const id=String((r as any).player_id||''),z=String((r as any).shot_zone_id||'');if(!id||!z)continue;zm[id] ||= {};const q=zm[id][z]||{zone:z,made:0,att:0};q.att++;if(String((r as any).shot_result||'').toLowerCase().includes('marq'))q.made++;zm[id][z]=q} if(live){setAgg(map);setZones(Object.fromEntries(Object.entries(zm).map(([k,v])=>[k,Object.values(v)])));setLoading(false)}})();return()=>{live=false}},[team?.id]);
 const depth=value.depthChart||{}; const cards=value.playerCards||[]; const stats=value.importantStats||[];
 const setDepth=(pos:string,id:string)=>{const next={...depth};Object.keys(next).forEach(k=>next[k]=(next[k]||[]).filter(x=>x!==id));next[pos]=[...(next[pos]||[]),id].slice(0,3);onChange({depthChart:next})};
 const metricValue=(a:Agg,m:string)=>m==='p3pct'?pct(a.p3m,a.p3a):m==='p2pct'?pct(a.p2m,a.p2a):m==='ftpct'?pct(a.ftm,a.fta):avg((a as any)[m]||0,a.games);
 const fmt=(v:number,m:string)=>m.includes('pct')?`${v.toFixed(1)}%`:v.toFixed(1).replace('.0','');
 const addCard=(id:string)=>{if(cards.some(c=>c.playerId===id))return;onChange({playerCards:[...cards,{playerId:id,profile:'🎯 Shooteur',profile2:'',notes:''}]})};
 return <div className="sb">
  <header className="sb-head"><div className="sb-club">{team?.logo?<img src={team.logo}/>:<span>🏀</span>}<b>{team?.name||'ÉQUIPE SCOUTÉE'}</b></div><div className="sb-title"><strong>SCOUTING ADVERSE</strong><small>{date||'Date du match'}</small></div><div className="sb-club right"><b>{myTeam?.name||'MON ÉQUIPE'}</b>{myTeam?.logo?<img src={myTeam.logo}/>:<span>🏀</span>}</div></header>
  <div className="sb-team-select"><label>Équipe scoutée</label><select value={value.scoutTeamId||''} onChange={e=>onChange({scoutTeamId:e.target.value,depthChart:{},playerCards:[]})}><option value="">Choisir l'adversaire…</option>{scoutTeams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><small>Uniquement les équipes créées comme équipes scoutées.</small></div>
  {team&&<>
  <section className="sb-section"><h3>DEPTH CHART</h3><div className="sb-depth">{['1','2','3','4','5'].map(pos=><div key={pos}><b>POSTE {pos}</b>{(depth[pos]||[]).map(id=><span key={id}>#{players.find(p=>p.id===id)?.num??'—'} {label(players.find(p=>p.id===id))}</span>)}<select value="" onChange={e=>{if(e.target.value)setDepth(pos,e.target.value)}}><option value="">+ joueur</option>{players.filter(p=>!Object.values(depth).flat().includes(p.id)).map(p=><option key={p.id} value={p.id}>#{p.num??'—'} {label(p)}</option>)}</select></div>)}</div></section>
  <section className="sb-section"><h3>TEAM INFORMATION</h3><div className="sb-three"><label><b>IDENTITÉ</b><textarea value={value.identity||''} onChange={e=>onChange({identity:e.target.value})} placeholder="Style, rythme, philosophie, joueurs moteurs…"/></label><label><b>ATTAQUE</b><textarea value={value.offense||''} onChange={e=>onChange({offense:e.target.value})} placeholder="Transition, P&R, post-up, spacing, habitudes…"/></label><label><b>DÉFENSE</b><textarea value={value.defense||''} onChange={e=>onChange({defense:e.target.value})} placeholder="Couvertures, transition, press, switch, zone…"/></label></div></section>
  <section className="sb-section"><div className="sb-section-head"><h3>STATS IMPORTANTES</h3><button onClick={()=>onChange({importantStats:[...stats,{id:crypto.randomUUID(),metric:'off_reb',limit:3}]})}>+ Ajouter un tableau</button></div><div className="sb-statgrid">{stats.map(s=>{const rows=players.map(p=>({p,a:agg[p.id]})).filter(x=>x.a).sort((x,y)=>metricValue(y.a,s.metric)-metricValue(x.a,s.metric)).slice(0,s.limit);return <article key={s.id}><div><select value={s.metric} onChange={e=>onChange({importantStats:stats.map(x=>x.id===s.id?{...x,metric:e.target.value}:x)})}>{METRICS.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select aria-label="Nombre de joueurs" value={s.limit} onChange={e=>onChange({importantStats:stats.map(x=>x.id===s.id?{...x,limit:Number(e.target.value)}:x)})}><option value={3}>Top 3</option><option value={5}>Top 5</option><option value={10}>Top 10</option></select><button onClick={()=>onChange({importantStats:stats.filter(x=>x.id!==s.id)})}>×</button></div><table><tbody>{rows.map(({p,a},i)=><tr key={p.id}><td>{i+1}</td><td>#{p.num??'—'} {label(p)}</td><td><b>{fmt(metricValue(a,s.metric),s.metric)}</b></td></tr>)}</tbody></table></article>})}{!stats.length&&<button className="sb-addstat" onClick={()=>onChange({importantStats:[{id:crypto.randomUUID(),metric:'off_reb',limit:3},{id:crypto.randomUUID(),metric:'p3pct',limit:3},{id:crypto.randomUUID(),metric:'ast',limit:3}]})}>Créer les 3 tableaux de départ</button>}</div></section>
  <section className="sb-section"><div className="sb-section-head"><h3>SYSTÈMES ADVERSES</h3><button onClick={onAddSystem}>+ Importer / dessiner</button></div><div className="sb-plays">{systems.map((s:any)=><article key={s.id}><b>{s.title}</b><div>{(s.schemaImages?.length?s.schemaImages:[s.schemaImage]).filter(Boolean).slice(0,3).map((im:string,i:number)=><img key={i} src={im}/>)}</div></article>)}{!systems.length&&<p>Aucun système adverse ajouté.</p>}</div></section>
  <section className="sb-section"><div className="sb-section-head"><h3>JOUEURS À METTRE EN AVANT</h3><select value="" onChange={e=>{if(e.target.value)addCard(e.target.value)}}><option value="">+ Ajouter un joueur</option>{players.filter(p=>!cards.some(c=>c.playerId===p.id)).map(p=><option key={p.id} value={p.id}>#{p.num??'—'} {label(p)}</option>)}</select></div>{cards.map(c=>{const p=players.find(x=>x.id===c.playerId),a=p?agg[p.id]:undefined,z=p?zones[p.id]||[]:[];if(!p)return null;return <article className="sb-player" key={p.id}><div className="sb-player-photo">{p.photo?<img src={p.photo}/>:<span>{p.firstName?.[0]}{p.lastName?.[0]}</span>}</div><div className="sb-player-main"><div className="sb-player-id"><b>#{p.num??'—'} · {label(p)}</b><span>POSTE {p.poste||'—'} · {p.taille||'—'} · {p.mainDominante||'Main à renseigner'}</span></div><div className="sb-player-stats">{[['PTS',a?avg(a.pts,a.games):0],['2P%',a?pct(a.p2m,a.p2a):0],['3P%',a?pct(a.p3m,a.p3a):0],['LF%',a?pct(a.ftm,a.fta):0],['RO',a?avg(a.off_reb,a.games):0],['REB',a?avg(a.reb,a.games):0],['PD',a?avg(a.ast,a.games):0],['BP',a?avg(a.turnovers,a.games):0],['INT',a?avg(a.stl,a.games):0]].map(([k,v])=><div key={String(k)}><small>{k}</small><b>{String(k).includes('%')?`${Number(v).toFixed(1)}%`:Number(v).toFixed(1)}</b></div>)}</div><div className="sb-player-edit"><div className="sb-profiles"><select value={c.profile} onChange={e=>onChange({playerCards:cards.map(x=>x.playerId===c.playerId?{...x,profile:e.target.value}:x)})}>{PROFILES.map(x=><option key={x}>{x}</option>)}</select><select value={c.profile2||''} onChange={e=>onChange({playerCards:cards.map(x=>x.playerId===c.playerId?{...x,profile2:e.target.value}:x)})}><option value="">2e profil (optionnel)</option>{PROFILES.filter(x=>x!==c.profile).map(x=><option key={x}>{x}</option>)}</select></div><textarea value={c.notes} onChange={e=>onChange({playerCards:cards.map(x=>x.playerId===c.playerId?{...x,notes:e.target.value}:x)})} placeholder="Caractéristiques · tendances · ce qu'il aime faire · comment le défendre…"/><button onClick={()=>onChange({playerCards:cards.filter(x=>x.playerId!==c.playerId)})}>Retirer</button></div></div><div className="sb-shot"><b>SHOT CHART</b>{z.length?<div>{z.slice(0,8).map(q=><span key={q.zone}><small>{q.zone}</small><strong>{Math.round(pct(q.made,q.att))}%</strong><i>{q.made}/{q.att}</i></span>)}</div>:<p>{loading?'Calcul…':'Aucun tir codé'}</p>}</div></article>})}</section>
  </>}</div>
}
