"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Grid={id:string;name:string;court_schema_url:string|null};type Row={id:string;grid_id:string;name:string;sort_order:number};type Session={id:string;grid_id:string;session_date:string};type Result={id:string;session_id:string;row_id:string;player_id:string;made:number;attempted:number};
const B="#6B1A2C",G="#D4A24C",BD="#E8DDD7",M="#7B6E68";const pct=(m:number,a:number)=>a?Math.round(m/a*1000)/10:0;const fmt=(v:string)=>new Date(`${v}T12:00:00`).toLocaleDateString("fr-FR");
function spot(name:string,i:number){const n=name.toLowerCase();if(n.includes("corner droit"))return[84,76];if(n.includes("aile droite"))return[75,49];if(n.includes("axe"))return[50,30];if(n.includes("aile gauche"))return[25,49];if(n.includes("corner gauche"))return[16,76];if(n.includes("lf")||n.includes("lancer"))return[50,57];return[20+(i%4)*20,42+Math.floor(i/4)*13]}
function ShotChart({rows,results}:{rows:Row[];results:Result[]}){return <svg viewBox="0 0 100 92" style={{width:"100%",maxWidth:260,display:"block",margin:"auto",background:"#fbf7f3",borderRadius:12,border:`1px solid ${BD}`}}><path d="M4 88V4h92v84M35 4v24h30V4M38 28a18 18 0 0 0 24 0M8 88a42 42 0 0 1 84 0" fill="none" stroke="#cbbdb5" strokeWidth="1"/><circle cx="50" cy="8" r="1.8" fill="none" stroke="#9d8f88"/>{rows.map((r,i)=>{const rr=results.filter(x=>x.row_id===r.id),m=rr.reduce((a,x)=>a+x.made,0),a=rr.reduce((z,x)=>z+x.attempted,0),p=pct(m,a),[x,y]=spot(r.name,i);return <g key={r.id}><circle cx={x} cy={y} r="7" fill={a?(p>=60?"#e7f4eb":p>=40?"#fff1cf":"#fbe7e7"):"#eee8e4"} stroke={B} strokeWidth=".8"/><text x={x} y={y+1.5} textAnchor="middle" fontSize="4.3" fontWeight="900" fill={B}>{a?`${p}%`:"—"}</text></g>})}</svg>}
function Block({grid,rows,sessions,results}:{grid:Grid;rows:Row[];sessions:Session[];results:Result[]}){const rs=results.filter(r=>sessions.some(s=>s.id===r.session_id));const made=rs.reduce((a,r)=>a+r.made,0),attempted=rs.reduce((a,r)=>a+r.attempted,0);return <article style={card}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start"}}><div><span style={eye}>1 GRILLE = 1 BLOC</span><h3 style={{margin:"4px 0",color:B}}>{grid.name}</h3><span style={{fontSize:11,color:M}}>{sessions.length} session(s) · {made}/{attempted} · <b>{pct(made,attempted)}%</b></span></div></div><div style={{display:"grid",gridTemplateColumns:"minmax(220px,.8fr) 1.2fr",gap:14,marginTop:12,alignItems:"start"}}><ShotChart rows={rows} results={rs}/><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr><th style={th}>Date</th><th style={th}>Marqués</th><th style={th}>Tentés</th><th style={th}>%</th></tr></thead><tbody>{sessions.map(s=>{const x=rs.filter(r=>r.session_id===s.id),m=x.reduce((a,r)=>a+r.made,0),a=x.reduce((z,r)=>z+r.attempted,0);return <tr key={s.id}><td style={td}>{fmt(s.session_date)}</td><td style={td}>{m}</td><td style={td}>{a}</td><td style={{...td,fontWeight:900,color:B}}>{pct(m,a)}%</td></tr>})}</tbody></table></div></div></article>}
export default function PlayerShootingGrids({playerId,teamId}:{playerId:string;teamId:string}){const sb=useMemo(()=>createClient(),[]),[grids,setGrids]=useState<Grid[]>([]),[rows,setRows]=useState<Row[]>([]),[sessions,setSessions]=useState<Session[]>([]),[results,setResults]=useState<Result[]>([]),[selected,setSelected]=useState<string[]>([]),[open,setOpen]=useState(false);
 useEffect(()=>{(async()=>{const rr=await sb.from("shooting_grid_player_results").select("id,session_id,row_id,player_id,made,attempted").eq("player_id",playerId);const res=(rr.data||[]) as Result[];setResults(res);if(!res.length)return;const ids=[...new Set(res.map(x=>x.session_id))];const ss=await sb.from("shooting_grid_sessions").select("id,grid_id,session_date").in("id",ids).order("session_date",{ascending:false});const ses=(ss.data||[]) as Session[];setSessions(ses);const gids=[...new Set(ses.map(x=>x.grid_id))];const [gg,ro]=await Promise.all([sb.from("shooting_grids").select("id,name,court_schema_url").in("id",gids),sb.from("shooting_grid_rows").select("id,grid_id,name,sort_order").in("grid_id",gids).order("sort_order")]);const gs=(gg.data||[]) as Grid[];setGrids(gs);setRows((ro.data||[]) as Row[]);setSelected(gs.map(g=>g.id));})()},[playerId,teamId,sb]);
 const visible=grids.filter(g=>selected.includes(g.id));const allRows=rows.filter(r=>selected.includes(r.grid_id)),allSessions=sessions.filter(s=>selected.includes(s.grid_id)),allResults=results.filter(r=>allSessions.some(s=>s.id===r.session_id));
 if(!grids.length)return <div style={{...card,textAlign:"center",color:M}}>Aucun résultat de grille de tir pour ce joueur.</div>;
 return <section style={{display:"grid",gap:12}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start",flexWrap:"wrap"}}><div><span style={eye}>GRILLES DE TIR</span><h2 style={{margin:"4px 0",color:B}}>Résultats & shot charts</h2><p style={{margin:0,color:M,fontSize:11}}>Chaque grille possède son propre bloc et sa shot chart. Choisis celles à inclure dans l'analyse.</p></div><div style={{position:"relative"}}><button onClick={()=>setOpen(v=>!v)} style={button}>☑ Grilles affichées ({selected.length}/{grids.length}) ▾</button>{open&&<div style={{position:"absolute",right:0,top:44,zIndex:20,width:280,background:"#fff",border:`1px solid ${BD}`,borderRadius:12,padding:10,boxShadow:"0 12px 30px rgba(0,0,0,.12)"}}><label style={{display:"flex",gap:8,padding:7,fontWeight:900}}><input type="checkbox" checked={selected.length===grids.length} onChange={e=>setSelected(e.target.checked?grids.map(g=>g.id):[])}/> Tout sélectionner</label>{grids.map(g=><label key={g.id} style={{display:"flex",gap:8,padding:7}}><input type="checkbox" checked={selected.includes(g.id)} onChange={e=>setSelected(cur=>e.target.checked?[...cur,g.id]:cur.filter(x=>x!==g.id))}/>{g.name}</label>)}</div>}</div></div>{visible.map(g=><Block key={g.id} grid={g} rows={rows.filter(r=>r.grid_id===g.id)} sessions={sessions.filter(s=>s.grid_id===g.id)} results={results}/>)}<article style={card}><span style={eye}>SHOT CHART GÉNÉRALE</span><h3 style={{margin:"4px 0 12px",color:B}}>Cumul des grilles sélectionnées</h3>{selected.length?<div style={{display:"grid",gridTemplateColumns:"280px 1fr",gap:16,alignItems:"center"}}><ShotChart rows={allRows} results={allResults}/><div><b style={{fontSize:28,color:B}}>{pct(allResults.reduce((a,r)=>a+r.made,0),allResults.reduce((a,r)=>a+r.attempted,0))}%</b><p style={{color:M,fontSize:11}}>Cumul calculé uniquement sur les grilles cochées dans le menu déroulant.</p></div></div>:<p style={{color:M}}>Sélectionne au moins une grille.</p>}</article></section>}
const eye:React.CSSProperties={display:"block",fontSize:9,fontWeight:1000,letterSpacing:".12em",color:G};const card:React.CSSProperties={border:`1px solid ${BD}`,borderRadius:16,padding:14,background:"#fff",minWidth:0};const th:React.CSSProperties={padding:8,background:"#F7F2EE",borderBottom:`1px solid ${BD}`,color:"#594B46",textAlign:"center"};const td:React.CSSProperties={padding:8,borderBottom:`1px solid ${BD}`,textAlign:"center"};const button:React.CSSProperties={border:`1px solid ${BD}`,borderRadius:10,padding:"10px 12px",background:"#fff",color:B,fontWeight:900,cursor:"pointer"};
