'use client';
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,ChevronDown,ChevronRight,Copy,FolderOpen,MoreHorizontal,Plus,Search,Tags,X} from 'lucide-react';
import {createPlaybook,type Playbook} from '@/lib/playbook';
import {createPlaybookSeries,createPersonalSystemTag,ensureDefaultPersonalSystemTags,listPersonalSystemTags,type PersonalSystemTag,type PlaybookSeries} from '@/lib/playbook-series';
import {attachPrivateSystemToPlaybook,createDrawingSeason,detachPrivateSystemFromPlaybook,duplicatePrivateSystem,ensureDrawingSeasons,listDrawingTeams,loadDrawingSystems,movePlaybookSystemToSeries,openPrivateSystemInDrawing,renamePrivateSystem,renameSeries,setPrivateSystemTags,type DrawingSeason,type DrawingSystem,type DrawingTeam} from '@/lib/drawing-workspace';
import './content-navigator.css';

type Props={embedded?:boolean;initialKind?:'exercise'|'system'};
const LIBRARY='__private_library__';
const uniq=(v:string[])=>Array.from(new Set(v.filter(Boolean)));

export default function ContentNavigator({embedded=false}:Props){
 const[teams,setTeams]=useState<DrawingTeam[]>([]),[seasons,setSeasons]=useState<DrawingSeason[]>([]),[playbooks,setPlaybooks]=useState<Playbook[]>([]),[series,setSeries]=useState<PlaybookSeries[]>([]),[systems,setSystems]=useState<DrawingSystem[]>([]),[tags,setTags]=useState<PersonalSystemTag[]>([]);
 const[teamId,setTeamId]=useState(''),[season,setSeason]=useState('2026-2027'),[playbookId,setPlaybookId]=useState(''),[seriesId,setSeriesId]=useState(''),[tag,setTag]=useState(''),[q,setQ]=useState(''),[libraryQ,setLibraryQ]=useState(''),[openSeries,setOpenSeries]=useState<Set<string>>(new Set()),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[showLibrary,setShowLibrary]=useState(false),[actionId,setActionId]=useState('');
 async function load(){try{const[t,ss,ws,tg]=await Promise.all([listDrawingTeams(),ensureDrawingSeasons(),loadDrawingSystems(),ensureDefaultPersonalSystemTags()]);setTeams(t);setSeasons(ss);setSystems(ws.systems);setPlaybooks(ws.playbooks);setSeries(ws.series);setTags(tg)}catch(e){console.error('DESSIN workspace',e)}}
 useEffect(()=>{void load()},[]);
 const filteredPlaybooks=useMemo(()=>playbooks.filter(p=>(!teamId||p.team_id===teamId)&&(!season||!p.season||p.season===season)),[playbooks,teamId,season]);
 const activePlaybook=playbooks.find(p=>p.id===playbookId);const activeSeries=series.filter(s=>s.playbook_id===playbookId).sort((a,b)=>a.position-b.position);
 const inContext=useMemo(()=>playbookId===LIBRARY?systems:playbookId?systems.filter(s=>s.playbookIds.includes(playbookId)):[],[systems,playbookId]);
 const matches=(s:DrawingSystem,query=q)=>{const allTags=uniq([...(s.tags||[]),...s.inheritedTags]);return (!tag||allTags.includes(tag))&&(!query||`${s.title} ${allTags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))};
 const visible=useMemo(()=>inContext.filter(s=>!seriesId||s.seriesIds.includes(seriesId)).filter(s=>matches(s)),[inContext,seriesId,tag,q]);
 const unclassified=playbookId&&playbookId!==LIBRARY?visible.filter(s=>!s.seriesIds.some(id=>activeSeries.some(sr=>sr.id===id))):[];
 const privatePool=useMemo(()=>systems.filter(s=>!playbookId||playbookId===LIBRARY||!s.playbookIds.includes(playbookId)).filter(s=>!libraryQ||`${s.title} ${(s.tags||[]).join(' ')}`.toLowerCase().includes(libraryQ.toLowerCase())),[systems,playbookId,libraryQ]);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if(!(e.metaKey||e.ctrlKey)||!selected)return;if(e.key.toLowerCase()==='c'){e.preventDefault();localStorage.setItem('mybasket_copied_system_id',selected)}if(e.key.toLowerCase()==='v'){const id=localStorage.getItem('mybasket_copied_system_id');if(id){e.preventDefault();void doDuplicate(id)}}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[selected,playbookId,seriesId]);
 async function addSeason(){const v=prompt('Nouvelle saison (ex. 2027-2028) ?');if(!v)return;try{const row=await createDrawingSeason(v);await load();setSeason(row.label)}catch(e:any){alert(e?.message||'Impossible de créer la saison')}}
 async function addPlaybook(){const name=prompt('Nom du nouveau Playbook ?');if(!name?.trim())return;try{const pb=await createPlaybook({title:name.trim(),team_id:teamId||null,season:season||null});await load();setPlaybookId(pb.id);setShowLibrary(true)}catch(e:any){alert(e?.message||'Impossible de créer le Playbook')}}
 async function addSeries(){if(!playbookId||playbookId===LIBRARY){alert('Ouvre d’abord un Playbook.');return}const name=prompt('Nom de la nouvelle série ?');if(!name?.trim())return;const tagText=prompt('Tags de la série (séparés par des virgules) ?\nEx : Pick top, Spanish')||'';const values=uniq(tagText.split(',').map(x=>x.trim()));try{for(const value of values)await createPersonalSystemTag(value);const row=await createPlaybookSeries(playbookId,name,values);await load();setOpenSeries(v=>new Set(v).add(row.id))}catch(e:any){alert(e?.message||'Création impossible')}}
 async function addTag(){const name=prompt('Nouveau tag de jeu ?');if(!name?.trim())return;await createPersonalSystemTag(name);setTags(await listPersonalSystemTags());setTag(name.trim())}
 function toggle(id:string){setOpenSeries(v=>{const n=new Set(v);n.has(id)?n.delete(id):n.add(id);return n})}
 async function doDuplicate(id:string){setBusy(true);try{const newId=await duplicatePrivateSystem(id,playbookId&&playbookId!==LIBRARY?playbookId:null,seriesId||null);await load();setSelected(newId);openPrivateSystemInDrawing(newId)}catch(e:any){alert(e?.message||'Duplication impossible')}finally{setBusy(false)}}
 async function dropOnPlaybook(systemId:string){if(!playbookId||playbookId===LIBRARY)return;const s=systems.find(x=>x.id===systemId);if(!s)return;setBusy(true);try{await attachPrivateSystemToPlaybook(s,playbookId,null);await load()}catch(e:any){alert(e?.message||'Ajout impossible')}finally{setBusy(false)}}
 async function dropOnSeries(systemId:string,sr:PlaybookSeries){const s=systems.find(x=>x.id===systemId);if(!s)return;setBusy(true);try{await attachPrivateSystemToPlaybook(s,sr.playbook_id,sr.id);await load();setPlaybookId(sr.playbook_id);setOpenSeries(v=>new Set(v).add(sr.id))}catch(e:any){alert(e?.message||'Classement impossible')}finally{setBusy(false)}}
 async function removeFromPlaybook(s:DrawingSystem){if(!playbookId||playbookId===LIBRARY)return;setBusy(true);try{await detachPrivateSystemFromPlaybook(s,playbookId);await load();setSelected('')}catch(e:any){alert(e?.message||'Retrait impossible')}finally{setBusy(false)}}
 async function renameSystem(s:DrawingSystem){const name=prompt('Nouveau nom du système ?',s.title);if(!name?.trim())return;setBusy(true);try{await renamePrivateSystem(s.id,name);await load()}catch(e:any){alert(e?.message||'Renommage impossible')}finally{setBusy(false)}}
 async function editSystemTags(s:DrawingSystem){const current=uniq([...(s.tags||[]),...s.inheritedTags]);const value=prompt('Tags du système (séparés par des virgules)',current.join(', '));if(value===null)return;const values=uniq(value.split(',').map(x=>x.trim()));setBusy(true);try{for(const x of values)await createPersonalSystemTag(x);await setPrivateSystemTags(s.id,values);await load();setTags(await listPersonalSystemTags())}catch(e:any){alert(e?.message||'Tags impossibles à enregistrer')}finally{setBusy(false)}}
 async function editSeries(sr:PlaybookSeries){const name=prompt('Nom de la série ?',sr.name);if(!name?.trim())return;setBusy(true);try{await renameSeries(sr.id,name);await load()}catch(e:any){alert(e?.message||'Renommage impossible')}finally{setBusy(false)}}
 function systemRow(s:DrawingSystem,compact=false){const opened=actionId===s.id;return <div key={s.id} className='cn-system-wrap'><article className={`cn-system ${selected===s.id?'selected':''} ${compact?'compact':''}`} draggable onDragStart={e=>{e.dataTransfer.setData('text/mybasket-system',s.id);e.dataTransfer.effectAllowed='copyMove'}} onClick={()=>setSelected(s.id)} onDoubleClick={()=>openPrivateSystemInDrawing(s.id)}><div className='thumb'>{s.schemaImage?<img src={s.schemaImage} alt=''/>:'🏀'}</div><div className='meta'><b>{s.title}</b><small>{uniq([...(s.tags||[]),...s.inheritedTags]).slice(0,3).join(' · ')||'Non classé'}</small></div><button className='more' onClick={e=>{e.stopPropagation();setActionId(opened?'':s.id)}}><MoreHorizontal size={14}/></button></article>{opened&&<div className='cn44-menu'><button onClick={()=>openPrivateSystemInDrawing(s.id)}>Ouvrir dans DESSIN</button><button onClick={()=>void doDuplicate(s.id)}>Dupliquer et modifier</button><button onClick={()=>void renameSystem(s)}>Renommer</button><button onClick={()=>void editSystemTags(s)}>Modifier les tags</button>{playbookId&&playbookId!==LIBRARY&&<button className='danger' onClick={()=>void removeFromPlaybook(s)}>Retirer du Playbook</button>}</div>}</div>}
 return <aside className={`content-nav-v44 ${embedded?'embedded':''} ${busy?'busy':''}`}>
  <div className='cn44-title'><BookOpen size={16}/><b>BIBLIOTHÈQUE</b></div><div className='cn44-tabs'><button>EXERCICES</button><button className='active'>SYSTÈMES</button></div>
  <div className='cn44-selects'>
   <label>Équipe<select value={teamId} onChange={e=>{setTeamId(e.target.value);setPlaybookId('');setSeriesId('')}}><option value=''>Toutes les équipes</option><optgroup label='Mes équipes'>{teams.filter(t=>!t.scouted).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</optgroup><optgroup label='Équipes scoutées'>{teams.filter(t=>t.scouted).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</optgroup></select></label>
   <label>Saison<div className='row'><select value={season} onChange={e=>{setSeason(e.target.value);setPlaybookId('');setSeriesId('')}}><option value=''>Toutes les saisons</option>{seasons.map(s=><option key={s.id}>{s.label}</option>)}</select><button onClick={addSeason}><Plus size={14}/></button></div></label>
   <label>Playbook<div className='row'><select value={playbookId} onChange={e=>{setPlaybookId(e.target.value);setSeriesId('');setOpenSeries(new Set());setShowLibrary(false)}}><option value=''>Choisir un Playbook…</option><option value={LIBRARY}>Toute ma bibliothèque privée</option>{filteredPlaybooks.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}{playbooks.filter(p=>!filteredPlaybooks.includes(p)).length>0&&<optgroup label='Autres Playbooks'>{playbooks.filter(p=>!filteredPlaybooks.includes(p)).map(p=><option key={p.id} value={p.id}>{p.title}{p.season?` · ${p.season}`:''}</option>)}</optgroup>}</select><button onClick={addPlaybook}><Plus size={14}/></button></div></label>
  </div>
  {!playbookId?<div className='cn44-empty'><FolderOpen size={26}/><b>Choisis ton espace de travail</b><span>Reprends un Playbook existant, crée-en un nouveau ou ouvre volontairement toute ta bibliothèque privée.</span><button onClick={addPlaybook}><Plus size={14}/> Nouveau Playbook</button><button className='ghost' onClick={()=>setPlaybookId(LIBRARY)}>Toute ma bibliothèque privée</button></div>:<>
   <div className='cn44-search'><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Rechercher dans cet espace…'/></div>
   {playbookId!==LIBRARY&&<><div className='cn44-context'><b>{activePlaybook?.title}</b><small>{season||activePlaybook?.season||'Toutes saisons'}</small></div><button className='cn44-library-toggle' onClick={()=>setShowLibrary(v=>!v)}>{showLibrary?<X size={13}/>:<Plus size={13}/>} {showLibrary?'Fermer la bibliothèque':'Ajouter depuis ma bibliothèque'}</button>{showLibrary&&<div className='cn44-pool'><div className='cn44-search mini'><Search size={12}/><input value={libraryQ} onChange={e=>setLibraryQ(e.target.value)} placeholder='Mes systèmes privés…'/></div><small>Glisse un système sur le Playbook ou directement sur une Série.</small><div className='cn44-pool-list'>{privatePool.map(s=>systemRow(s,true))}</div></div>}
   <div className='cn44-playbook-drop' onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void dropOnPlaybook(e.dataTransfer.getData('text/mybasket-system'))}}><b>Déposer dans {activePlaybook?.title}</b><small>Ajoute le système au Playbook sans créer de copie.</small></div></>}
   {playbookId!==LIBRARY&&<section><div className='cn44-section'><b>SÉRIES</b><button onClick={addSeries}><Plus size={14}/></button></div>{activeSeries.length?activeSeries.map(sr=>{const children=visible.filter(s=>s.seriesIds.includes(sr.id));return <div key={sr.id} className='cn44-series' onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();e.stopPropagation();void dropOnSeries(e.dataTransfer.getData('text/mybasket-system'),sr)}}><div className='series-head-row'><button className='series-head' onClick={()=>toggle(sr.id)}>{openSeries.has(sr.id)?<ChevronDown size={14}/>:<ChevronRight size={14}/>} {sr.name}<span>{children.length}</span></button><button className='series-more' onClick={()=>void editSeries(sr)}><MoreHorizontal size={13}/></button></div>{sr.tags.length>0&&<div className='series-tags'>{sr.tags.map(x=><span key={x}>{x}</span>)}</div>}{openSeries.has(sr.id)&&<div className='series-children'>{children.map(s=>systemRow(s,true))}<small className='drop-hint'>Dépose ici pour classer dans {sr.name}</small></div>}</div>}):<small>Aucune série. Clique sur + pour en créer une.</small>}</section>}
   <section><div className='cn44-section'><b><Tags size={11}/> TAGS DE JEU</b><button onClick={addTag}><Plus size={14}/></button></div><div className='cn44-tags'><button className={!tag?'on':''} onClick={()=>setTag('')}>Tous</button>{tags.map(t=><button key={t.id} className={tag===t.name?'on':''} onClick={()=>setTag(tag===t.name?'':t.name)}>{t.name}</button>)}</div></section>
   {playbookId!==LIBRARY&&<div className='cn44-unclassified'><b>SANS SÉRIE</b>{unclassified.length?unclassified.map(s=>systemRow(s,true)):<small>Aucun système non classé.</small>}</div>}
   {playbookId===LIBRARY&&<><div className='cn44-list-title'><b>Ma bibliothèque privée</b><span>{visible.length}</span></div><div className='cn44-list'>{visible.map(s=>systemRow(s))}</div></>}
   {selected&&<div className='cn44-actions'><button onClick={()=>openPrivateSystemInDrawing(selected)}><FolderOpen size={13}/> Ouvrir</button><button onClick={()=>void doDuplicate(selected)}><Copy size={13}/> Dupliquer</button><span>⌘C / ⌘V</span></div>}
  </>}
 </aside>
}
