"use client";
import {useEffect,useMemo,useState} from "react";
import {listClubPlayers,listClubTeams,updateClubPlayer,type ClubPlayer,type ClubTeam} from "@/lib/club-core";
import {getCotisationsWorkspace,type PlayerCotisation} from "@/lib/club-cotisations";
import {adminFileComplete,currentClubSeason,listAdminFiles,saveAdminFile,type AdminMap,type ClubAdminFile} from "@/lib/club-licensee-admin";
import ClubA4Document from "./ClubA4Document";

const CHECKS=[
 ["identity_ok","Identité"],["registration_form_ok","Fiche inscription"],["photo_ok","Photo"],
 ["license_file_ok","Dossier licence"],["medical_ok","Médical"],["parental_ok","Autorisation parentale"]
] as const;

function money(c:number){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(c/100)}
function cotFor(p:ClubPlayer,cs:PlayerCotisation[]){return cs.find(c=>c.playerId===p.id)}
function payStatus(c?:PlayerCotisation){if(!c)return "missing";if(c.status==="paid"||c.paidCents>=c.amountCents)return "paid";if(c.paidCents>0)return "partial";return "unpaid"}

export default function ClubLicenseesHub({clubId,clubName,onNavigate}:{clubId:string;clubName:string;onNavigate?:(tab:string)=>void}){
 const [players,setPlayers]=useState<ClubPlayer[]>([]),[teams,setTeams]=useState<ClubTeam[]>([]),[cotis,setCotis]=useState<PlayerCotisation[]>([]),[admin,setAdmin]=useState<AdminMap>({});
 const [q,setQ]=useState(""),[filter,setFilter]=useState("all"),[team,setTeam]=useState(""),[selected,setSelected]=useState<ClubPlayer|null>(null),[busy,setBusy]=useState(""),[err,setErr]=useState(""),[print,setPrint]=useState(false);
 async function load(){setErr("");try{const [p,t,c,a]=await Promise.all([listClubPlayers(clubId),listClubTeams(clubId),getCotisationsWorkspace(clubId),listAdminFiles(clubId)]);setPlayers(p);setTeams(t);setCotis(c.cotisations);setAdmin(a)}catch(e:any){setErr(e?.message||"Chargement impossible")}}
 useEffect(()=>{void load()},[clubId]);
 const status=(p:ClubPlayer)=>{const a=admin[p.id],c=cotFor(p,cotis),pay=payStatus(c),lic=p.licenseStatus==="valid",docs=adminFileComplete(a),complete=docs&&lic&&pay==="paid";return{a,c,pay,lic,docs,complete}};
 const filtered=useMemo(()=>players.filter(p=>{const s=status(p),hay=`${p.lastName} ${p.firstName} ${p.category} ${p.licenseNumber||""}`.toLowerCase();if(q&&!hay.includes(q.toLowerCase()))return false;if(team&&p.teamId!==team)return false;if(filter==="incomplete"&&s.complete)return false;if(filter==="docs"&&s.docs)return false;if(filter==="license"&&s.lic)return false;if(filter==="unpaid"&&s.pay==="paid")return false;return true}),[players,admin,cotis,q,filter,team]);
 const stats=players.reduce((x,p)=>{const s=status(p);x.total++;if(s.complete)x.complete++;if(!s.docs)x.docs++;if(!s.lic)x.license++;if(s.pay!=="paid")x.unpaid++;return x},{total:0,complete:0,docs:0,license:0,unpaid:0});
 async function check(p:ClubPlayer,key:keyof ClubAdminFile,v:boolean){setBusy(`${p.id}:${key}`);try{const r=await saveAdminFile(clubId,p.id,{[key]:v} as any);setAdmin(x=>({...x,[p.id]:r}))}catch(e:any){setErr(e?.message||"Enregistrement impossible")}finally{setBusy("")}}
 async function license(p:ClubPlayer,v:boolean){setBusy(`${p.id}:license`);try{const u=await updateClubPlayer(p.id,{licenseStatus:v?"valid":"pending"});setPlayers(x=>x.map(y=>y.id===p.id?u:y))}catch(e:any){setErr(e?.message||"Enregistrement impossible")}finally{setBusy("")}}
 if(print)return <ClubA4Document title="Suivi des licenciés" subtitle={`${clubName} · Saison ${currentClubSeason()}`} onClose={()=>setPrint(false)}><table><thead><tr><th>Licencié</th><th>Équipe</th><th>Dossier</th><th>Licence</th><th>Cotisation</th><th>Statut</th></tr></thead><tbody>{filtered.map(p=>{const s=status(p),c=s.c;return <tr key={p.id}><td><b>{p.lastName} {p.firstName}</b><br/>{p.category}</td><td>{teams.find(t=>t.id===p.teamId)?.name||"—"}</td><td>{s.docs?"Complet":"À compléter"}</td><td>{s.lic?"Validée":"À faire"}</td><td>{c?`${money(c.paidCents)} / ${money(c.amountCents)}`:"Non affectée"}</td><td>{s.complete?"COMPLET":"À SUIVRE"}</td></tr>})}</tbody></table></ClubA4Document>;
 return <section className="hub">
  <div className="head"><div><p>GESTION ADMINISTRATIVE</p><h2>Licenciés</h2><span>Une seule fiche alimente dossier, licence, cotisation, équipe et relances.</span></div><button className="print" onClick={()=>setPrint(true)}>Imprimer / PDF</button></div>
  {err&&<div className="err">{err}</div>}
  <div className="kpis">
   <button onClick={()=>setFilter("all")}><b>{stats.total}</b><span>Licenciés</span></button><button onClick={()=>setFilter("incomplete")}><b>{stats.complete}</b><span>Complets</span></button>
   <button onClick={()=>setFilter("docs")}><b>{stats.docs}</b><span>Dossiers incomplets</span></button><button onClick={()=>setFilter("license")}><b>{stats.license}</b><span>Licences à faire</span></button><button onClick={()=>setFilter("unpaid")}><b>{stats.unpaid}</b><span>Cotisations à suivre</span></button>
  </div>
  <div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher nom, licence, catégorie…"/><select value={team} onChange={e=>setTeam(e.target.value)}><option value="">Toutes les équipes</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tous les statuts</option><option value="incomplete">À terminer</option><option value="docs">Dossier incomplet</option><option value="license">Licence à faire</option><option value="unpaid">Cotisation à suivre</option></select></div>
  <div className="table"><table><thead><tr><th>Licencié</th><th>Équipe</th><th>Dossier</th><th>Licence</th><th>Cotisation</th><th>Statut</th><th></th></tr></thead><tbody>{filtered.map(p=>{const s=status(p),c=s.c;return <tr key={p.id}><td><b>{p.lastName} {p.firstName}</b><small>{p.category} {p.licenseNumber?`· ${p.licenseNumber}`:""}</small></td><td>{teams.find(t=>t.id===p.teamId)?.name||"Non affecté"}</td><td><button className={`pill ${s.docs?"ok":"warn"}`} onClick={()=>setSelected(p)}>{s.docs?"✓ Complet":`${CHECKS.filter(([k])=>!!s.a?.[k]).length}/${CHECKS.length}`}</button></td><td><label className="tick"><input type="checkbox" checked={s.lic} disabled={busy===`${p.id}:license`} onChange={e=>void license(p,e.target.checked)}/><span>{s.lic?"Validée":"À faire"}</span></label></td><td><button className={`pill ${s.pay}`} onClick={()=>onNavigate?.("cotisations")}>{c?`${money(c.paidCents)} / ${money(c.amountCents)}`:"Non affectée"}</button></td><td><span className={`state ${s.complete?"green":s.docs||s.pay==="partial"?"orange":"red"}`}>{s.complete?"Complet":"À suivre"}</span></td><td><button className="open" onClick={()=>setSelected(p)}>Ouvrir</button></td></tr>})}</tbody></table></div>
  {selected&&<div className="veil" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><aside><header><div><p>FICHE LICENCIÉ</p><h2>{selected.lastName} {selected.firstName}</h2><span>{selected.category} · {teams.find(t=>t.id===selected.teamId)?.name||"Sans équipe"}</span></div><button onClick={()=>setSelected(null)}>×</button></header>
   <div className="block"><h3>Dossier d'inscription</h3><p>Tu coches uniquement ce qui est reçu. « Dossier complet » est calculé automatiquement.</p><div className="checks">{CHECKS.map(([k,l])=><label key={k}><input type="checkbox" checked={!!admin[selected.id]?.[k]} disabled={busy===`${selected.id}:${k}`} onChange={e=>void check(selected,k,e.target.checked)}/><span>{l}</span></label>)}</div></div>
   <div className="block"><h3>Licence</h3><label className="big"><input type="checkbox" checked={status(selected).lic} onChange={e=>void license(selected,e.target.checked)}/><span>Licence fédérale validée</span></label></div>
   <div className="block"><h3>Cotisation</h3>{(()=>{const c=status(selected).c;return c?<><b>{money(c.paidCents)} encaissé sur {money(c.amountCents)}</b><p>Reste : {money(Math.max(0,c.amountCents-c.paidCents))}</p><button className="go" onClick={()=>onNavigate?.("cotisations")}>Gérer les paiements</button></>:<><p>Aucun plan de cotisation affecté.</p><button className="go" onClick={()=>onNavigate?.("cotisations")}>Affecter une cotisation</button></>})()}</div>
   <div className="quick"><button onClick={()=>onNavigate?.("relances")}>Ouvrir les relances</button><button onClick={()=>onNavigate?.("communication")}>Communiquer</button><button onClick={()=>onNavigate?.("equipes")}>Voir les équipes</button></div>
  </aside></div>}
  <style jsx>{`
   .hub{display:grid;gap:15px}.head{display:flex;justify-content:space-between;gap:15px;align-items:center}.head p,.veil header p{margin:0;color:#d4a24c;font-size:10px;font-weight:900;letter-spacing:.12em}.head h2{margin:3px 0;color:#5a1727;font-size:27px}.head span{color:#88767c;font-size:12px}.print,.open,.go,.quick button{border:0;background:#6b1a2c;color:white;border-radius:10px;padding:10px 13px;font-weight:900;cursor:pointer}.err{background:#fdeaea;color:#a73535;padding:10px;border-radius:10px}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.kpis button{border:1px solid #eaded8;background:white;border-radius:14px;padding:13px;text-align:left;cursor:pointer}.kpis b{display:block;color:#6b1a2c;font-size:22px}.kpis span{font-size:10px;color:#8c787e;font-weight:800}.filters{display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px}.filters input,.filters select{height:42px;border:1px solid #ddd0cb;border-radius:10px;padding:0 11px;background:white}.table{overflow:auto;border:1px solid #eaded8;border-radius:14px;background:white}.table table{width:100%;min-width:900px;border-collapse:collapse}.table th,.table td{padding:11px;border-bottom:1px solid #f1e8e4;text-align:left;font-size:12px}.table th{font-size:10px;color:#8c777d;background:#faf7f5;text-transform:uppercase}.table td small{display:block;color:#97858a;margin-top:2px}.pill{border:0;border-radius:999px;padding:7px 9px;font-size:10px;font-weight:900;cursor:pointer}.pill.ok,.pill.paid{background:#e8f6ee;color:#217146}.pill.warn,.pill.partial{background:#fff2dc;color:#8b6114}.pill.unpaid,.pill.missing{background:#fdeaea;color:#a73535}.tick{display:flex;align-items:center;gap:6px}.tick input,.checks input,.big input{width:18px;height:18px;accent-color:#6b1a2c}.state{border-radius:999px;padding:6px 8px;font-size:10px;font-weight:900}.green{background:#e8f6ee;color:#217146}.orange{background:#fff2dc;color:#8b6114}.red{background:#fdeaea;color:#a73535}.open{padding:7px 9px;font-size:10px}
   .veil{position:fixed;inset:0;background:#2d161d66;z-index:1000;display:flex;justify-content:flex-end}.veil aside{width:min(570px,96vw);height:100%;overflow:auto;background:#f8f5f3;padding:20px;box-shadow:-15px 0 45px #0002}.veil header{display:flex;justify-content:space-between}.veil header h2{margin:4px 0;color:#571625}.veil header span{color:#88767c;font-size:12px}.veil header>button{width:38px;height:38px;border:0;border-radius:10px;background:white;font-size:24px}.block{background:white;border:1px solid #eaded8;border-radius:14px;padding:15px;margin-top:12px}.block h3{margin:0 0 4px}.block p{font-size:11px;color:#8a777d}.checks{display:grid;grid-template-columns:1fr 1fr;gap:7px}.checks label,.big{display:flex;align-items:center;gap:9px;border:1px solid #eee3df;border-radius:10px;padding:10px}.quick{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:12px}.quick button{background:white;color:#6b1a2c;border:1px solid #dccbc5}
   @media(max-width:900px){.kpis{grid-template-columns:1fr 1fr}.filters{grid-template-columns:1fr}.checks,.quick{grid-template-columns:1fr}}
  `}</style>
 </section>
}
