"use client";
import { useEffect, useRef, useState } from "react";
import { buildLocalVideoDescriptor, descriptorMatches, type LocalVideoDescriptor } from "@/lib/video/local-project-video";

export type LocalProjectVideoValue={file:File;objectUrl:string;descriptor:LocalVideoDescriptor};
type Props={projectId:string;expected?:LocalVideoDescriptor|null;onLinked:(v:LocalProjectVideoValue)=>void;onUnlinked?:()=>void};
export default function LocalProjectVideoPicker({projectId,expected,onLinked,onUnlinked}:Props){
 const inputRef=useRef<HTMLInputElement|null>(null);const urlRef=useRef<string|null>(null);const [linked,setLinked]=useState<LocalProjectVideoValue|null>(null);const [warning,setWarning]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>()=>{if(urlRef.current)URL.revokeObjectURL(urlRef.current)},[]);
 async function choose(file:File|null){if(!file)return;setBusy(true);setWarning("");try{const descriptor=await buildLocalVideoDescriptor(file);if(expected&&!descriptorMatches(expected,descriptor))setWarning("Cette vidéo semble différente de celle utilisée pour coder le projet.");if(urlRef.current)URL.revokeObjectURL(urlRef.current);const objectUrl=URL.createObjectURL(file);urlRef.current=objectUrl;const value={file,objectUrl,descriptor};setLinked(value);onLinked(value);try{localStorage.setItem(`mybasket_local_video_descriptor_${projectId}`,JSON.stringify(descriptor))}catch{}}finally{setBusy(false);if(inputRef.current)inputRef.current.value=""}}
 function unlink(){if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=null;setLinked(null);setWarning("");onUnlinked?.()}
 return <section className="lpv"><div className="head"><div><b>🎬 Vidéo locale du match</b><span>Aucun upload · lecture directe depuis cet ordinateur</span></div><i>0 Go MyBasket</i></div>{linked?<div className="row ok"><strong>✓</strong><div><b>{linked.descriptor.name}</b><span>⚡ Lecture locale optimisée pour le codage et les clips</span></div><button onClick={()=>inputRef.current?.click()}>Changer</button><button className="danger" onClick={unlink}>Retirer</button></div>:<div className="row"><div><b>Relie ta copie du match</b><span>La vidéo reste sur ton Mac/PC. MyBasket conserve uniquement les timecodes.</span></div><button onClick={()=>inputRef.current?.click()}>{busy?"Analyse…":"📁 Relier une vidéo locale"}</button></div>}{warning&&<p>⚠️ {warning}</p>}<input ref={inputRef} hidden type="file" accept="video/*,.mp4,.mov,.m4v,.webm" onChange={e=>void choose(e.target.files?.[0]||null)}/><style jsx>{`.lpv{border:1px solid #2b3950;border-radius:14px;background:#0d1727;color:#f3f6fb;overflow:hidden}.head{padding:11px 13px;border-bottom:1px solid #27354a;display:flex;align-items:center;justify-content:space-between;gap:10px}.head>div,.row>div{display:grid;gap:3px;min-width:0}.head b,.row b{font-size:11px}.head span,.row span{font-size:9px;color:#94a2b7}.head i{font-style:normal;font-size:9px;font-weight:900;border:1px solid #2d6844;border-radius:999px;padding:5px 8px;color:#75d795;background:#102319;white-space:nowrap}.row{display:flex;align-items:center;gap:9px;padding:11px 13px}.row>div{flex:1}.row.ok{background:#0d1d16}.row>strong{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#246b40}.row button{border:1px solid #d4a24c;border-radius:8px;background:rgba(212,162,76,.1);color:#efc45d;padding:7px 9px;font-size:9px;font-weight:900;cursor:pointer}.row button.danger{border-color:#613641;color:#ee8f9d;background:#1c1218}p{margin:0 13px 11px;padding:8px 9px;border:1px solid #725a25;border-radius:8px;background:#251d0d;color:#f0c35f;font-size:9px}`} </style></section>
}
