"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import InstitutionalPlanning from "@/components/institutionnel/InstitutionalPlanning";

type EventRow = { id:string; event_date:string; start_time:string|null; end_time:string|null; title:string; event_type:string; location:string|null; intervenant:string|null; source_type?:string|null; cohort_id?:string|null };
type Cohort = { id:string; name:string; planning_title?:string|null };
const MONTHS=["JANVIER","FÉVRIER","MARS","AVRIL","MAI","JUIN","JUILLET","AOÛT","SEPTEMBRE","OCTOBRE","NOVEMBRE","DÉCEMBRE"];
const DAYS=["L","M","M","J","V","S","D"];
const pad=(n:number)=>String(n).padStart(2,"0");
function color(type:string){if(type==="formation")return {bg:"#D4A24C",fg:"#2B2119"};if(type==="detection"||type==="selection"||type==="stage")return {bg:"#6B1A2C",fg:"#fff"};if(type==="meeting")return {bg:"#2563EB",fg:"#fff"};return {bg:"#64748B",fg:"#fff"}}

export default function InstitutionalCalendarHub({structureId,onGoTraining,onGoPlayers}:{structureId:string;onGoTraining:()=>void;onGoPlayers:()=>void}){
 const sb=useMemo(()=>createClient(),[]);const today=new Date();const[year,setYear]=useState(today.getFullYear()),[month,setMonth]=useState(today.getMonth()),[events,setEvents]=useState<EventRow[]>([]),[cohorts,setCohorts]=useState<Cohort[]>([]),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const[a,b]=await Promise.all([sb.from("institutional_events").select("id,event_date,start_time,end_time,title,event_type,location,intervenant,source_type,cohort_id").eq("structure_id",structureId).eq("archived",false).order("event_date").order("start_time"),sb.from("training_cohorts").select("id,name,planning_title").eq("institution_id",structureId).order("created_at",{ascending:false})]);if(a.error)console.error(a.error);setEvents((a.data||[]) as EventRow[]);setCohorts((b.data||[]) as Cohort[]);setLoading(false)}
 useEffect(()=>{void load()},[structureId]); // eslint-disable-line react-hooks/exhaustive-deps
 function move(delta:number){const d=new Date(year,month+delta,1);setYear(d.getFullYear());setMonth(d.getMonth())}
 const cells=useMemo(()=>{const first=new Date(year,month,1),last=new Date(year,month+1,0);const before=(first.getDay()+6)%7;const total=Math.ceil((before+last.getDate())/7)*7;return Array.from({length:total},(_,i)=>{const day=i-before+1;return day<1||day>last.getDate()?null:day})},[year,month]);
 const cohortMap=useMemo(()=>new Map(cohorts.map(c=>[c.id,c])),[cohorts]);
 const trainingEvents=events.filter(e=>e.event_type==="formation").slice(0,40);
 return <div className="hub">
  <section className="calendarCard">
   <div className="calHead"><div><p>CALENDRIER INSTITUTION</p><h3>{MONTHS[month]} {year}</h3><span>Même logique que Mon Calendrier, alimentée par les modules de l’Institution.</span></div><div><button className="ghost" onClick={()=>move(-1)}>‹</button><button className="ghost" onClick={()=>{setYear(today.getFullYear());setMonth(today.getMonth())}}>Aujourd’hui</button><button className="ghost" onClick={()=>move(1)}>›</button></div></div>
   <div className="legend"><span><i style={{background:"#D4A24C"}}/> Formation</span><span><i style={{background:"#6B1A2C"}}/> Détection / sélection</span><span><i style={{background:"#2563EB"}}/> Réunion</span><span><i style={{background:"#64748B"}}/> Autre</span></div>
   {loading?<div className="empty">Chargement…</div>:<div className="calGrid">{DAYS.map((d,i)=><div className="dow" key={`${d}-${i}`}>{d}</div>)}{cells.map((day,i)=>{if(day==null)return <div className="cell muted" key={`x-${i}`}/>;const date=`${year}-${pad(month+1)}-${pad(day)}`,dayEvents=events.filter(e=>e.event_date===date);const isToday=date===new Date().toISOString().slice(0,10);return <div className={`cell ${isToday?"today":""}`} key={date}><b>{day}</b><div>{dayEvents.map(e=>{const c=color(e.event_type);return <button key={e.id} className="event" style={{background:c.bg,color:c.fg}} title={`${e.title}${e.location?` · ${e.location}`:""}`} onClick={e.event_type==="formation"?onGoTraining:e.event_type==="detection"||e.event_type==="selection"?onGoPlayers:undefined}><small>{e.start_time?.slice(0,5)||""}</small><span>{e.title}</span></button>})}</div></div>})}</div>}
  </section>
  <section className="trainingLinked"><div className="sectionHead"><div><p>PLANNING DE FORMATION LIÉ</p><h3>Les blocs de formation alimentent automatiquement le calendrier du dessus</h3></div><button onClick={onGoTraining}>Ouvrir Formation des cadres →</button></div><div className="linked">{trainingEvents.map(e=><article key={e.id}><time>{new Date(e.event_date+"T12:00:00").toLocaleDateString("fr-FR")}</time><div><b>{e.title}</b><small>{e.start_time?.slice(0,5)||""}{e.end_time?` – ${e.end_time.slice(0,5)}`:""} · {e.location||"Lieu —"}{e.cohort_id&&cohortMap.get(e.cohort_id)?` · ${cohortMap.get(e.cohort_id)?.planning_title||cohortMap.get(e.cohort_id)?.name}`:""}</small></div></article>)}{!trainingEvents.length&&<p className="empty">Aucun bloc de formation synchronisé pour le moment.</p>}</div></section>
  <section className="general"><div className="sectionHead"><div><p>ÉVÉNEMENTS & ORGANISATION</p><h3>Planning général de l’Institution</h3><span>Réunions, salles et événements libres. L’export PDF est enregistré automatiquement dans Documents.</span></div></div><InstitutionalPlanning structureId={structureId}/></section>
  <style jsx>{`.hub{display:grid;gap:14px}.hub>section{background:#fff;border:1px solid #eadfd8;border-radius:16px;padding:14px}.calHead,.sectionHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.calHead p,.sectionHead p{margin:0;color:#d4a24c;font-size:.66rem;font-weight:1000;letter-spacing:.12em}.calHead h3,.sectionHead h3{margin:3px 0;color:#4d1420}.calHead span,.sectionHead span{color:#817379;font-size:.76rem}.calHead>div:last-child{display:flex;gap:5px}.ghost,.sectionHead button{border:1px solid #d9c9c4;border-radius:9px;background:#fff;color:#6b1a2c;padding:8px 10px;font-weight:900;cursor:pointer}.legend{display:flex;gap:14px;flex-wrap:wrap;margin:12px 0 8px;font-size:.7rem;color:#74676b}.legend span{display:flex;align-items:center;gap:5px}.legend i{width:9px;height:9px;border-radius:50%}.calGrid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:1px;background:#e8dfda;border:1px solid #e8dfda;border-radius:11px;overflow:hidden}.dow{background:#f7f2ef;text-align:center;padding:8px;font-size:.67rem;font-weight:1000;color:#6b1a2c}.cell{background:#fff;min-height:118px;padding:7px;min-width:0}.cell.muted{background:#faf8f7}.cell.today{box-shadow:inset 0 0 0 2px #d4a24c}.cell>b{display:block;font-size:.72rem;margin-bottom:5px;color:#55464b}.cell>div{display:grid;gap:3px}.event{border:0;border-radius:6px;padding:4px 5px;display:grid;grid-template-columns:32px minmax(0,1fr);gap:3px;text-align:left;cursor:pointer;min-width:0}.event small{font-size:.57rem;font-weight:1000}.event span{font-size:.61rem;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.linked{display:grid;gap:6px;margin-top:10px}.linked article{display:grid;grid-template-columns:110px 1fr;gap:10px;padding:9px;border:1px solid #eee3de;border-radius:10px}.linked time{font-weight:900;color:#6b1a2c}.linked b,.linked small{display:block}.linked small,.empty{color:#817379;font-size:.72rem}.general{display:grid;gap:12px}@media(max-width:800px){.cell{min-height:92px;padding:4px}.event{grid-template-columns:1fr}.event small{display:none}.calHead,.sectionHead{flex-direction:column}}@media(max-width:600px){.calGrid{overflow:auto;grid-template-columns:repeat(7,minmax(86px,1fr))}.calendarCard{overflow:hidden}.linked article{grid-template-columns:1fr}}`}</style>
 </div>
}
