"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type D={id:string;title:string;document_type:string;file_url:string|null;content:any;created_at:string};
export default function InstitutionalDocuments({structureId}:{structureId:string}){const s=useMemo(()=>createClient(),[]),[rows,setRows]=useState<D[]>([]),[title,setTitle]=useState(""),[text,setText]=useState("");async function load(){const{data}=await s.from("institutional_documents").select("*").eq("structure_id",structureId).eq("archived",false).order("updated_at",{ascending:false});setRows((data||[]) as D[])}useEffect(()=>{void load()},[structureId]);// eslint-disable-line
async function addNote(){const{data:{user}}=await s.auth.getUser();if(!user||!title.trim())return;const q=await s.from("institutional_documents").insert({structure_id:structureId,title:title.trim(),document_type:"resource",content:{text},created_by:user.id});if(q.error)return alert(q.error.message);setTitle("");setText("");await load()}
async function upload(file:File){const{data:{user}}=await s.auth.getUser();if(!user)return;const clean=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${structureId}/${crypto.randomUUID()}-${clean}`;const u=await s.storage.from("institutional-documents").upload(path,file);if(u.error)return alert(u.error.message);const url=s.storage.from("institutional-documents").getPublicUrl(path).data.publicUrl;const q=await s.from("institutional_documents").insert({structure_id:structureId,title:file.name,document_type:"file",storage_path:path,file_url:url,created_by:user.id});if(q.error)return alert(q.error.message);await load()}
async function edit(row:D){const next=prompt("Titre",row.title);if(next===null)return;const q=await s.from("institutional_documents").update({title:next,updated_at:new Date().toISOString()}).eq("id",row.id);if(q.error)return alert(q.error.message);await load()}
async function remove(id:string){if(!confirm("Archiver ce document ?"))return;await s.from("institutional_documents").update({archived:true,archived_at:new Date().toISOString()}).eq("id",id);await load()}
return <div className="docs"><div className="create"><input placeholder="Titre de la fiche / ressource" value={title} onChange={e=>setTitle(e.target.value)}/><textarea placeholder="Définition, repères, contenu technique…" value={text} onChange={e=>setText(e.target.value)}/><div><button onClick={addNote}>+ Fiche ressource</button><label className="upload">+ Fichier<input hidden type="file" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=""}}/></label></div></div><div className="grid">{rows.map(r=><article key={r.id}><small>{r.document_type}</small><h3>{r.title}</h3>{r.content?.text&&<p>{r.content.text}</p>}<div>{r.file_url&&<a href={r.file_url} target="_blank" rel="noreferrer">Ouvrir</a>}<button onClick={()=>edit(r)}>Modifier</button><button className="danger" onClick={()=>remove(r.id)}>Supprimer</button></div></article>)}</div><style jsx>{`.docs{display:grid;gap:10px}.create{display:grid;gap:7px}.create input,.create textarea{border:1px solid #ddd1ca;border-radius:8px;padding:8px}.create div{display:flex;gap:6px}.create button,.upload,article button,article a{background:#6b1a2c;color:#fff;border:0;border-radius:8px;padding:8px 10px;font-weight:900;text-decoration:none;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}article{border:1px solid #eee4df;border-radius:10px;padding:10px}article small{color:#d4a24c;font-weight:900}article h3{margin:4px 0}article p{white-space:pre-wrap;color:#74665f;font-size:.78rem}article>div{display:flex;gap:5px;flex-wrap:wrap}.danger{background:#fff!important;color:#b42318!important;border:1px solid #e7bbb7!important}@media(max-width:850px){.grid{grid-template-columns:1fr}}`}</style></div>}
