"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type P={id:string;first_name:string;last_name:string;birthdate:string|null;email:string|null;phone:string|null;sex:string|null;photo_url:string|null;father_height_cm:number|null;mother_height_cm:number|null};
type S={id:string;season_label:string};
type E={id:string;season_id:string;player_id:string;club_name:string|null;club_email:string|null;club_logo_url:string|null;category:string|null;position_label:string|null;status:string};
type M={id:string;season_id:string;player_id:string;measured_at:string;height_cm:number|null;weight_kg:number|null;wingspan_cm:number|null;shoe_size:number|null};
type AS={id:string;season_id:string;session_date:string;title:string;location:string|null};
type AR={id:string;session_id:string;season_id:string;player_id:string;status:"present"|"absent"|"excused"};
type C={id:string;season_id:string|null;player_id:string;author_name:string|null;comment_date:string;profile_text:string|null;strengths_text:string|null;improvement_text:string|null;projection_text:string|null;free_comment:string|null;share_with_club:boolean};

const today=()=>new Date().toISOString().slice(0,10);
const fmt=(d?:string|null)=>d?d.slice(0,10).split("-").reverse().join("/"):"—";
const num=(x:string)=>x.trim()===""?null:Number(x.replace(",","."));

export default function InstitutionalPlayerNotebook({structureId}:{structureId:string}){
 const sb=useMemo(()=>createClient(),[]);
 const[players,setPlayers]=useState<P[]>([]),[seasons,setSeasons]=useState<S[]>([]),[entries,setEntries]=useState<E[]>([]),[measurements,setMeasurements]=useState<M[]>([]);
 const[sessions,setSessions]=useState<AS[]>([]),[records,setRecords]=useState<AR[]>([]),[comments,setComments]=useState<C[]>([]);
 const[seasonId,setSeasonId]=useState(""),[selected,setSelected]=useState(""),[sexFilter,setSexFilter]=useState("");
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState("");
 const[seasonLabel,setSeasonLabel]=useState("2026-2027"),[copySeason,setCopySeason]=useState("");
 const[newPlayer,setNewPlayer]=useState({first_name:"",last_name:"",birthdate:"",sex:"",email:"",phone:""});
 const[existing,setExisting]=useState("");
 const[measure,setMeasure]=useState({measured_at:today(),height_cm:"",weight_kg:"",wingspan_cm:"",shoe_size:""});
 const[attendance,setAttendance]=useState({session_date:today(),title:"Entraînement / sélection",location:""});
 const[comment,setComment]=useState({profile_text:"",strengths_text:"",improvement_text:"",projection_text:"",free_comment:"",share_with_club:true});
 const toast=(x:string)=>{setMsg(x);setTimeout(()=>setMsg(""),2200)};

 async function reload(preferred?:string){
  const[p,s,e,m,ss,rr,c]=await Promise.all([
   sb.from("institutional_players").select("id,first_name,last_name,birthdate,email,phone,sex,photo_url,father_height_cm,mother_height_cm").eq("structure_id",structureId).eq("archived",false).order("last_name"),
   sb.from("institutional_player_tracking_seasons").select("id,season_label").eq("structure_id",structureId).eq("archived",false).order("season_label",{ascending:false}),
   sb.from("institutional_player_season_entries").select("*").eq("structure_id",structureId),
   sb.from("institutional_player_measurements").select("*").eq("structure_id",structureId).order("measured_at"),
   sb.from("institutional_player_attendance_sessions").select("*").eq("structure_id",structureId).order("session_date",{ascending:false}),
   sb.from("institutional_player_attendance_records").select("*").eq("structure_id",structureId),
   sb.from("institutional_player_basket_comments").select("*").eq("structure_id",structureId).order("comment_date",{ascending:false}),
  ]);
  const er=p.error||s.error||e.error||m.error||ss.error||rr.error||c.error;if(er){alert(er.message);return}
  setPlayers((p.data||[]) as P[]);setSeasons((s.data||[]) as S[]);setEntries((e.data||[]) as E[]);setMeasurements((m.data||[]) as M[]);
  setSessions((ss.data||[]) as AS[]);setRecords((rr.data||[]) as AR[]);setComments((c.data||[]) as C[]);
  const sid=preferred||seasonId||(s.data?.[0]?.id||"");setSeasonId(sid);
 }
 useEffect(()=>{void reload()},[structureId]);// eslint-disable-line

 const seasonEntries=entries.filter(e=>e.season_id===seasonId),mapP=new Map(players.map(p=>[p.id,p]));
 const rows=seasonEntries.map(e=>({e,p:mapP.get(e.player_id)!})).filter(x=>x.p).filter(x=>!sexFilter||x.p.sex===sexFilter);
 const player=players.find(p=>p.id===selected)||null,entry=entries.find(e=>e.player_id===selected&&e.season_id===seasonId)||null;
 const playerMeasures=measurements.filter(m=>m.player_id===selected),playerComments=comments.filter(c=>c.player_id===selected);
 const rate=(pid:string)=>{const ss=sessions.filter(s=>s.season_id===seasonId),ids=new Set(ss.map(s=>s.id));if(!ss.length)return null;const rr=records.filter(r=>r.player_id===pid&&ids.has(r.session_id));return Math.round(rr.filter(r=>r.status==="present").length/ss.length*100)};

 async function createSeason(){
  const{data:{user}}=await sb.auth.getUser();if(!user)return;
  const q=await sb.from("institutional_player_tracking_seasons").insert({structure_id:structureId,season_label:seasonLabel,created_by:user.id}).select("id").single();
  if(q.error)return alert(q.error.message);
  if(copySeason){const old=entries.filter(e=>e.season_id===copySeason);if(old.length)await sb.from("institutional_player_season_entries").insert(old.map(e=>({structure_id:structureId,season_id:q.data.id,player_id:e.player_id,club_name:e.club_name,club_email:e.club_email,club_logo_url:e.club_logo_url,category:e.category,position_label:e.position_label,status:"followed",created_by:user.id})))}
  await reload(q.data.id);toast("Saison créée");
 }
 async function createPlayer(){
  const{data:{user}}=await sb.auth.getUser();if(!user||!seasonId)return;
  const q=await sb.from("institutional_players").insert({structure_id:structureId,...newPlayer,birthdate:newPlayer.birthdate||null,sex:newPlayer.sex||null,status:"followed",created_by:user.id}).select("id").single();
  if(q.error)return alert(q.error.message);await sb.from("institutional_player_season_entries").insert({structure_id:structureId,season_id:seasonId,player_id:q.data.id,status:"followed",created_by:user.id});
  setNewPlayer({first_name:"",last_name:"",birthdate:"",sex:"",email:"",phone:""});await reload(seasonId);setSelected(q.data.id)
 }
 async function addExisting(){const{data:{user}}=await sb.auth.getUser();if(!user||!existing)return;const q=await sb.from("institutional_player_season_entries").insert({structure_id:structureId,season_id:seasonId,player_id:existing,status:"followed",created_by:user.id});if(q.error)return alert(q.error.message);setExisting("");await reload(seasonId)}
 async function patchEntry(id:string,patch:Partial<E>){const q=await sb.from("institutional_player_season_entries").update({...patch,updated_at:new Date().toISOString()}).eq("id",id);if(q.error)return alert(q.error.message);setEntries(v=>v.map(x=>x.id===id?{...x,...patch}:x))}
 async function addMeasure(){if(!player||!seasonId)return;const{data:{user}}=await sb.auth.getUser();if(!user)return;const vals={height_cm:num(measure.height_cm),weight_kg:num(measure.weight_kg),wingspan_cm:num(measure.wingspan_cm),shoe_size:num(measure.shoe_size)};if(Object.values(vals).every(x=>x==null))return alert("Renseigne une mesure");const q=await sb.from("institutional_player_measurements").insert({structure_id:structureId,player_id:player.id,season_id:seasonId,measured_at:measure.measured_at,...vals,created_by:user.id});if(q.error)return alert(q.error.message);setMeasure({measured_at:today(),height_cm:"",weight_kg:"",wingspan_cm:"",shoe_size:""});await reload(seasonId)}
 async function createAttendance(){const{data:{user}}=await sb.auth.getUser();if(!user)return;const q=await sb.from("institutional_player_attendance_sessions").insert({structure_id:structureId,season_id:seasonId,...attendance,location:attendance.location||null,created_by:user.id}).select("id").single();if(q.error)return alert(q.error.message);if(seasonEntries.length)await sb.from("institutional_player_attendance_records").insert(seasonEntries.map(e=>({structure_id:structureId,session_id:q.data.id,season_id:seasonId,player_id:e.player_id,status:"absent",created_by:user.id})));await reload(seasonId)}
 async function presence(sessionId:string,pid:string,status:AR["status"]){const old=records.find(r=>r.session_id===sessionId&&r.player_id===pid);if(old)await sb.from("institutional_player_attendance_records").update({status,updated_at:new Date().toISOString()}).eq("id",old.id);else{const{data:{user}}=await sb.auth.getUser();if(user)await sb.from("institutional_player_attendance_records").insert({structure_id:structureId,session_id:sessionId,season_id:seasonId,player_id:pid,status,created_by:user.id})}await reload(seasonId)}
 async function addComment(){if(!player)return;const{data:{user}}=await sb.auth.getUser();if(!user)return;const prof=await sb.from("profiles").select("display_name").eq("id",user.id).maybeSingle();const q=await sb.from("institutional_player_basket_comments").insert({structure_id:structureId,season_id:seasonId,player_id:player.id,author_id:user.id,author_name:prof.data?.display_name||user.email,comment_date:today(),...comment});if(q.error)return alert(q.error.message);setComment({profile_text:"",strengths_text:"",improvement_text:"",projection_text:"",free_comment:"",share_with_club:true});await reload(seasonId)}
 async function uploadAsset(file:File,kind:"player"|"club"|"structure"){
  if(!file)return;setBusy("upload");const path=`${structureId}/${kind}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await sb.storage.from("institutional-assets").upload(path,file,{upsert:false});if(up.error){setBusy("");return alert(up.error.message)}const{data}=sb.storage.from("institutional-assets").getPublicUrl(path);
  if(kind==="player"&&player)await sb.from("institutional_players").update({photo_url:data.publicUrl}).eq("id",player.id);
  if(kind==="club"&&entry)await sb.from("institutional_player_season_entries").update({club_logo_url:data.publicUrl}).eq("id",entry.id);
  if(kind==="structure")await sb.from("institutional_structures").update({logo_url:data.publicUrl}).eq("id",structureId);
  setBusy("");await reload(seasonId)
 }
 async function parentLink(){if(!player)return;const r=await fetch("/api/institutionnel/parent-questionnaire/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({structureId,playerId:player.id,seasonId})});const j=await r.json();if(!r.ok)return alert(j.error);const url=`${location.origin}/institutionnel/questionnaire-parent/${j.token}`;await navigator.clipboard.writeText(url);prompt("Lien parent créé et copié :",url)}
 async function downloadPdf(){if(!player)return;setBusy("pdf");const r=await fetch("/api/institutionnel/player-notebook/pdf",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({structureId,playerId:player.id,seasonId})});if(!r.ok){const j=await r.json();setBusy("");return alert(j.error)}const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`Cahier_${player.first_name}_${player.last_name}.pdf`;a.click();URL.revokeObjectURL(u);setBusy("")}
 async function sendClub(){if(!player||!entry?.club_email)return alert("Renseigne l'email du club");setBusy("send");const r=await fetch("/api/institutionnel/player-notebook/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({structureId,playerId:player.id,seasonId,to:entry.club_email})});const j=await r.json();setBusy("");if(!r.ok)return alert(j.error);toast("Cahier envoyé au club")}

 return <div className="nb">{msg&&<div className="toast">{msg}</div>}
  <section className="card head"><div><p>FORMATION DU JOUEUR</p><h2>Cahiers de suivi</h2><span>Chaque saison enrichit le même historique joueur.</span></div><div className="actions"><select value={seasonId} onChange={e=>{setSeasonId(e.target.value);setSelected("")}}><option value="">Saison</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.season_label}</option>)}</select><button onClick={()=>window.print()}>Imprimer</button></div></section>
  <section className="card"><h3>Créer une saison</h3><div className="line"><input value={seasonLabel} onChange={e=>setSeasonLabel(e.target.value)}/><select value={copySeason} onChange={e=>setCopySeason(e.target.value)}><option value="">Base vide</option>{seasons.map(s=><option key={s.id} value={s.id}>Reprendre {s.season_label}</option>)}</select><button onClick={createSeason}>+ Créer</button></div></section>
  {seasonId&&<><section className="card"><div className="title"><h3>Effectif</h3><select value={sexFilter} onChange={e=>setSexFilter(e.target.value)}><option value="">Tous</option><option value="M">Garçons</option><option value="F">Filles</option></select></div>
   <div className="line"><select value={existing} onChange={e=>setExisting(e.target.value)}><option value="">Joueur déjà connu…</option>{players.filter(p=>!seasonEntries.some(x=>x.player_id===p.id)).map(p=><option key={p.id} value={p.id}>{p.last_name} {p.first_name}</option>)}</select><button onClick={addExisting}>Ajouter</button></div>
   <details><summary>+ Nouveau joueur</summary><div className="grid"><input placeholder="Prénom" value={newPlayer.first_name} onChange={e=>setNewPlayer({...newPlayer,first_name:e.target.value})}/><input placeholder="Nom" value={newPlayer.last_name} onChange={e=>setNewPlayer({...newPlayer,last_name:e.target.value})}/><input type="date" value={newPlayer.birthdate} onChange={e=>setNewPlayer({...newPlayer,birthdate:e.target.value})}/><select value={newPlayer.sex} onChange={e=>setNewPlayer({...newPlayer,sex:e.target.value})}><option value="">Sexe</option><option value="M">Garçon</option><option value="F">Fille</option></select><input placeholder="Email" value={newPlayer.email} onChange={e=>setNewPlayer({...newPlayer,email:e.target.value})}/><input placeholder="Téléphone" value={newPlayer.phone} onChange={e=>setNewPlayer({...newPlayer,phone:e.target.value})}/><button onClick={createPlayer}>Créer</button></div></details>
   <div className="list">{rows.map(({e,p})=><button className={`player ${selected===p.id?"on":""}`} key={e.id} onClick={()=>setSelected(p.id)}><span className="avatar">{p.photo_url?<img src={p.photo_url} alt=""/>:p.first_name.slice(0,1)}</span><span><b>{p.first_name} {p.last_name}</b><small>{p.sex==="F"?"Fille":p.sex==="M"?"Garçon":"—"} · {e.club_name||"Club —"} · présence {rate(p.id)==null?"—":`${rate(p.id)}%`}</small></span></button>)}</div>
  </section>

  <section className="card"><h3>Feuilles de présence</h3><div className="line"><input type="date" value={attendance.session_date} onChange={e=>setAttendance({...attendance,session_date:e.target.value})}/><input value={attendance.title} onChange={e=>setAttendance({...attendance,title:e.target.value})}/><input placeholder="Lieu" value={attendance.location} onChange={e=>setAttendance({...attendance,location:e.target.value})}/><button onClick={createAttendance}>+ Feuille</button></div>
  {sessions.filter(s=>s.season_id===seasonId).map(s=><details className="sheet" key={s.id}><summary>{fmt(s.session_date)} · {s.title}</summary>{seasonEntries.map(e=>{const p=mapP.get(e.player_id),r=records.find(x=>x.session_id===s.id&&x.player_id===e.player_id),st=r?.status||"absent";return p?<div className="presence" key={p.id}><b>{p.first_name} {p.last_name}</b>{(["present","absent","excused"] as const).map(x=><label key={x}><input type="radio" name={`${s.id}-${p.id}`} checked={st===x} onChange={()=>presence(s.id,p.id,x)}/>{x==="present"?"Présent":x==="absent"?"Absent":"Excusé"}</label>)}</div>:null})}</details>)}</section>

  {player&&entry&&<section className="card detail"><div className="profileHead"><label className="photo">{player.photo_url?<img src={player.photo_url} alt=""/>:<span>PHOTO</span>}<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&uploadAsset(e.target.files[0],"player")}/></label><div><p>FICHE JOUEUR</p><h2>{player.first_name} {player.last_name}</h2><span>{entry.category||"—"} · {entry.club_name||"Club non renseigné"} · présence {rate(player.id)==null?"—":`${rate(player.id)}%`}</span></div><div className="buttons"><button onClick={parentLink}>👪 Lien parents</button><button onClick={downloadPdf} disabled={!!busy}>📘 PDF</button><button onClick={sendClub} disabled={!!busy}>✉ Club</button></div></div>
   <div className="grid"><input placeholder="Club actuel" value={entry.club_name||""} onChange={e=>patchEntry(entry.id,{club_name:e.target.value})}/><input placeholder="Email club" value={entry.club_email||""} onChange={e=>patchEntry(entry.id,{club_email:e.target.value})}/><input placeholder="Catégorie" value={entry.category||""} onChange={e=>patchEntry(entry.id,{category:e.target.value})}/><input placeholder="Poste" value={entry.position_label||""} onChange={e=>patchEntry(entry.id,{position_label:e.target.value})}/><label className="asset">Logo club<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&uploadAsset(e.target.files[0],"club")}/></label><label className="asset">Logo institution<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&uploadAsset(e.target.files[0],"structure")}/></label></div>

   <h3>Évolution physique</h3><div className="grid"><input type="date" value={measure.measured_at} onChange={e=>setMeasure({...measure,measured_at:e.target.value})}/><input placeholder="Taille cm" value={measure.height_cm} onChange={e=>setMeasure({...measure,height_cm:e.target.value})}/><input placeholder="Poids kg" value={measure.weight_kg} onChange={e=>setMeasure({...measure,weight_kg:e.target.value})}/><input placeholder="Envergure cm" value={measure.wingspan_cm} onChange={e=>setMeasure({...measure,wingspan_cm:e.target.value})}/><input placeholder="Pointure" value={measure.shoe_size} onChange={e=>setMeasure({...measure,shoe_size:e.target.value})}/><button onClick={addMeasure}>Enregistrer mesure</button></div>
   <div className="history">{playerMeasures.map(m=><span key={m.id}><b>{fmt(m.measured_at)}</b> {m.height_cm?`${m.height_cm}cm`:""} {m.weight_kg?`· ${m.weight_kg}kg`:""} {m.wingspan_cm?`· env. ${m.wingspan_cm}cm`:""}</span>)}</div>

   <h3>Commentaires basket</h3><div className="commentGrid"><textarea placeholder="Profil" value={comment.profile_text} onChange={e=>setComment({...comment,profile_text:e.target.value})}/><textarea placeholder="Points forts" value={comment.strengths_text} onChange={e=>setComment({...comment,strengths_text:e.target.value})}/><textarea placeholder="Axes de travail" value={comment.improvement_text} onChange={e=>setComment({...comment,improvement_text:e.target.value})}/><textarea placeholder="Projection" value={comment.projection_text} onChange={e=>setComment({...comment,projection_text:e.target.value})}/><textarea className="wide" placeholder="Commentaire libre" value={comment.free_comment} onChange={e=>setComment({...comment,free_comment:e.target.value})}/></div><label className="share"><input type="checkbox" checked={comment.share_with_club} onChange={e=>setComment({...comment,share_with_club:e.target.checked})}/> Visible dans le cahier envoyé au club</label><button onClick={addComment}>Ajouter l'observation</button>
   <div className="comments">{playerComments.map(c=><article key={c.id}><b>{fmt(c.comment_date)} · {c.author_name||"Entraîneur"} {c.share_with_club?"· Club":"· Interne"}</b><p>{[c.profile_text,c.strengths_text,c.improvement_text,c.projection_text,c.free_comment].filter(Boolean).join("\n\n")}</p></article>)}</div>
  </section>}</>}
  <style jsx>{css}</style>
 </div>
}
const css=`.nb{display:grid;gap:10px}.card{background:#fff;border:1px solid #eadfd8;border-radius:14px;padding:13px}.head,.title,.profileHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.card p{margin:0;color:#d4a24c;font-size:.68rem;font-weight:1000;letter-spacing:.12em}.card h2{margin:3px 0;color:#251a1b}.card h3{color:#6b1a2c;margin:10px 0}.card span,.card small{color:#7f7169}.actions,.buttons,.line{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:8px 0}.commentGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.wide{grid-column:1/-1}input,select,textarea{border:1px solid #ddd1ca;border-radius:8px;padding:8px;min-width:0;font:inherit}textarea{min-height:80px}button{border:0;border-radius:8px;padding:8px 10px;background:#6b1a2c;color:#fff;font-weight:900;cursor:pointer}button:disabled{opacity:.5}.list{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:10px}.player{background:#fff;color:#241b1d;border:1px solid #e8ddd7;text-align:left;display:flex;gap:9px;align-items:center}.player.on{border-color:#6b1a2c;background:#fff6f8}.avatar{width:35px;height:35px;border-radius:50%;background:#f1ebe8;display:grid;place-items:center;font-weight:900;color:#6b1a2c;overflow:hidden}.avatar img,.photo img{width:100%;height:100%;object-fit:cover}.player b,.player small{display:block}.sheet{border:1px solid #e8ddd7;border-radius:9px;padding:8px;margin-top:6px}.presence{display:grid;grid-template-columns:2fr repeat(3,1fr);gap:8px;padding:6px;border-top:1px solid #eee}.photo{width:80px;height:100px;background:#f2ece9;border-radius:10px;display:grid;place-items:center;overflow:hidden;cursor:pointer}.profileHead>div:nth-child(2){flex:1}.asset{border:1px dashed #d8c9c1;border-radius:8px;padding:8px;font-size:.75rem;font-weight:800;color:#6b1a2c}.asset input{display:block;border:0;padding:5px 0}.history{display:flex;flex-wrap:wrap;gap:5px}.history span{border:1px solid #e5dad4;border-radius:999px;padding:5px 8px;font-size:.72rem}.share{display:flex;gap:6px;align-items:center;font-size:.8rem;margin:8px 0}.comments{display:grid;gap:6px;margin-top:10px}.comments article{border-left:4px solid #6b1a2c;background:#fbf8f6;padding:9px}.comments p{color:#342b2d;white-space:pre-wrap;font-size:.8rem;letter-spacing:0;margin-top:5px}.toast{position:fixed;top:15px;left:50%;transform:translateX(-50%);background:#231b1d;color:#fff;padding:9px 14px;border-radius:999px;z-index:100}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}.list{grid-template-columns:1fr}.profileHead{display:grid}.commentGrid{grid-template-columns:1fr}.wide{grid-column:auto}}@media(max-width:560px){.grid{grid-template-columns:1fr}.presence{grid-template-columns:1fr 1fr}}`;
