"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Grid={id:string;name:string;description:string|null;input_mode:string;fixed_value:number;court_schema_url:string|null};
type Row={id:string;grid_id:string;name:string;sort_order:number};
export default function InstitutionalPlayerShootingGrids({structureId,player}:{structureId:string;player:{id:string;first_name?:string;last_name?:string}}){
 const sb=useMemo(()=>createClient(),[]); const[grids,setGrids]=useState<Grid[]>([]);const[gridId,setGridId]=useState("");const[assigned,setAssigned]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 async function load(){const [{data:g},{data:s}]=await Promise.all([sb.from("institutional_shooting_grids").select("id,name,description,input_mode,fixed_value,court_schema_url").eq("structure_id",structureId).order("created_at",{ascending:false}),sb.from("institutional_shooting_grid_session_players").select("session_id,institutional_shooting_grid_sessions!inner(id,grid_id,session_date,institutional_shooting_grids!inner(id,name,structure_id))").eq("player_id",player.id)]);const gg=(g||[]) as Grid[];setGrids(gg);if(!gridId&&gg[0])setGridId(gg[0].id);setAssigned((s||[]).filter((x:any)=>x.institutional_shooting_grid_sessions?.institutional_shooting_grids?.structure_id===structureId));}
 useEffect(()=>{void load()},[structureId,player.id]); // eslint-disable-line
 async function assign(){if(!gridId||busy)return;setBusy(true);setMsg("");try{const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error("Session expirée");const {data:rows,error:re}=await sb.from("institutional_shooting_grid_rows").select("id,grid_id,name,sort_order").eq("grid_id",gridId).order("sort_order");if(re)throw re;const grid=grids.find(g=>g.id===gridId);if(!grid)throw new Error("Grille introuvable");const {data:session,error:se}=await sb.from("institutional_shooting_grid_sessions").insert({grid_id:gridId,owner_id:user.id,session_date:new Date().toISOString().slice(0,10)}).select("id").single();if(se)throw se;const {error:pe}=await sb.from("institutional_shooting_grid_session_players").insert({session_id:session.id,player_id:player.id});if(pe)throw pe;const resultRows=((rows||[]) as Row[]).map(r=>({session_id:session.id,row_id:r.id,player_id:player.id,made:grid.input_mode==="fixed_makes"?grid.fixed_value:0,attempted:grid.input_mode==="fixed_attempts"?grid.fixed_value:grid.fixed_value}));if(resultRows.length){const {error}=await sb.from("institutional_shooting_grid_player_results").insert(resultRows);if(error)throw error}setMsg("Grille attribuée au joueur ✓");await load()}catch(e:any){setMsg(e?.message||"Attribution impossible")}finally{setBusy(false)}}
 return <section style={{display:"grid",gap:14}}><div><div style={{fontSize:10,fontWeight:900,letterSpacing:1.1,color:"#1765e5"}}>GRILLES DE TIR</div><h3 style={{margin:"4px 0",color:"#1d2c49"}}>Importer une grille de Mes documents</h3><p style={{margin:0,color:"#8492a8",fontSize:12}}>Choisis un modèle déjà créé dans Mon compte → Mes documents → Mes grilles de tir, puis attribue-le à {player.first_name||"ce joueur"}.</p></div>{grids.length?<div style={{display:"grid",gridTemplateColumns:"minmax(220px,1fr) auto",gap:8,alignItems:"end"}}><label style={{display:"grid",gap:5,fontSize:11,fontWeight:800,color:"#4b5d78"}}>Grille<select value={gridId} onChange={e=>setGridId(e.target.value)} style={{padding:"10px",border:"1px solid #dfe5ed",borderRadius:8,background:"#fff"}}>{grids.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><button onClick={assign} disabled={busy} style={{padding:"10px 13px",border:0,borderRadius:8,background:"#1765e5",color:"#fff",fontWeight:800,cursor:"pointer"}}>{busy?"Attribution…":"Importer et attribuer"}</button></div>:<div style={{padding:16,border:"1px dashed #d7dfe9",borderRadius:9,color:"#8492a8"}}>Aucune grille disponible. Crée d’abord un modèle dans Mes documents.</div>}{msg&&<div style={{fontSize:12,fontWeight:750,color:msg.includes("✓")?"#177a43":"#b4233b"}}>{msg}</div>}<div style={{display:"grid",gap:7}}><b style={{color:"#263c65",fontSize:12}}>Grilles attribuées</b>{assigned.map((x:any)=>{const s=x.institutional_shooting_grid_sessions;return <div key={x.session_id} style={{display:"flex",justifyContent:"space-between",gap:10,padding:10,border:"1px solid #e5eaf1",borderRadius:9,background:"#fbfcfe"}}><strong style={{color:"#23406f"}}>{s?.institutional_shooting_grids?.name||"Grille"}</strong><span style={{color:"#8492a8",fontSize:11}}>{s?.session_date?new Date(s.session_date+"T12:00:00").toLocaleDateString("fr-FR"):""}</span></div>})}{!assigned.length&&<span style={{color:"#8492a8",fontSize:12}}>Aucune grille attribuée à ce joueur.</span>}</div></section>
}
