"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Player={id:string;first_name:string;last_name:string;birthdate:string|null;club_name:string|null;category:string|null;photo_url?:string|null;structure_id?:string};
type Event={id:string;title:string;event_type:string;event_date:string;start_time:string|null;location:string|null};
type Participant={id:string;event_id:string;player_id:string;status:string};
type Transfer={id:string;target_email:string;target_label:string|null;access_level:string;status:string;created_at:string};
type Referral={id:string;first_name:string;last_name:string;birthdate:string|null;club_name:string|null;category:string|null;reporter_name:string|null;reporter_email:string;reason:string|null;status:string;created_at:string};
type Share={id:string;player_id:string;source_structure_id:string;access_level:string;institutional_players?:Player|null};
const EVENT_LABELS:Record<string,string>={detection:"Détection",camp:"Stage",selection:"Sélection",tournament:"Tournoi intercomités",pole_test:"Tests Pôle",other:"Autre"};
const STATUS_LABELS:Record<string,string>={invited:"Invité",confirmed:"Confirmé",present:"Présent",absent:"Absent",preselected:"Présélectionné",selected:"Sélectionné",waiting:"Liste d'attente",not_selected:"Non retenu"};

export default function InstitutionalPlayerWorkflow({structureId}:{structureId:string}){
 const sb=useMemo(()=>createClient(),[]);const[players,setPlayers]=useState<Player[]>([]),[events,setEvents]=useState<Event[]>([]),[parts,setParts]=useState<Participant[]>([]),[transfers,setTransfers]=useState<Transfer[]>([]),[referrals,setReferrals]=useState<Referral[]>([]),[shares,setShares]=useState<Share[]>([]),[referralToken,setReferralToken]=useState(""),[selected,setSelected]=useState<string[]>([]),[activeEvent,setActiveEvent]=useState("");
 const[eform,setEform]=useState({title:"Journée de détection",event_type:"detection",event_date:new Date().toISOString().slice(0,10),start_time:"09:00",location:""});
 const[tform,setTform]=useState({target_email:"",target_label:"",access_level:"editor",message:""});const[busy,setBusy]=useState(false);
 async function load(){const[p,e,pa,t,r,sh,st]=await Promise.all([sb.from("institutional_players").select("id,structure_id,first_name,last_name,birthdate,club_name,category,photo_url").eq("structure_id",structureId).eq("archived",false).order("last_name"),sb.from("institutional_detection_events").select("*").eq("structure_id",structureId).eq("archived",false).order("event_date",{ascending:false}),sb.from("institutional_detection_participants").select("*"),sb.from("institutional_player_transfers").select("id,target_email,target_label,access_level,status,created_at").eq("source_structure_id",structureId).order("created_at",{ascending:false}),sb.from("institutional_player_referrals").select("*").eq("structure_id",structureId).order("created_at",{ascending:false}),sb.from("institutional_player_shares").select("id,player_id,source_structure_id,access_level,institutional_players(id,structure_id,first_name,last_name,birthdate,club_name,category,photo_url)").eq("target_structure_id",structureId).is("revoked_at",null).order("granted_at",{ascending:false}),sb.from("institutional_structures").select("player_referral_token").eq("id",structureId).maybeSingle()]);if(p.error)return alert(p.error.message);setPlayers((p.data||[]) as Player[]);setEvents((e.data||[]) as Event[]);const eventIds=new Set((e.data||[]).map((x:any)=>x.id));setParts(((pa.data||[]) as Participant[]).filter(x=>eventIds.has(x.event_id)));setTransfers((t.data||[]) as Transfer[]);setReferrals((r.data||[]) as Referral[]);setShares(((sh.data||[]) as unknown) as Share[]);setReferralToken(String(st.data?.player_referral_token||""));if(!activeEvent&&e.data?.[0]?.id)setActiveEvent(e.data[0].id)}
 useEffect(()=>{void load()},[structureId]);// eslint-disable-line
 const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 async function createEvent(){const{data:{user}}=await sb.auth.getUser();if(!user||!eform.title.trim())return;const q=await sb.from("institutional_detection_events").insert({structure_id:structureId,...eform,location:eform.location||null,created_by:user.id}).select("id").single();if(q.error)return alert(q.error.message);setActiveEvent(q.data.id);await load()}
 async function addToEvent(){if(!activeEvent||!selected.length)return alert("Sélectionne une journée et au moins un joueur.");const rows=selected.map(player_id=>({event_id:activeEvent,player_id,status:"invited"}));const q=await sb.from("institutional_detection_participants").upsert(rows,{onConflict:"event_id,player_id"});if(q.error)return alert(q.error.message);await load()}
 async function patchStatus(id:string,status:string){const{data:{user}}=await sb.auth.getUser();const q=await sb.from("institutional_detection_participants").update({status,updated_by:user?.id||null,updated_at:new Date().toISOString()}).eq("id",id);if(q.error)return alert(q.error.message);setParts(v=>v.map(x=>x.id===id?{...x,status}:x))}
 async function sendTransfer(){if(!selected.length)return alert("Sélectionne au moins un joueur.");if(!tform.target_email.trim())return alert("Renseigne l'email de la structure destinataire.");setBusy(true);const r=await fetch("/api/institutionnel/player-transfers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({structureId,playerIds:selected,...tform})});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return alert(j.error||"Envoi impossible");setTform({target_email:"",target_label:"",access_level:"editor",message:""});await load();alert("Invitation envoyée.")}
 async function convertReferral(ref:Referral){const{data:{user}}=await sb.auth.getUser();if(!user)return;const q=await sb.from("institutional_players").insert({structure_id:structureId,first_name:ref.first_name,last_name:ref.last_name,birthdate:ref.birthdate,club_name:ref.club_name,category:ref.category,status:"followed",created_by:user.id}).select("id").single();if(q.error)return alert(q.error.message);await sb.from("institutional_player_referrals").update({status:"converted",converted_player_id:q.data.id,updated_at:new Date().toISOString()}).eq("id",ref.id);await load()}
 async function dismissReferral(id:string){await sb.from("institutional_player_referrals").update({status:"dismissed",updated_at:new Date().toISOString()}).eq("id",id);await load()}
 function copyReferralLink(){const url=`${window.location.origin}/signalement-joueur/${referralToken}`;navigator.clipboard?.writeText(url).then(()=>alert("Lien copié")).catch(()=>prompt("Copiez ce lien",url))}
 const currentParts=parts.filter(x=>x.event_id===activeEvent);const pMap=new Map<string,Player>(players.map(p=>[p.id,p]));const newRefs=referrals.filter(r=>r.status==="new"||r.status==="reviewing");
 return <div className="wf">
  <section className="card"><div className="title"><div><p>SIGNALEMENTS CLUBS</p><h3>Repérer dès U10 / U11</h3></div>{referralToken&&<button className="ghost" onClick={copyReferralLink}>Copier le lien de signalement</button>}</div><p className="hint">Le club remplit un formulaire simple. Le comité décide ensuite de créer ou non une vraie fiche joueur.</p><div className="refList">{newRefs.map(r=><article key={r.id}><div><b>{r.first_name} {r.last_name}</b><span>{r.club_name||"Club —"} · {r.category||"Catégorie —"} · signalé par {r.reporter_name||r.reporter_email}</span>{r.reason&&<small>{r.reason}</small>}</div><div className="actions"><button onClick={()=>convertReferral(r)}>Créer la fiche</button><button className="ghost" onClick={()=>dismissReferral(r.id)}>Ignorer</button></div></article>)}{!newRefs.length&&<span className="hint">Aucun nouveau signalement.</span>}</div></section>
  <section className="card"><div className="title"><div><p>BASE JOUEURS</p><h3>Sélection multiple</h3></div><span>{selected.length} sélectionné(s)</span></div><div className="players">{players.map(p=><label key={p.id} className={selected.includes(p.id)?"player on":"player"}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/><span className="avatar">{p.photo_url?<img src={p.photo_url} alt=""/>:(p.first_name[0]||"?")}</span><span><b>{p.first_name} {p.last_name}</b><small>{p.club_name||"Club —"} · {p.category||"Catégorie —"}</small></span></label>)}</div>{shares.length>0&&<><h4>Fiches reçues d'autres structures</h4><div className="received">{shares.map(sh=>{const p=sh.institutional_players;return p?<div key={sh.id}><b>{p.first_name} {p.last_name}</b><span>{p.club_name||"Club —"} · droit {sh.access_level}</span></div>:null})}</div></>}</section>
  <section className="card"><div className="title"><div><p>DÉTECTIONS & SÉLECTIONS</p><h3>Créer une journée puis constituer le groupe</h3></div></div><div className="grid"><input value={eform.title} onChange={e=>setEform({...eform,title:e.target.value})}/><select value={eform.event_type} onChange={e=>setEform({...eform,event_type:e.target.value})}>{Object.entries(EVENT_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input type="date" value={eform.event_date} onChange={e=>setEform({...eform,event_date:e.target.value})}/><input type="time" value={eform.start_time} onChange={e=>setEform({...eform,start_time:e.target.value})}/><input placeholder="Lieu" value={eform.location} onChange={e=>setEform({...eform,location:e.target.value})}/><button onClick={createEvent}>+ Créer</button></div><div className="line"><select value={activeEvent} onChange={e=>setActiveEvent(e.target.value)}><option value="">Choisir une journée</option>{events.map(e=><option key={e.id} value={e.id}>{e.event_date} · {e.title}</option>)}</select><button onClick={addToEvent}>Ajouter les joueurs sélectionnés</button></div>{activeEvent&&<div className="partList">{currentParts.map(x=>{const p=pMap.get(x.player_id);return p?<div className="part" key={x.id}><b>{p.first_name} {p.last_name}</b><select value={x.status} onChange={e=>patchStatus(x.id,e.target.value)}>{Object.entries(STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>:null})}</div>}</section>
  <section className="card"><div className="title"><div><p>PASSATION</p><h3>Partager les fiches avec une autre institution</h3></div></div><p className="hint">Le destinataire reçoit un lien sécurisé. La fiche d'origine reste intacte et son historique reste traçable.</p><div className="grid"><input type="email" placeholder="Email institution / club / fédé" value={tform.target_email} onChange={e=>setTform({...tform,target_email:e.target.value})}/><input placeholder="Nom de la structure (facultatif)" value={tform.target_label} onChange={e=>setTform({...tform,target_label:e.target.value})}/><select value={tform.access_level} onChange={e=>setTform({...tform,access_level:e.target.value})}><option value="viewer">Lecture + PDF</option><option value="editor">Enrichir le suivi</option><option value="manager">Contrôle + retransmission</option></select><textarea placeholder="Message" value={tform.message} onChange={e=>setTform({...tform,message:e.target.value})}/><button disabled={busy} onClick={sendTransfer}>{busy?"Envoi…":`Partager ${selected.length||""} fiche(s)`}</button></div><div className="history">{transfers.slice(0,10).map(t=><div key={t.id}><b>{t.target_label||t.target_email}</b><span>{t.status} · {t.access_level}</span></div>)}</div></section>
  <style jsx>{`.wf{display:grid;gap:12px}.card{background:#fff;border:1px solid #eadfd8;border-radius:14px;padding:13px}.title{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.title p{margin:0;color:#d4a24c;font-size:.68rem;font-weight:1000;letter-spacing:.12em}.title h3{margin:3px 0;color:#6b1a2c}.title span,.hint{color:#7f7169}.players{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin-top:10px}.player{display:flex;align-items:center;gap:8px;border:1px solid #e8ddd7;border-radius:10px;padding:7px;cursor:pointer}.player.on{border-color:#6b1a2c;background:#fff6f8}.player input{width:16px;height:16px}.avatar{width:32px;height:32px;border-radius:50%;background:#f1ebe8;display:grid;place-items:center;overflow:hidden;color:#6b1a2c;font-weight:900}.avatar img{width:100%;height:100%;object-fit:cover}.player b,.player small{display:block}.player small,.refList span,.refList small,.received span{color:#7f7169}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:10px}.grid textarea{grid-column:1/-1;min-height:70px}.grid input,.grid select,.grid textarea,.line select,.part select{border:1px solid #ddd1ca;border-radius:8px;padding:8px;font:inherit;min-width:0}.grid button,.line button,.actions button,.title button{border:0;border-radius:8px;padding:8px 10px;background:#6b1a2c;color:#fff;font-weight:900;cursor:pointer}.ghost{background:#fff!important;color:#6b1a2c!important;border:1px solid #d8c8c1!important}.line{display:flex;gap:7px;margin-top:10px;flex-wrap:wrap}.line select{flex:1}.partList,.history,.refList,.received{display:grid;gap:6px;margin-top:10px}.part,.history>div,.received>div{display:flex;justify-content:space-between;align-items:center;gap:8px;border-top:1px solid #eee;padding-top:6px}.history span{color:#7f7169;font-size:.8rem}.refList article{display:flex;justify-content:space-between;gap:12px;border:1px solid #eee1da;border-radius:10px;padding:9px}.refList b,.refList span,.refList small,.received b,.received span{display:block}.actions{display:flex;gap:6px;align-items:center}h4{margin:14px 0 4px;color:#6b1a2c}@media(max-width:850px){.players,.grid{grid-template-columns:1fr}.grid textarea{grid-column:auto}.refList article{display:grid}}`}</style>
 </div>
}
