"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type F={id:string;title:string;purpose:string|null;is_active:boolean};
type Field={id:string;form_id:string;section_name:string|null;label:string;field_key:string;field_type:string;required:boolean;sort_order:number};
export default function InstitutionalFormBuilder({structureId}:{structureId:string}){
 const s=useMemo(()=>createClient(),[]),[forms,setForms]=useState<F[]>([]),[fields,setFields]=useState<Field[]>([]),[fid,setFid]=useState(""),[title,setTitle]=useState("Fiche détection U13");
 async function load(pref?:string){const{data}=await s.from("institutional_forms").select("*").eq("structure_id",structureId).eq("archived",false).order("updated_at",{ascending:false});const list=(data||[]) as F[];setForms(list);const id=pref||fid||list[0]?.id||"";setFid(id);if(id){const q=await s.from("institutional_form_fields").select("*").eq("form_id",id).order("sort_order");setFields((q.data||[]) as Field[])}else setFields([])}
 useEffect(()=>{void load()},[structureId]);// eslint-disable-line
 async function create(){const{data:{user}}=await s.auth.getUser();if(!user)return;const q=await s.from("institutional_forms").insert({structure_id:structureId,title,purpose:"player_followup",created_by:user.id}).select("id").single();if(q.error)return alert(q.error.message);await load(q.data.id)}
 async function addField(){if(!fid)return;const label=prompt("Nom du champ ?","Nouvelle information");if(!label)return;const type=prompt("Type : text / number / date / select / rating / checkbox","text")||"text";const q=await s.from("institutional_form_fields").insert({form_id:fid,section_name:"Général",label,field_key:`field_${Date.now()}`,field_type:type,required:false,sort_order:fields.length}).select("*").single();if(q.error)return alert(q.error.message);setFields(v=>[...v,q.data as Field])}
 async function patch(id:string,p:Partial<Field>){await s.from("institutional_form_fields").update(p).eq("id",id);setFields(v=>v.map(x=>x.id===id?{...x,...p}:x))}
 async function remove(id:string){await s.from("institutional_form_fields").delete().eq("id",id);setFields(v=>v.filter(x=>x.id!==id))}
 return <div className="builder"><div className="top"><input value={title} onChange={e=>setTitle(e.target.value)}/><button onClick={create}>+ Nouveau formulaire</button><select value={fid} onChange={async e=>{setFid(e.target.value);await load(e.target.value)}}><option value="">Choisir</option>{forms.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select><button onClick={addField} disabled={!fid}>+ Champ</button></div>{fid&&<div className="fields">{fields.map(f=><div key={f.id}><input value={f.section_name||""} onChange={e=>patch(f.id,{section_name:e.target.value})}/><input value={f.label} onChange={e=>patch(f.id,{label:e.target.value})}/><select value={f.field_type} onChange={e=>patch(f.id,{field_type:e.target.value})}><option>text</option><option>number</option><option>date</option><option>select</option><option>rating</option><option>checkbox</option></select><label><input type="checkbox" checked={f.required} onChange={e=>patch(f.id,{required:e.target.checked})}/> Obligatoire</label><button onClick={()=>remove(f.id)}>×</button></div>)}</div>}<p>Les responsables peuvent créer, renommer et supprimer leurs propres champs sans modifier le code MyBasket.</p><style jsx>{`.builder{display:grid;gap:8px}.top{display:flex;gap:6px;flex-wrap:wrap}.top input,.top select,.fields input,.fields select{border:1px solid #ddd1ca;border-radius:8px;padding:8px}.top button,.fields button{background:#6b1a2c;color:white;border:0;border-radius:8px;padding:8px 10px;font-weight:900}.fields{display:grid;gap:5px}.fields>div{display:grid;grid-template-columns:150px 1fr 120px 120px 34px;gap:5px;align-items:center;border:1px solid #eee4df;border-radius:8px;padding:6px}.fields label{font-size:.72rem}p{color:#80726a;font-size:.78rem}@media(max-width:760px){.fields>div{grid-template-columns:1fr 1fr}}`}</style></div>
}
