"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {PoleExitSection} from "@/lib/institutionnel/pole-exit-pdf";
type P={id:string;first_name:string;last_name:string;birthdate:string|null;club_name:string|null;category:string|null};type Season={id:string;season_label:string};
const choices:{id:PoleExitSection;label:string;help:string}[]=[{id:"identity",label:"Identité",help:"État civil, club, catégorie, poste"},{id:"pathway",label:"Parcours",help:"Saisons et clubs / structures"},{id:"measurements",label:"Mesures",help:"Taille, poids, envergure"},{id:"attendance",label:"Présences",help:"Convocations et assiduité"},{id:"parent",label:"Contexte",help:"Informations familiales et scolaires"},{id:"basket",label:"Évaluations basket",help:"Profil, points forts, axes, projection"},{id:"performance",label:"Performance",help:"Stats, charge, clips et bilans"}];
export default function PoleExitDossiers({structureId}:{structureId:string}){const sb=useMemo(()=>createClient(),[]),[seasons,setSeasons]=useState<Season[]>([]),[seasonId,setSeasonId]=useState(""),[players,setPlayers]=useState<P[]>([]),[selected,setSelected]=useState<string[]>([]),[sections,setSections]=useState<PoleExitSection[]>(choices.map(x=>x.id)),[emails,setEmails]=useState(""),[subject,setSubject]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(""),[toast,setToast]=useState("");
 async function load(){const qs=await sb.from("institutional_player_tracking_seasons").select("id,season_label").eq("structure_id",structureId).order("start_date",{ascending:false});const ss=(qs.data||[]) as Season[];setSeasons(ss);const sid=seasonId||ss[0]?.id||"";if(!seasonId)setSeasonId(sid);if(!sid)return;const qe=await sb.from("institutional_player_season_entries").select("player_id").eq("structure_id",structureId).eq("season_id",sid).neq("status","removed");const ids=[...new Set((qe.data||[]).map((x:any)=>String(x.player_id)))];if(!ids.length){setPlayers([]);return}const qp=await sb.from("institutional_players").select("id,first_name,last_name,birthdate,club_name,category").in("id",ids).eq("archived",false).order("last_name");setPlayers((qp.data||[]) as P[]);setSelected(v=>v.filter(id=>ids.includes(id)))}
 useEffect(()=>{void load()},[structureId,seasonId]); // eslint-disable-line
 const all=players.length>0&&selected.length===players.length;const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);const flash=(t:string)=>{setToast(t);window.setTimeout(()=>setToast(""),2300)};
 async function downloadOne(id:string){setBusy(`pdf-${id}`);const r=await fetch("/api/institutionnel/pole-exit/pdf",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({structureId,playerId:id,seasonId,sections})});if(!r.ok){const j=await r.json().catch(()=>({}));setBusy("");return alert(j.error||"PDF impossible")}const p=players.find(x=>x.id===id),blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`Dossier_sortie_${p?.first_name||"joueur"}_${p?.last_name||""}.pdf`;a.click();URL.revokeObjectURL(url);setBusy("")}
 async function send(){if(!selected.length)return alert("Sélectionne au moins un joueur.");const to=emails.split(/[;,\s]+/).filter(x=>x.includes("@"));if(!to.length)return alert("Renseigne au moins une adresse email.");setBusy("send");const r=await fetch("/api/institutionnel/pole-exit/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({structureId,seasonId,playerIds:selected,to,sections,subject,message})});const j=await r.json().catch(()=>({}));setBusy("");if(!r.ok)return alert(j.error||"Envoi impossible");flash(`${j.count} dossier(s) envoyé(s)`)}
 return <section className="exit">{toast&&<div className="toast">{toast}</div>}<div className="head"><div><p>SORTIE DU PÔLE</p><h2>Dossiers joueurs</h2><span>Sélectionne les joueurs et uniquement les parties du dossier que tu souhaites transmettre.</span></div><select value={seasonId} onChange={e=>setSeasonId(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.season_label}</option>)}</select></div>
 <div className="sectionBox"><b>Contenu des PDF</b><div className="sectionGrid">{choices.map(c=><label key={c.id} className={sections.includes(c.id)?"on":""}><input type="checkbox" checked={sections.includes(c.id)} onChange={e=>setSections(v=>e.target.checked?[...v,c.id]:v.filter(x=>x!==c.id))}/><span><strong>{c.label}</strong><small>{c.help}</small></span></label>)}</div></div>
 <div className="tableWrap"><table><thead><tr><th><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:players.map(p=>p.id))}/></th><th>Prénom</th><th>Nom</th><th>Date de naissance</th><th>Club</th><th>Catégorie</th><th>PDF</th></tr></thead><tbody>{players.map(p=><tr key={p.id}><td><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/></td><td>{p.first_name}</td><td><b>{p.last_name}</b></td><td>{p.birthdate||"—"}</td><td>{p.club_name||"—"}</td><td>{p.category||"—"}</td><td><button className="ghost" disabled={busy===`pdf-${p.id}`} onClick={()=>downloadOne(p.id)}>{busy===`pdf-${p.id}`?"Génération…":"Télécharger"}</button></td></tr>)}</tbody></table>{!players.length&&<div className="empty">Aucun joueur dans cette saison.</div>}</div>
 <div className="sendBox"><div className="sendHead"><div><b>{selected.length} joueur(s) sélectionné(s)</b><span>Chaque joueur génère son propre PDF. Jusqu'à 15 dossiers par email.</span></div></div><label>Destinataires<input value={emails} onChange={e=>setEmails(e.target.value)} placeholder="club@exemple.fr, recrutement@exemple.fr"/></label><label>Objet<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Dossiers joueurs · Pôle"/></label><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Bonjour, vous trouverez ci-joint les dossiers…"/></label><button disabled={!selected.length||!sections.length||busy==="send"} onClick={send}>{busy==="send"?"Envoi…":`Envoyer ${selected.length||""} dossier(s) par email`}</button></div>
 <style jsx>{`.exit{display:grid;gap:12px}.head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.head p{margin:0;color:var(--inst-secondary);font-size:.68rem;font-weight:1000;letter-spacing:.12em}.head h2{margin:4px 0;color:var(--inst-primary)}.head span,.sendHead span{color:#81746f;font-size:.78rem}.head select{border:1px solid #e2d7d1;border-radius:9px;padding:9px;background:#fff}.sectionBox,.sendBox{border:1px solid #eadfd8;background:#fff;border-radius:14px;padding:13px;display:grid;gap:10px}.sectionGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.sectionGrid label{display:flex;gap:8px;border:1px solid #eadfd8;border-radius:10px;padding:9px;background:#faf7f5}.sectionGrid label.on{border-color:var(--inst-primary);box-shadow:0 0 0 1px var(--inst-primary) inset}.sectionGrid span{display:grid}.sectionGrid small{color:#81746f;font-size:.65rem}.tableWrap{border:1px solid #eadfd8;border-radius:14px;overflow:auto;background:#fff}.tableWrap table{width:100%;border-collapse:collapse;min-width:850px}.tableWrap th{background:#faf7f5;color:var(--inst-primary);font-size:.68rem;text-align:left;padding:9px;border-bottom:1px solid #eadfd8}.tableWrap td{padding:9px;border-bottom:1px solid #f0e8e4;font-size:.78rem}.ghost,.sendBox button{border:1px solid #d8c8c1;border-radius:8px;padding:8px 10px;background:#fff;color:var(--inst-primary);font-weight:900;cursor:pointer}.sendBox{max-width:900px}.sendBox label{display:grid;gap:4px;font-size:.72rem;font-weight:900;color:var(--inst-primary)}.sendBox input,.sendBox textarea{border:1px solid #ddd1ca;border-radius:9px;padding:9px;font:inherit}.sendBox textarea{min-height:86px}.sendBox button{background:var(--inst-primary);color:#fff;justify-self:start}.sendBox button:disabled,.ghost:disabled{opacity:.5}.empty{text-align:center;padding:24px;color:#81746f}.toast{position:fixed;top:18px;left:50%;transform:translateX(-50%);z-index:200;background:#231b1d;color:#fff;border-radius:999px;padding:10px 15px}@media(max-width:980px){.sectionGrid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.head{flex-direction:column}.sectionGrid{grid-template-columns:1fr}}`}</style></section>}
