"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import ShotChart,{SHOT_ZONES,type ShotLike} from "@/components/prise-stats-pro/ShotChart";
import type {Player} from "@/types/player";
type Source="grid"|"match"; type Grid={id:string;name:string}; type Row={id:string;grid_id:string;name:string}; type Session={id:string;grid_id:string}; type Result={session_id:string;row_id:string;player_id:string;made:number;attempted:number}; type Action={player_id:string|null;shot_type:string|null;shot_result:string|null;shot_zone_id:string|null};
const B="#6B1A2C",G="#D4A24C",BD="#E8DDD7",M="#7C6F68",SOFT="#FBF7F3"; const pct=(m:number,a:number)=>a?Math.round(m/a*1000)/10:0; const pname=(p?:Player)=>p?`${p.firstName||""} ${p.lastName||""}`.trim()||"Joueur":"Joueur"; const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim(); const made=(v:any)=>/made|marqu|reussi|réussi|in/i.test(String(v||""));
function zoneFor(label:string){const n=norm(label),type=n.includes("3pt")||n.includes("3 point")?"3PTS":"2PTS";const score=(z:(typeof SHOT_ZONES)[number])=>{const l=norm(z.label+" "+z.shortLabel);let s=0;for(const t of n.split(" "))if(t.length>2&&l.includes(t))s+=2;if(n.includes("corner")&&l.includes("corner"))s+=6;if(n.includes("axe")&&l.includes("axe"))s+=6;if(n.includes("droite")&&l.includes("droite"))s+=4;if(n.includes("gauche")&&l.includes("gauche"))s+=4;if((n.includes("45")||n.includes("aile"))&&l.includes("aile"))s+=5;return s};const b=SHOT_ZONES.filter(z=>z.type===type).map(z=>({z,s:score(z)})).sort((a,b)=>b.s-a.s)[0];return b?.s>0?b.z:null}
function gridShots(pid:string,gid:string,rows:Row[],sessions:Session[],results:Result[]):ShotLike[]{const sids=new Set(sessions.filter(s=>!gid||s.grid_id===gid).map(s=>s.id)),rm=new Map(rows.map(r=>[r.id,r])),out:ShotLike[]=[];for(const r of results){if(r.player_id!==pid||!sids.has(r.session_id))continue;const z=zoneFor(rm.get(r.row_id)?.name||"");if(!z)continue;const m=Math.min(+r.made||0,+r.attempted||0);for(let i=0;i<(+r.attempted||0);i++)out.push({shot_type:z.type,shot_result:i<m?"made":"missed",shot_zone_id:z.id})}return out}
const matchShots=(pid:string,actions:Action[]):ShotLike[]=>actions.filter(a=>String(a.player_id)===pid&&a.shot_zone_id).map(a=>({shot_type:(a.shot_type||"2PTS") as any,shot_result:made(a.shot_result)?"made":"missed",shot_zone_id:a.shot_zone_id||undefined})); const totals=(s:ShotLike[])=>{const m=s.filter(x=>made(x.shot_result)).length;return{m,a:s.length,p:pct(m,s.length)}};
export default function ShootingComparison({teamId,players,initialPlayerId}:{teamId:string;players:Player[];initialPlayerId?:string}){const sb=useMemo(()=>createClient(),[]),first=initialPlayerId||String(players[0]?.id||"");const [ap,setAp]=useState(first),[bp,setBp]=useState(initialPlayerId||String(players[1]?.id||players[0]?.id||"")),[as,setAs]=useState<Source>("grid"),[bs,setBs]=useState<Source>(initialPlayerId?"match":"grid"),[ag,setAg]=useState(""),[bg,setBg]=useState("");const [grids,setGrids]=useState<Grid[]>([]),[rows,setRows]=useState<Row[]>([]),[sessions,setSessions]=useState<Session[]>([]),[results,setResults]=useState<Result[]>([]),[actions,setActions]=useState<Action[]>([]),[loading,setLoading]=useState(true);
useEffect(()=>{let live=true;(async()=>{setLoading(true);const [gg,mm]=await Promise.all([sb.from("shooting_grids").select("id,name").eq("team_id",teamId),sb.from("match_stats").select("id").eq("team_id",teamId)]);if(!live)return;const gs=(gg.data||[]) as Grid[];setGrids(gs);const gids=gs.map(g=>g.id);if(gids.length){const [ro,ss]=await Promise.all([sb.from("shooting_grid_rows").select("id,grid_id,name").in("grid_id",gids),sb.from("shooting_grid_sessions").select("id,grid_id").in("grid_id",gids)]);const ses=(ss.data||[]) as Session[];setRows((ro.data||[]) as Row[]);setSessions(ses);const ids=ses.map(s=>s.id);if(ids.length){const rr=await sb.from("shooting_grid_player_results").select("session_id,row_id,player_id,made,attempted").in("session_id",ids);if(live)setResults((rr.data||[]) as Result[])}}const mids=(mm.data||[]).map((x:any)=>x.id);if(mids.length){const aa=await sb.from("match_actions").select("player_id,shot_type,shot_result,shot_zone_id").in("match_id",mids);if(live)setActions((aa.data||[]) as Action[])}if(live)setLoading(false)})();return()=>{live=false}},[sb,teamId]);useEffect(()=>{if(initialPlayerId)setAp(initialPlayerId)},[initialPlayerId]);
const get=(pid:string,src:Source,gid:string)=>src==="match"?matchShots(pid,actions):gridShots(pid,gid,rows,sessions,results),A=get(ap,as,ag),C=get(bp,bs,bg),ta=totals(A),tb=totals(C);const label=(pid:string,src:Source,gid:string)=>`${pname(players.find(p=>String(p.id)===pid))} · ${src==="match"?"Match":grids.find(g=>g.id===gid)?.name||"Toutes les grilles"}`;if(!players.length)return null;
const picker=(pid:string,setPid:any,src:Source,setSrc:any,gid:string,setGid:any,n:number)=><div style={{background:SOFT,border:`1px solid ${BD}`,borderRadius:13,padding:10,display:"grid",gap:7}}><b style={{color:B}}>Sélection {n}</b><select value={pid} onChange={e=>setPid(e.target.value)} style={inp}>{players.map(p=><option key={String(p.id)} value={String(p.id)}>{pname(p)}</option>)}</select><select value={src} onChange={e=>setSrc(e.target.value as Source)} style={inp}><option value="grid">Grille de tir</option><option value="match">Tirs pris en match</option></select>{src==="grid"&&<select value={gid} onChange={e=>setGid(e.target.value)} style={inp}><option value="">Toutes les grilles</option>{grids.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select>}</div>;
return <section style={{border:`1px solid ${BD}`,borderRadius:16,padding:14,background:"#fff"}}><span style={{fontSize:9,fontWeight:1000,letterSpacing:".12em",color:G}}>COMPARAISON</span><h3 style={{margin:"4px 0",color:B}}>Comparer les tirs</h3><p style={{margin:"0 0 12px",fontSize:11,color:M}}>Choisis un joueur, un autre joueur, une grille ou les tirs pris en match. Pour comparer le même joueur grille/match, sélectionne le même nom des deux côtés.</p><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12}}>{picker(ap,setAp,as,setAs,ag,setAg,1)}{picker(bp,setBp,bs,setBs,bg,setBg,2)}</div>{loading?<div style={{padding:20,color:M}}>Chargement…</div>:<><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,marginTop:12}}>{[[A,ta,label(ap,as,ag)],[C,tb,label(bp,bs,bg)]].map((x:any,i)=><div key={i} style={{border:`1px solid ${BD}`,borderRadius:13,padding:10,minWidth:0}}><b style={{display:"block",color:B,fontSize:12,marginBottom:6}}>{x[2]}</b><ShotChart mode="analysis" size="md" shots={x[0]} showStats showLabels showDots={false}/><div style={{textAlign:"center",fontWeight:1000,color:B,marginTop:6}}>{x[1].m}/{x[1].a} · {x[1].p}%</div></div>)}</div><div style={{overflowX:"auto",marginTop:12}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr><th style={th}>Zone</th><th style={th}>{label(ap,as,ag)}</th><th style={th}>{label(bp,bs,bg)}</th><th style={th}>Écart</th></tr></thead><tbody>{SHOT_ZONES.map(z=>{const x=totals(A.filter(s=>s.shot_zone_id===z.id)),y=totals(C.filter(s=>s.shot_zone_id===z.id));if(!x.a&&!y.a)return null;const d=Math.round((x.p-y.p)*10)/10;return <tr key={z.id}><td style={{...td,textAlign:"left",fontWeight:800}}>{z.label}</td><td style={td}>{x.m}/{x.a} · {x.p}%</td><td style={td}>{y.m}/{y.a} · {y.p}%</td><td style={{...td,fontWeight:900,color:B}}>{d>0?"+":""}{d} pts</td></tr>})}</tbody></table></div></>}</section>}
const inp:React.CSSProperties={border:`1px solid ${BD}`,borderRadius:9,padding:"9px 10px",background:"#fff",fontSize:11};const th:React.CSSProperties={padding:8,background:"#F7F2EE",borderBottom:`1px solid ${BD}`,textAlign:"center"};const td:React.CSSProperties={padding:8,borderBottom:`1px solid ${BD}`,textAlign:"center"};
