import {createClient} from '@/lib/supabase/client';import type{ContentItem,ContentKind,DocumentKind,DocumentLayout}from'./types';import{DEFAULT_DOCUMENT_LAYOUT}from'./types';
async function uid(){const s=createClient();const{data}=await s.auth.getUser();if(!data.user)throw new Error('Connexion requise');return data.user.id}
export async function listDocuments(){const s=createClient();const{data,error}=await s.from('coach_documents').select('*').eq('owner_id',await uid()).order('updated_at',{ascending:false});if(error)throw error;return data||[]}
export async function createDocument(title:string,kind:DocumentKind='mixed'){const s=createClient();const{data,error}=await s.from('coach_documents').insert({owner_id:await uid(),title,kind,layout:DEFAULT_DOCUMENT_LAYOUT}).select('*').single();if(error)throw error;return data}
export async function getDocument(id:string){const s=createClient();const{data,error}=await s.from('coach_documents').select('*').eq('owner_id',await uid()).eq('id',id).single();if(error)throw error;return data}
export async function updateDocument(id:string,patch:any){const s=createClient();const{data,error}=await s.from('coach_documents').update({...patch,updated_at:new Date().toISOString()}).eq('owner_id',await uid()).eq('id',id).select('*').single();if(error)throw error;return data}
export async function listDocumentItems(id:string){const s=createClient();const{data,error}=await s.from('coach_document_items').select('*').eq('owner_id',await uid()).eq('document_id',id).order('position');if(error)throw error;return data||[]}
export async function addDocumentItem(document_id:string,item:ContentItem){const s=createClient();const{data,error}=await s.from('coach_document_items').upsert({owner_id:await uid(),document_id,content_type:item.type,content_id:item.id,position:Date.now()},{onConflict:'document_id,content_type,content_id'}).select('*').single();if(error)throw error;return data}
export async function updateDocumentItem(id:string,patch:any){const s=createClient();const{error}=await s.from('coach_document_items').update(patch).eq('owner_id',await uid()).eq('id',id);if(error)throw error}
export async function removeDocumentItem(id:string){const s=createClient();const{error}=await s.from('coach_document_items').delete().eq('owner_id',await uid()).eq('id',id);if(error)throw error}
