import { createClient } from '@/lib/supabase/client';
import { listMyExercises, duplicateExercise, deleteExercise } from '@/lib/exercises';
import { listMySystems, duplicateSystem, deleteSystem } from '@/lib/systems';
import type { ClassificationType, ContentItem, ContentKind, WorkspaceClassification } from './types';
async function uid(){const s=createClient();const {data}=await s.auth.getUser();if(!data.user)throw new Error('Connexion requise');return data.user.id}
export async function listWorkspaceContent():Promise<ContentItem[]>{const [ex,sy]=await Promise.all([listMyExercises(),listMySystems()]);return [...ex.map(x=>({id:x.id,type:'exercise' as const,title:x.title,description:x.description||x.organisation||'',thumbnail:x.schemaImage||x.schemaImages?.[0],tags:x.tags||x.themes||[],createdAt:x.createdAt,updatedAt:x.updatedAt,raw:x})),...sy.map(x=>({id:x.id,type:'system' as const,title:x.title,description:x.objectif||x.organisation||'',thumbnail:x.schemaImage||x.schemaImages?.[0],tags:x.tags||[],createdAt:x.createdAt,updatedAt:x.updatedAt,raw:x}))]}
export async function listClassifications(type?:ClassificationType){const s=createClient();let q=s.from('content_classifications').select('*').eq('owner_id',await uid()).eq('archived',false).order('position');if(type)q=q.eq('type',type);const {data,error}=await q;if(error)throw error;return (data||[]) as WorkspaceClassification[]}
export async function createClassification(type:ClassificationType,name:string,parent_id?:string|null){const s=createClient();const {data,error}=await s.from('content_classifications').insert({owner_id:await uid(),type,name:name.trim(),parent_id:parent_id||null}).select('*').single();if(error)throw error;return data as WorkspaceClassification}
export async function renameClassification(id:string,name:string){const s=createClient();const {error}=await s.from('content_classifications').update({name:name.trim()}).eq('id',id).eq('owner_id',await uid());if(error)throw error}
export async function deleteClassification(id:string){const s=createClient();const {error}=await s.from('content_classifications').delete().eq('id',id).eq('owner_id',await uid());if(error)throw error}
export async function listRelations(){const s=createClient();const {data,error}=await s.from('content_classification_links').select('*').eq('owner_id',await uid());if(error)throw error;return data||[]}
export async function addClassification(content_type:ContentKind,content_id:string,classification_id:string){const s=createClient();const {error}=await s.from('content_classification_links').upsert({owner_id:await uid(),content_type,content_id,classification_id},{onConflict:'owner_id,content_type,content_id,classification_id'});if(error)throw error}
export async function removeClassification(content_type:ContentKind,content_id:string,classification_id:string){const s=createClient();const {error}=await s.from('content_classification_links').delete().eq('owner_id',await uid()).eq('content_type',content_type).eq('content_id',content_id).eq('classification_id',classification_id);if(error)throw error}
export async function toggleFavorite(content_type:ContentKind,content_id:string,favorite:boolean){const s=createClient();if(favorite){const {error}=await s.from('content_favorites').upsert({owner_id:await uid(),content_type,content_id},{onConflict:'owner_id,content_type,content_id'});if(error)throw error}else{await s.from('content_favorites').delete().eq('owner_id',await uid()).eq('content_type',content_type).eq('content_id',content_id)}}
export async function listFavorites(){const s=createClient();const {data}=await s.from('content_favorites').select('content_type,content_id').eq('owner_id',await uid());return data||[]}
export async function duplicateContent(item:ContentItem){return item.type==='exercise'?duplicateExercise(item.id):duplicateSystem(item.id)}
export async function deleteContent(item:ContentItem){return item.type==='exercise'?deleteExercise(item.id):deleteSystem(item.id)}
export function openInDrawing(item:ContentItem){if(typeof window==='undefined')return;['mybasket_edit_exercise_id','mybasket_current_exercise_id','mybasket_edit_system_id','mybasket_current_system_id'].forEach(k=>localStorage.removeItem(k));if(item.type==='exercise'){localStorage.setItem('mybasket_edit_exercise_id',item.id);localStorage.setItem('mybasket_current_exercise_id',item.id);localStorage.setItem('mb_plaquette_return_to',`/exercices/creer?id=${item.id}`);location.href='/plaquette?mode=edit&return=exercise'}else{localStorage.setItem('mybasket_edit_system_id',item.id);localStorage.setItem('mybasket_current_system_id',item.id);localStorage.setItem('mb_plaquette_return_to',`/systemes/creer?id=${item.id}`);location.href='/plaquette?mode=edit&return=systeme'}}
