"use client";
import {use, useEffect,useMemo,useState} from "react";
type Data={grid:any;rows:any[];players:any[];team:any};
export default function PublicShootingGrid({params}:{params:Promise<{token:string}>}){
 const {token}=use(params);const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[playerId,setPlayerId]=useState(""),[other,setOther]=useState(false),[otherName,setOtherName]=useState(""),[scores,setScores]=useState<Record<string,{made:string;attempted:string}>>({}),[sending,setSending]=useState(false),[done,setDone]=useState<any>(null);
 useEffect(()=>{fetch(`/api/public/shooting-grid/${token}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}).catch(e=>setError(e.message))},[token]);
 const progress=useMemo(()=>data?data.rows.filter(r=>{const x=scores[r.id];return x&&(x.made!==""||x.attempted!=="")}).length:0,[data,scores]);
 if(error)return <main style={shell}><div style={card}><h2>Lien indisponible</h2><p>{error}</p></div></main>;if(!data)return <main style={shell}><div style={card}>Chargement…</div></main>;
 const fixed=data.grid.fixed_value||0;function score(rowId:string,key:"made"|"attempted",value:string){setScores(s=>({...s,[rowId]:{made:s[rowId]?.made??"",attempted:s[rowId]?.attempted??"",[key]:value}}))}
 async function submit(){if((!other&&!playerId)||(other&&!otherName.trim()))return setError("Choisis ton nom ou renseigne ton prénom.");if(!data)return;const currentData=data;setSending(true);setError("");const results=currentData.rows.map(r=>{const x=scores[r.id]||{made:"",attempted:""};return {rowId:r.id,made:currentData.grid.input_mode==="fixed_makes"?fixed:Number(x.made||0),attempted:currentData.grid.input_mode==="fixed_attempts"?fixed:Number(x.attempted||0)}});try{const r=await fetch(`/api/public/shooting-grid/${token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playerId:other?null:playerId,otherName:other?otherName:null,results})});const j=await r.json();if(!r.ok)throw new Error(j.error);setDone(j)}catch(e:any){setError(e.message)}finally{setSending(false)}}
 if(done)return <main style={shell}><div style={{...card,textAlign:"center"}}><div style={{fontSize:42}}>✅</div><h1 style={{color:"#6B1A2C"}}>Résultats envoyés</h1><p style={{fontSize:24,fontWeight:900}}>{done.made}/{done.attempted} · {done.percentage}%</p><p>{done.guest?"Tes résultats ont été transmis au coach pour rattachement.":"Ta session a été ajoutée automatiquement à ta fiche joueur."}</p></div></main>;
 return <main style={shell}><div style={{...card,maxWidth:720}}><div style={{color:"#D4A24C",fontWeight:1000,fontSize:12}}>MYBASKET · GRILLE DE TIR</div><h1 style={{margin:"6px 0",color:"#6B1A2C"}}>{data.grid.name}</h1><p style={{color:"#756760"}}>{data.team?.name||"Équipe"}{data.grid.description?` · ${data.grid.description}`:""}</p><label style={field}><b>Qui es-tu ?</b><select value={other?"__other":playerId} onChange={e=>{setOther(e.target.value==="__other");setPlayerId(e.target.value==="__other"?"":e.target.value)}} style={input}><option value="">Choisir mon prénom</option>{data.players.map(p=><option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}<option value="__other">Je ne suis pas dans la liste</option></select></label>{other&&<label style={field}><b>Ton prénom et ton nom</b><input autoFocus value={otherName} onChange={e=>setOtherName(e.target.value)} placeholder="Ex. Lucas Martin" style={input}/><small style={{color:"#756760"}}>Le coach sera averti afin de pouvoir t'ajouter à l'effectif.</small></label>}<div style={{margin:"18px 0 8px",fontSize:12,fontWeight:900,color:"#756760"}}>{progress}/{data.rows.length} positions renseignées</div><div style={{display:"grid",gap:9}}>{data.rows.map((r,i)=>{const x=scores[r.id]||{made:"",attempted:""};return <div key={r.id} style={{border:"1px solid #eadfd9",borderRadius:13,padding:12,display:"grid",gridTemplateColumns:"1fr 110px",gap:10,alignItems:"center"}}><div><b style={{color:"#6B1A2C"}}>{i+1}. {r.name}</b><small style={{display:"block",color:"#756760",marginTop:3}}>{data.grid.input_mode==="fixed_attempts"?`${fixed} tirs · renseigne les paniers marqués`:`${fixed} paniers à marquer · renseigne les tirs tentés`}</small></div>{data.grid.input_mode==="fixed_attempts"?<input type="number" min="0" max={fixed} value={x.made} onChange={e=>score(r.id,"made",e.target.value)} placeholder={`0/${fixed}`} style={input}/>:<input type="number" min={fixed} value={x.attempted} onChange={e=>score(r.id,"attempted",e.target.value)} placeholder={`${fixed}/…`} style={input}/>}</div>})}</div>{error&&<p style={{color:"#b42318",fontWeight:800}}>{error}</p>}<button disabled={sending} onClick={submit} style={{width:"100%",marginTop:18,border:0,borderRadius:12,padding:14,background:"#6B1A2C",color:"white",fontWeight:1000,fontSize:15}}>{sending?"Envoi…":"ENVOYER MES RÉSULTATS"}</button></div></main>
}
const shell:React.CSSProperties={minHeight:"100vh",background:"#f7f3f0",padding:"28px 14px",display:"grid",placeItems:"start center",fontFamily:"Arial,sans-serif"};const card:React.CSSProperties={width:"100%",background:"white",border:"1px solid #eadfd9",borderRadius:20,padding:22,boxShadow:"0 12px 35px rgba(70,25,35,.08)"};const field:React.CSSProperties={display:"grid",gap:6,marginTop:14};const input:React.CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #d9ccc5",borderRadius:10,padding:"10px 11px",background:"#fff",fontSize:14};
