"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type A={id:string;title:string;description:string|null;created_at:string};
const events=[["session.created","Nouvelle séance"],["calendar.changed","Calendrier"],["availability.changed","Blessure / indisponibilité"],["document.added","Nouveau document"],["resource.updated","Fiche technique"],["player.updated","Fiche joueur"],["staff.updated","Staff"],["rpe.alert","Alertes RPE critiques"],["rpe.digest","Récapitulatif RPE"]];
export default function TeamActivityPanel({teamId}:{teamId:string}){
 const supabase=useMemo(()=>createClient(),[]),[items,setItems]=useState<A[]>([]),[prefs,setPrefs]=useState<Record<string,{in_app:boolean;email:boolean}>>({});
 async function load(){const{data:{user}}=await supabase.auth.getUser();const[a,p]=await Promise.all([supabase.from("activity_log").select("*").eq("team_id",teamId).order("created_at",{ascending:false}).limit(100),user?supabase.from("notification_preferences").select("*").eq("user_id",user.id).eq("team_id",teamId):Promise.resolve({data:[]} as any)]);setItems((a.data||[]) as A[]);const m:Record<string,{in_app:boolean;email:boolean}>={};for(const x of p.data||[])m[x.event_key]={in_app:x.in_app,email:x.email};setPrefs(m)}
 useEffect(()=>{void load()},[teamId]); // eslint-disable-line
 async function setPref(k:string,f:"in_app"|"email",v:boolean){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const cur=prefs[k]||{in_app:true,email:true},next={...cur,[f]:v};await supabase.from("notification_preferences").upsert({user_id:user.id,team_id:teamId,event_key:k,...next},{onConflict:"user_id,team_id,event_key"});setPrefs(s=>({...s,[k]:next}))}
 return <section className="grid"><div className="card"><h2>Journal d’activité</h2>{items.map(x=><div className="item" key={x.id}><div><b>{x.title}</b>{x.description&&<span>{x.description}</span>}</div><small>{new Date(x.created_at).toLocaleString("fr-FR")}</small></div>)}</div><div className="card"><h2>Mes notifications</h2>{events.map(([k,l])=>{const p=prefs[k]||{in_app:true,email:true};return <div className="pref" key={k}><span>{l}</span><label>App <input type="checkbox" checked={p.in_app} onChange={e=>setPref(k,"in_app",e.target.checked)}/></label><label>Email <input type="checkbox" checked={p.email} onChange={e=>setPref(k,"email",e.target.checked)}/></label></div>})}</div><style jsx>{`.grid{display:grid;grid-template-columns:1.3fr .7fr;gap:12px}.card{background:#fff;border:1px solid #eadfd8;border-radius:15px;padding:15px}.item{display:flex;justify-content:space-between;gap:10px;border-bottom:1px solid #eee4df;padding:8px 0}.item b,.item span{display:block}.item span,.item small{font-size:.72rem;color:#877970}.pref{display:grid;grid-template-columns:1fr 85px 85px;padding:8px 0;border-bottom:1px solid #eee4df;font-size:.78rem}@media(max-width:850px){.grid{grid-template-columns:1fr}}`}</style></section>
}
