"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type A={id:string;title:string;description:string|null;created_at:string};
type Auto={id:string;title:string;description:string;date:string;icon:string};
const events=[["session.created","Nouvelle séance"],["calendar.changed","Calendrier"],["availability.changed","Blessure / indisponibilité"],["document.added","Nouveau document"],["resource.updated","Fiche technique"],["player.updated","Fiche joueur"],["staff.updated","Staff"],["rpe.alert","Alertes RPE critiques"],["rpe.digest","Récapitulatif RPE"]];
export default function TeamActivityPanel({teamId}:{teamId:string}){
 const supabase=useMemo(()=>createClient(),[]),[items,setItems]=useState<A[]>([]),[auto,setAuto]=useState<Auto[]>([]),[prefs,setPrefs]=useState<Record<string,{in_app:boolean;email:boolean}>>({});
 async function load(){const{data:{user}}=await supabase.auth.getUser();const[a,p,m,g]=await Promise.all([supabase.from("activity_log").select("*").eq("team_id",teamId).order("created_at",{ascending:false}).limit(100),user?supabase.from("notification_preferences").select("*").eq("user_id",user.id).eq("team_id",teamId):Promise.resolve({data:[]} as any),supabase.from("match_stats").select("id,opponent,match_date,us_score,them_score").eq("team_id",teamId).order("match_date",{ascending:false}).limit(8),supabase.from("shooting_grids").select("id,name").eq("team_id",teamId)]);setItems((a.data||[]) as A[]);const feed:Auto[]=(m.data||[]).map((x:any)=>({id:`m-${x.id}`,icon:"🏀",title:`Match · ${x.opponent||"Adversaire"}`,description:x.us_score!=null?`${x.us_score} - ${x.them_score}`:"Statistiques enregistrées",date:x.match_date||new Date().toISOString()}));const gids=(g.data||[]).map((x:any)=>x.id);if(gids.length){const s=await supabase.from("shooting_grid_sessions").select("id,grid_id,session_date").in("grid_id",gids).order("session_date",{ascending:false}).limit(8);const gm=new Map((g.data||[]).map((x:any)=>[x.id,x.name]));for(const x of s.data||[])feed.push({id:`s-${x.id}`,icon:"🎯",title:`Grille de tir · ${gm.get(x.grid_id)||"Session"}`,description:"Nouvelle session de tir enregistrée",date:x.session_date})}setAuto(feed.sort((x,y)=>String(y.date).localeCompare(String(x.date))).slice(0,15));const mm:Record<string,{in_app:boolean;email:boolean}>={};for(const x of p.data||[])mm[x.event_key]={in_app:x.in_app,email:x.email};setPrefs(mm)}
 useEffect(()=>{void load()},[teamId]); // eslint-disable-line
 async function setPref(k:string,f:"in_app"|"email",v:boolean){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const cur=prefs[k]||{in_app:true,email:true},next={...cur,[f]:v};await supabase.from("notification_preferences").upsert({user_id:user.id,team_id:teamId,event_key:k,...next},{onConflict:"user_id,team_id,event_key"});setPrefs(s=>({...s,[k]:next}))}
 return <section className="grid"><div className="card"><h2>Fil d’activité sportive</h2><p className="intro">Matchs, grilles de tir et événements importants de l’équipe remontent ici automatiquement.</p>{auto.map(x=><div className="item" key={x.id}><div><b>{x.icon} {x.title}</b><span>{x.description}</span></div><small>{new Date(`${x.date}T12:00:00`).toLocaleDateString("fr-FR")}</small></div>)}{items.map(x=><div className="item" key={x.id}><div><b>• {x.title}</b>{x.description&&<span>{x.description}</span>}</div><small>{new Date(x.created_at).toLocaleString("fr-FR")}</small></div>)}{!auto.length&&!items.length&&<div className="empty">Aucune activité pour le moment. Les prochains matchs, sessions de tir et alertes apparaîtront automatiquement ici.</div>}</div><div className="card"><h2>Mes notifications</h2>{events.map(([k,l])=>{const p=prefs[k]||{in_app:true,email:true};return <div className="pref" key={k}><span>{l}</span><label>App <input type="checkbox" checked={p.in_app} onChange={e=>setPref(k,"in_app",e.target.checked)}/></label><label>Email <input type="checkbox" checked={p.email} onChange={e=>setPref(k,"email",e.target.checked)}/></label></div>})}</div><style jsx>{`.grid{display:grid;grid-template-columns:1.3fr .7fr;gap:12px}.card{background:#fff;border:1px solid #eadfd8;border-radius:15px;padding:15px}.intro{color:#877970;font-size:.76rem}.item{display:flex;justify-content:space-between;gap:10px;border-bottom:1px solid #eee4df;padding:10px 0}.item b,.item span{display:block}.item span,.item small{font-size:.72rem;color:#877970}.empty{padding:28px;text-align:center;color:#9a8a82;background:#faf7f4;border-radius:12px}.pref{display:grid;grid-template-columns:1fr 85px 85px;padding:8px 0;border-bottom:1px solid #eee4df;font-size:.78rem}@media(max-width:850px){.grid{grid-template-columns:1fr}}`}</style></section>
}
