"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import {logActivity} from "@/lib/activity";

type R={id:string;team_id:string;owner_id:string;title:string;category:string;definition:string|null;content:string|null;visibility:"team"|"club";updated_at:string};
type RL={id:string;resource_id:string;link_type:string;target_id:string|null;label:string;url:string|null;sort_order:number};
type D={id:string;title:string;file_name:string;file_url:string;created_at:string};
type E={id:string;title:string};
const cats=["Lexique","Technique individuelle","Pré-collectif","Collectif","Défense","Jeu rapide","Préparation physique","Management","Autres"];

export default function TeamResourcesPanel({teamId,canEdit}:{teamId:string;canEdit:boolean}){
 const supabase=useMemo(()=>createClient(),[]),[tab,setTab]=useState<"resources"|"documents">("resources"),[resources,setResources]=useState<R[]>([]),[rid,setRid]=useState(""),[links,setLinks]=useState<RL[]>([]),[docs,setDocs]=useState<D[]>([]),[ex,setEx]=useState<E[]>([]),[search,setSearch]=useState("");
 const selected=resources.find(x=>x.id===rid)||null;
 async function loadLinks(id:string){const q=await supabase.from("team_resource_links").select("*").eq("resource_id",id).order("sort_order");setLinks((q.data||[]) as RL[])}
 async function reload(pref?:string){const[r,d,e]=await Promise.all([supabase.from("team_resources").select("*").eq("team_id",teamId).order("updated_at",{ascending:false}),supabase.from("team_documents_shared").select("*").eq("team_id",teamId).order("created_at",{ascending:false}),supabase.from("exercises").select("id,title").order("title").limit(500)]);const list=(r.data||[]) as R[];setResources(list);setDocs((d.data||[]) as D[]);setEx((e.data||[]) as E[]);const next=pref&&list.some(x=>x.id===pref)?pref:(list.some(x=>x.id===rid)?rid:list[0]?.id||"");setRid(next);if(next)await loadLinks(next)}
 useEffect(()=>{void reload()},[teamId]); // eslint-disable-line
 function patch(p:Partial<R>){if(!selected)return;setResources(a=>a.map(x=>x.id===selected.id?{...x,...p}:x))}
 async function create(){if(!canEdit)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const q=await supabase.from("team_resources").insert({team_id:teamId,owner_id:user.id,title:"Nouvelle fiche repère",category:"Autres",definition:"",content:"",visibility:"team"}).select("*").single();if(q.error){alert(q.error.message);return}await logActivity({teamId,scope:"resource",actionKey:"resource.created",title:"Nouvelle fiche repère créée",href:`/equipes/${teamId}`});await reload(q.data.id)}
 async function save(){if(!selected||!canEdit)return;const q=await supabase.from("team_resources").update({title:selected.title.trim()||"Fiche repère",category:selected.category,definition:selected.definition?.trim()||null,content:selected.content?.trim()||null,visibility:selected.visibility,updated_at:new Date().toISOString()}).eq("id",selected.id);if(q.error){alert(q.error.message);return}await logActivity({teamId,scope:"resource",actionKey:"resource.updated",title:`Fiche modifiée : ${selected.title}`,href:`/equipes/${teamId}`})}
 async function addExercise(e:E){if(!selected||!canEdit)return;await supabase.from("team_resource_links").insert({resource_id:selected.id,link_type:"exercise",target_id:e.id,label:e.title,sort_order:links.length});await loadLinks(selected.id)}
 async function upload(file:File){if(!canEdit)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const clean=file.name.replace(/[^a-zA-Z0-9._-]/g,"-"),path=`${teamId}/${crypto.randomUUID()}-${clean}`;const up=await supabase.storage.from("team-documents").upload(path,file);if(up.error){alert(up.error.message);return}const url=supabase.storage.from("team-documents").getPublicUrl(path).data.publicUrl;const q=await supabase.from("team_documents_shared").insert({team_id:teamId,owner_id:user.id,title:file.name,file_name:file.name,storage_path:path,file_url:url});if(q.error){alert(q.error.message);return}await logActivity({teamId,scope:"document",actionKey:"document.added",title:`Document ajouté : ${file.name}`,href:`/equipes/${teamId}`});await reload(rid)}
 const filtered=ex.filter(x=>x.title.toLowerCase().includes(search.toLowerCase())).slice(0,20);
 return <section><div className="tabs"><button className={tab==="resources"?"active":""} onClick={()=>setTab("resources")}>Fiches techniques</button><button className={tab==="documents"?"active":""} onClick={()=>setTab("documents")}>Fichiers partagés</button></div>
 {tab==="resources"?<div className="layout"><aside>{canEdit&&<button className="primary" onClick={create}>+ Nouvelle fiche</button>}{resources.map(r=><button className={r.id===rid?"res active":"res"} key={r.id} onClick={async()=>{setRid(r.id);await loadLinks(r.id)}}><b>{r.title}</b><span>{r.category}</span></button>)}</aside><div className="card">{selected?<><div className="fields"><input disabled={!canEdit} value={selected.title} onChange={e=>patch({title:e.target.value})}/><select disabled={!canEdit} value={selected.category} onChange={e=>patch({category:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select><select disabled={!canEdit} value={selected.visibility} onChange={e=>patch({visibility:e.target.value as R["visibility"]})}><option value="team">Équipe</option><option value="club">Club</option></select><textarea className="wide" disabled={!canEdit} value={selected.definition||""} onChange={e=>patch({definition:e.target.value})} placeholder="Définition"/><textarea className="wide big" disabled={!canEdit} value={selected.content||""} onChange={e=>patch({content:e.target.value})} placeholder={"Pick & Roll sur Step\nCe qu’on recherche...\nLecture porteur / roller...\nSpacing..."}/></div>{canEdit&&<button className="primary" onClick={save}>Enregistrer</button>}<h3>Exercices recommandés</h3>{links.map(l=><div className="link" key={l.id}>{l.target_id?<Link href={`/exercices/${l.target_id}`}>▶ {l.label}</Link>:l.label}{canEdit&&<button onClick={async()=>{await supabase.from("team_resource_links").delete().eq("id",l.id);await loadLinks(selected.id)}}>×</button>}</div>)}{canEdit&&<div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Chercher un exercice..."/>{search&&<div className="results">{filtered.map(x=><button key={x.id} onClick={()=>addExercise(x)}>+ {x.title}</button>)}</div>}</div>}</>:<p>Aucune fiche.</p>}</div></div>:<div className="card"><div className="dochead"><h2>Documents équipe</h2>{canEdit&&<label className="primary">+ Ajouter<input hidden type="file" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value=""}}/></label>}</div>{docs.map(d=><a className="doc" key={d.id} href={d.file_url} target="_blank" rel="noreferrer"><b>{d.title}</b><span>{new Date(d.created_at).toLocaleDateString("fr-FR")}</span></a>)}</div>}
 <style jsx>{`.tabs{display:flex;gap:6px;margin-bottom:10px}.tabs button{border:1px solid #ddd1ca;background:#fff;color:#6b1a2c;border-radius:999px;padding:9px 12px;font-weight:900}.tabs .active{background:#6b1a2c;color:#fff}.layout{display:grid;grid-template-columns:250px 1fr;gap:10px}aside,.card{background:#fff;border:1px solid #eadfd8;border-radius:15px;padding:12px}aside{display:grid;align-content:start;gap:5px}.res{text-align:left;border:1px solid #eee4df;background:#fff;border-radius:9px;padding:8px}.res b,.res span{display:block}.res span{font-size:.68rem;color:#877970}.res.active{border-color:#6b1a2c}.primary{background:#6b1a2c;color:#fff;border:0;border-radius:9px;padding:9px 11px;font-weight:900;cursor:pointer}.fields{display:grid;grid-template-columns:1fr 1fr 1fr;gap:7px}.fields input,.fields select,.fields textarea,.search{border:1px solid #ddd1ca;border-radius:8px;padding:8px}.wide{grid-column:1/-1}.big{min-height:170px}.link,.doc{display:flex;justify-content:space-between;border:1px solid #eee4df;border-radius:9px;padding:8px;margin:5px 0}.link a,.doc{text-decoration:none;color:#6b1a2c}.link button{border:0;background:transparent;color:#a52c2c}.results{display:grid;max-height:220px;overflow:auto}.results button{text-align:left;border:0;background:#faf6f3;padding:7px}.dochead{display:flex;justify-content:space-between}.doc span{color:#8a7c74}@media(max-width:850px){.layout{grid-template-columns:1fr}.fields{grid-template-columns:1fr}.wide{grid-column:auto}}`}</style></section>
}
