"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {logActivity} from "@/lib/activity";
import type {Player} from "@/types/player";

type Status="available"|"limited"|"injured"|"unavailable"|"absent"|"returning";
type A={id:string;player_id:string;status:Status;starts_at:string;ends_at:string|null;reason:string|null};
type L={id:string;player_id:string|null;load_date:string;duration_minutes:number;planned_rpe:number|null;actual_rpe:number|null;planned_load:number;actual_load:number;load_type:string};
const statuses:[Status,string][]=[["available","Disponible"],["limited","Limité"],["injured","Blessé"],["unavailable","Indisponible"],["absent","Absent"],["returning","Retour progressif"]];
const color=(s:Status)=>["injured","unavailable","absent"].includes(s)?"#b42318":["limited","returning"].includes(s)?"#b26a00":"#15803d";

export default function TeamAvailabilityLoad({teamId,players,canEdit}:{teamId:string;players:Player[];canEdit:boolean}){
 const supabase=useMemo(()=>createClient(),[]),[map,setMap]=useState<Record<string,A>>({}),[loads,setLoads]=useState<L[]>([]);
 const [pid,setPid]=useState(players[0]?.id?String(players[0].id):""),[status,setStatus]=useState<Status>("available"),[reason,setReason]=useState(""),[end,setEnd]=useState("");
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[duration,setDuration]=useState(90),[planned,setPlanned]=useState(6),[actual,setActual]=useState<number|"">(""),[type,setType]=useState("basket");
 async function reload(){const now=new Date().toISOString();const[a,l]=await Promise.all([
  supabase.from("player_availability").select("*").eq("team_id",teamId).lte("starts_at",now).or(`ends_at.is.null,ends_at.gte.${now}`).order("starts_at",{ascending:false}),
  supabase.from("training_load_entries").select("*").eq("team_id",teamId).order("load_date",{ascending:false}).limit(250)
 ]);const m:Record<string,A>={};for(const r of (a.data||[]) as A[])if(!m[r.player_id])m[r.player_id]=r;setMap(m);setLoads((l.data||[]) as L[])}
 useEffect(()=>{void reload()},[teamId]); // eslint-disable-line
 async function saveStatus(){if(!canEdit||!pid)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const q=await supabase.from("player_availability").insert({team_id:teamId,player_id:pid,status,starts_at:new Date().toISOString(),ends_at:end?new Date(`${end}T23:59:59`).toISOString():null,reason:reason||null,created_by:user.id});if(q.error){alert(q.error.message);return}const p=players.find(x=>String(x.id)===pid);await logActivity({teamId,playerId:pid,scope:"player",actionKey:"availability.changed",title:`${p?.firstName||"Joueur"} ${p?.lastName||""} : ${statuses.find(x=>x[0]===status)?.[1]}`,description:reason||null,href:`/equipes/${teamId}/${pid}`});await reload()}
 async function saveLoad(){if(!canEdit)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const q=await supabase.from("training_load_entries").insert({team_id:teamId,player_id:pid||null,load_date:date,duration_minutes:duration,planned_rpe:planned,actual_rpe:actual===""?null:actual,load_type:type,created_by:user.id});if(q.error){alert(q.error.message);return}await logActivity({teamId,playerId:pid||null,scope:"training",actionKey:"load.created",title:`Charge ajoutée · ${duration} min · RPE ${actual===""?planned:actual}`,href:`/equipes/${teamId}`});await reload()}
 const totals=useMemo(()=>{const m=new Map<string,{p:number;a:number}>();for(const r of loads){const x=m.get(r.load_date)||{p:0,a:0};x.p+=Number(r.planned_load||0);x.a+=Number(r.actual_load||0);m.set(r.load_date,x)}return Array.from(m.entries()).slice(0,14)},[loads]);
 return <section className="wrap"><div className="card"><h2>Disponibilité joueurs</h2><div className="players">{players.map(p=>{const a=map[String(p.id)],s=a?.status||"available";return <div key={String(p.id)} className="player" style={{borderColor:color(s)}}><b>{p.firstName} {p.lastName}</b><span style={{color:color(s)}}>{statuses.find(x=>x[0]===s)?.[1]}</span>{a?.reason&&<small>{a.reason}</small>}</div>})}</div>{canEdit&&<div className="form"><select value={pid} onChange={e=>setPid(e.target.value)}>{players.map(p=><option key={String(p.id)} value={String(p.id)}>{p.firstName} {p.lastName}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value as Status)}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/><input className="wide" placeholder="Motif / information staff" value={reason} onChange={e=>setReason(e.target.value)}/><button onClick={saveStatus}>Mettre à jour</button></div>}</div>
 <div className="card"><h2>Suivi de charge</h2>{canEdit&&<div className="form"><select value={pid} onChange={e=>setPid(e.target.value)}>{players.map(p=><option key={String(p.id)} value={String(p.id)}>{p.firstName} {p.lastName}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><input type="number" value={duration} onChange={e=>setDuration(Number(e.target.value)||0)} placeholder="Durée"/><input type="number" min="0" max="10" step=".5" value={planned} onChange={e=>setPlanned(Number(e.target.value)||0)} placeholder="RPE visé"/><input type="number" min="0" max="10" step=".5" value={actual} onChange={e=>setActual(e.target.value===""?"":Number(e.target.value))} placeholder="RPE réel"/><select value={type} onChange={e=>setType(e.target.value)}><option value="basket">Basket</option><option value="physical">Préparation physique</option><option value="game">Match</option><option value="individual">Individuel</option></select><div className="preview">Prévue <b>{Math.round(duration*planned)}</b> · Réelle <b>{Math.round(duration*(actual===""?0:actual))}</b></div><button onClick={saveLoad}>Enregistrer charge</button></div>}<div className="history">{totals.map(([d,x])=><div key={d}><span>{new Date(`${d}T12:00:00`).toLocaleDateString("fr-FR")}</span><span>Prévue <b>{Math.round(x.p)}</b></span><span>Réelle <b>{Math.round(x.a)}</b></span></div>)}</div></div>
 <style jsx>{`.wrap{display:grid;grid-template-columns:1fr 1fr;gap:13px}.card{background:#fff;border:1px solid #eadfd8;border-radius:16px;padding:16px}.players{display:grid;grid-template-columns:1fr 1fr;gap:7px}.player{border:1px solid;border-radius:10px;padding:9px;display:grid}.player span{font-size:.72rem;font-weight:900}.player small{color:#81736c}.form{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;border-top:1px solid #eee4df;margin-top:12px;padding-top:12px}.form input,.form select{border:1px solid #ddd1ca;border-radius:9px;padding:8px}.wide{grid-column:1/-1}.form button{background:#6b1a2c;color:#fff;border:0;border-radius:9px;font-weight:900}.preview{border:1px solid #eee4df;border-radius:9px;padding:9px}.history>div{display:grid;grid-template-columns:1fr 1fr 1fr;padding:7px 0;border-bottom:1px solid #eee4df;font-size:.76rem}@media(max-width:900px){.wrap{grid-template-columns:1fr}}`}</style></section>
}
