"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Choice={name:string;url:string};type Game={sourceKey:string;round:string;date:string;time:string;homeAway:string;opponent:string;ourScore:number|null;opponentScore:number|null};type Parsed={mode:"team";team:string;competition:string;pool:string;phase:string;sourceUrl:string;matches:Game[];classementText:string;updatedAt:string}|{mode:"choose-team";sourceUrl:string;teams:Choice[]};
export default function TeamFfbbCompetition({teamId}:{teamId:string}){const sb=useMemo(()=>createClient(),[]),[url,setUrl]=useState(""),[data,setData]=useState<Parsed|null>(null),[connections,setConnections]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function reload(){const q=await sb.from("ffbb_team_connections").select("*").eq("team_id",teamId).order("created_at");if(!q.error)setConnections(q.data||[])}useEffect(()=>{reload()},[teamId]);
 async function read(target=url){if(!target)return;setBusy(true);setError("");try{const r=await fetch(`/api/ffbb/competition?url=${encodeURIComponent(target)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Erreur FFBB");setData(j)}catch(e){setError(e instanceof Error?e.message:"Erreur FFBB")}finally{setBusy(false)}}
 async function connect(p:Extract<Parsed,{mode:"team"}>){const existing=connections.find(c=>c.source_url===p.sourceUrl);const payload={team_id:teamId,source_url:p.sourceUrl,ffbb_team_name:p.team,competition_name:p.competition,pool_name:p.pool||null,phase_id:p.phase||null,competition_kind:/coupe|trophée|supercoupe/i.test(p.competition)?"cup":"championship",logical_competition_key:p.competition.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),is_primary:connections.length===0,last_synced_at:new Date().toISOString()};const q=existing?await sb.from("ffbb_team_connections").update(payload).eq("id",existing.id).select().single():await sb.from("ffbb_team_connections").insert(payload).select().single();if(q.error)throw q.error;const cid=q.data.id;if(p.matches.length){await sb.from("ffbb_synced_matches").upsert(p.matches.map(g=>({connection_id:cid,team_id:teamId,source_match_key:g.sourceKey,round_label:g.round||null,match_date:g.date,start_time:g.time||null,home_away:g.homeAway,opponent:g.opponent,our_score:g.ourScore,opponent_score:g.opponentScore,competition_kind:payload.competition_kind,source_url:p.sourceUrl,last_synced_at:new Date().toISOString()})),{onConflict:"connection_id,source_match_key"})}await reload()}
 async function syncAll(){setBusy(true);setError("");try{for(const c of connections){const r=await fetch(`/api/ffbb/competition?url=${encodeURIComponent(c.source_url)}`,{cache:"no-store"}),p=await r.json();if(r.ok&&p.mode==="team")await connect(p)}}catch(e){setError(e instanceof Error?e.message:"Synchronisation impossible")}finally{setBusy(false)}}
 async function calendarSync(){setBusy(true);setError("");try{const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error("Connexion requise");const q=await sb.from("ffbb_synced_matches").select("*").eq("team_id",teamId).order("match_date");if(q.error)throw q.error;for(const m of q.data||[]){const payload={user_id:user.id,team_id:teamId,title:`Match ${m.home_away==="away"?"@":"vs"} ${m.opponent}`,description:`Synchronisé FFBB · ${m.competition_kind==="cup"?"Coupe":"Championnat"}${m.round_label?` · ${m.round_label}`:""}`,event_date:m.match_date,start_time:m.start_time,end_time:null,location:null,event_type:"game",session_id:null,attachment_url:null,visibility:"private",ffbb_synced_match_id:m.id};const ex=await sb.from("calendar_events").select("id").eq("ffbb_synced_match_id",m.id).maybeSingle();if(ex.data?.id)await sb.from("calendar_events").update(payload).eq("id",ex.data.id);else await sb.from("calendar_events").insert(payload)}}catch(e){setError(e instanceof Error?e.message:"Calendrier impossible")}finally{setBusy(false)}}
 return <section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><small style={eyebrow}>COMPÉTITIONS FFBB</small><h2 style={h2}>Connecter calendrier & classement</h2><p style={hint}>Plusieurs phases d’un même championnat restent une seule compétition MyBasket : les matchs sont cumulés. Les statistiques avancées MyBasket restent inchangées.</p></div>{connections.length>0&&<div style={{display:"flex",gap:7}}><button style={secondary} onClick={calendarSync} disabled={busy}>📅 Alimenter le calendrier</button><button style={btn} onClick={syncAll} disabled={busy}>↻ Tout actualiser</button></div>}</div>
 <div style={{display:"flex",gap:7,marginTop:12,flexWrap:"wrap"}}><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Colle une page équipe, poule ou championnat FFBB" style={input}/><button style={btn} onClick={()=>read()} disabled={busy}>{busy?"Lecture…":"Analyser"}</button><a style={secondary} href="https://competitions.ffbb.com/" target="_blank" rel="noreferrer">🔎 Rechercher sur FFBB ↗</a></div><p style={hint}>Sur FFBB, recherche ton club ou ton équipe puis colle ici la page trouvée. Si tu colles une compétition/poule, MyBasket te demandera quelle équipe choisir.</p>{error&&<p style={{color:"#a22",fontSize:12}}>{error}</p>}
 {data?.mode==="choose-team"&&<div style={box}><b>Quelle est ton équipe ?</b><div style={{display:"grid",gap:7,marginTop:8}}>{data.teams.length?data.teams.map(t=><button key={t.url} style={choice} onClick={()=>{setUrl(t.url);read(t.url)}}>{t.name}<span>Choisir →</span></button>):<p style={hint}>Aucune équipe exploitable détectée sur cette page. Ouvre ton club sur FFBB, clique sur l’équipe concernée puis colle son lien.</p>}</div></div>}
 {data?.mode==="team"&&<div style={box}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><div><b>{data.team}</b><div style={hint}>{data.competition}{data.pool?` · Poule ${data.pool}`:""}{data.phase?` · phase ${data.phase}`:""}</div></div><button style={btn} onClick={()=>connect(data)}>✓ Connecter cette phase</button></div><div style={{marginTop:9,fontSize:12}}>{data.matches.slice(0,5).map(g=><div key={g.sourceKey} style={{padding:"6px 0",borderBottom:"1px solid #eee4df"}}>🏀 {g.date} {g.time} · {g.homeAway==="home"?"vs":"@"} {g.opponent}</div>)}</div></div>}
 {connections.length>0&&<div style={{marginTop:14}}><b>Compétitions connectées</b><div style={{display:"grid",gap:8,marginTop:8}}>{Object.entries(connections.reduce((a:any,c:any)=>((a[c.logical_competition_key]??=[]).push(c),a),{})).map(([k,cs]:any)=><div key={k} style={box}><strong>{cs[0].competition_name}</strong><span style={{marginLeft:8,fontSize:11,color:"#7b6d66"}}>• {cs.length} phase{cs.length>1?"s":""} cumulée{cs.length>1?"s":""}</span><div style={hint}>{cs.map((c:any)=>`${c.pool_name?`Poule ${c.pool_name}`:""}${c.phase_id?` · ${c.phase_id}`:""}`).join("  +  ")}</div></div>)}</div></div>}
 </section>}
const card:React.CSSProperties={border:"1px solid #eadfd8",borderRadius:15,padding:15,background:"#fff",marginTop:12};const box:React.CSSProperties={border:"1px solid #eadfd8",borderRadius:11,padding:11,marginTop:10,background:"#fffaf7"};const eyebrow:React.CSSProperties={color:"#d0a04a",fontWeight:1000,letterSpacing:".1em"};const h2:React.CSSProperties={margin:"4px 0",color:"#6b1a2c"};const hint:React.CSSProperties={fontSize:11,color:"#7c6e67",margin:"4px 0"};const input:React.CSSProperties={flex:"1 1 420px",border:"1px solid #ddcfc8",borderRadius:9,padding:10};const btn:React.CSSProperties={border:0,borderRadius:9,background:"#6b1a2c",color:"white",padding:"9px 12px",fontWeight:900,cursor:"pointer"};const secondary:React.CSSProperties={border:"1px solid #d9c8be",borderRadius:9,color:"#6b1a2c",padding:"9px 12px",fontWeight:900,textDecoration:"none"};const choice:React.CSSProperties={display:"flex",justifyContent:"space-between",border:"1px solid #eadfd8",borderRadius:9,padding:"10px 12px",background:"white",color:"#4c3337",fontWeight:800,cursor:"pointer"};
