import React from "react";
import {renderToBuffer} from "@react-pdf/renderer";
import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin-server";
import {buildPlayerNotebookSnapshot} from "@/lib/institutionnel/player-notebook-data";
import {PoleExitPdf,type PoleExitSection} from "@/lib/institutionnel/pole-exit-pdf";
export const runtime="nodejs";
export async function POST(req:Request){const sb=await createClient(),{data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:"Non connecté"},{status:401});const b=await req.json().catch(()=>({})),structureId=String(b.structureId||""),playerId=String(b.playerId||""),seasonId=b.seasonId?String(b.seasonId):null,sections=(Array.isArray(b.sections)?b.sections:[]) as PoleExitSection[];const db=createAdminClient()||sb;const {data:structure}=await db.from("institutional_structures").select("id,structure_type").eq("id",structureId).maybeSingle();const {data:m}=await db.from("institutional_members").select("id").eq("structure_id",structureId).eq("user_id",user.id).eq("status","active").maybeSingle();if(!m||structure?.structure_type!=="pole")return NextResponse.json({error:"Cette action est réservée au Pôle."},{status:403});try{const snapshot=await buildPlayerNotebookSnapshot({structureId,playerId,seasonId});const buffer=await renderToBuffer(React.createElement(PoleExitPdf,{snapshot,sections:sections.length?sections:undefined}) as React.ReactElement<any>);await db.from("institutional_player_exit_exports").insert({structure_id:structureId,player_id:playerId,season_id:seasonId,sections:sections.length?sections:null,export_type:"pdf",created_by:user.id});const p:any=snapshot.player,filename=`Dossier_sortie_${String(p.first_name||"").replace(/\s+/g,"-")}_${String(p.last_name||"").replace(/\s+/g,"-")}.pdf`;return new Response(new Uint8Array(buffer),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${filename}"`,"Cache-Control":"no-store"}})}catch(e:any){return NextResponse.json({error:e?.message||"Génération impossible"},{status:400})}}
