"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

const CATS=["U5","U7","U9","U11","U13","U15","U18","U21","Seniors","Vétérans","Loisir","Académie","3x3"];
const LEVELS=["Départemental","Régional","National","Autre"];
const MODS=[["teams","Équipes"],["planning","Planning"],["convocations","Convocations"],["documents","Documents"],["communication","Communication"],["cotisations","Cotisations"],["relances","Relances"],["finance","Finance"],["performance","Performance"]];
type TeamSetup={category:string;count:number;gender:string;level:string;fee:number};

export default function Page(){
 const router=useRouter(),supabase=useMemo(()=>createClient(),[]),[step,setStep]=useState(1),[saving,setSaving]=useState(false);
 const [id,setId]=useState({name:"",shortName:"",ffbb:"",committee:"",league:"",address:"",city:"",postal:"",email:"",phone:"",website:"",c1:"#6B1A2C",c2:"#D4A24C"});
 const [org,setOrg]=useState({president:"",technical:"",admin:"",treasurer:"",members:0,teams:0,scope:"Mixte"});
 const [facilities,setFacilities]=useState([{name:"",address:"",courts:1,capacity:"",changing:"",access:"",slots:""}]);
 const [season,setSeason]=useState("2026-2027"),[restart,setRestart]=useState(""),[teams,setTeams]=useState<TeamSetup[]>([]);
 const [payments,setPayments]=useState({bankTransfer:true,cheque:true,cash:true}),[mods,setMods]=useState<Record<string,boolean>>(Object.fromEntries(MODS.map(([k])=>[k,true]))),[logo,setLogo]=useState<File|null>(null);
 const toggle=(c:string)=>setTeams(a=>a.some(t=>t.category===c)?a.filter(t=>t.category!==c):[...a,{category:c,count:1,gender:"Mixte",level:"Départemental",fee:0}]);
 async function create(){if(!id.name.trim()){alert("Nom du club obligatoire");setStep(1);return}setSaving(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Non connecté");const cq=await supabase.from("clubs").insert({name:id.name.trim(),city:id.city||null,status:"active",created_by:user.id}).select("id").single();if(cq.error)throw cq.error;const clubId=cq.data.id;const mq=await supabase.from("club_members").insert({club_id:clubId,user_id:user.id,role:"owner",status:"active"});if(mq.error)throw mq.error;let logoUrl:string|null=null;if(logo){const path=`${clubId}/${crypto.randomUUID()}-${logo.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const u=await supabase.storage.from("club-assets").upload(path,logo);if(!u.error)logoUrl=supabase.storage.from("club-assets").getPublicUrl(path).data.publicUrl}
 const pq=await supabase.from("club_onboarding_profiles").insert({club_id:clubId,short_name:id.shortName||null,logo_url:logoUrl,ffbb_number:id.ffbb||null,committee_name:id.committee||null,league_name:id.league||null,address:id.address||null,postal_code:id.postal||null,city:id.city||null,email:id.email||null,phone:id.phone||null,website:id.website||null,primary_color:id.c1,secondary_color:id.c2,president_name:org.president||null,technical_manager_name:org.technical||null,administrative_manager_name:org.admin||null,treasurer_name:org.treasurer||null,approximate_members:org.members,approximate_teams:org.teams,gender_scope:org.scope,season_label:season,restart_date:restart||null,payment_methods:payments,onboarding_completed:true});if(pq.error)throw pq.error;
 for(const f of facilities.filter(x=>x.name.trim())){const q=await supabase.from("club_facilities").insert({club_id:clubId,name:f.name,address:f.address||null,court_count:f.courts,capacity:f.capacity?Number(f.capacity):null,changing_rooms:f.changing||null,access_info:f.access||null,available_slots:f.slots||null});if(q.error)throw q.error}
 for(const t of teams){for(let i=1;i<=t.count;i++){const q=await supabase.from("club_teams").insert({club_id:clubId,name:`${t.category} Équipe ${i}`,category:t.category,level:t.level,season,status:"active"});if(q.error)throw q.error}const q=await supabase.from("club_membership_fees").insert({club_id:clubId,season_label:season,category:t.category,amount_cents:Math.round(t.fee*100)});if(q.error)throw q.error}
 const q=await supabase.from("club_module_settings").insert(Object.entries(mods).map(([module_key,enabled])=>({club_id:clubId,module_key,enabled})));if(q.error)throw q.error;router.push("/mon-compte/club")}catch(e:any){console.error(e);alert(e?.message||"Erreur création club")}finally{setSaving(false)}}
 return <main className="page"><div className="shell"><header><p>ESPACE CLUB</p><h1>Créer mon club</h1><span>Étape {step}/5</span></header><div className="progress"><i style={{width:`${step*20}%`}}/></div>
 {step===1&&<section className="card"><h2>1. Identité</h2><div className="fields"><F l="Nom officiel *"><input value={id.name} onChange={e=>setId({...id,name:e.target.value})}/></F><F l="Nom court"><input value={id.shortName} onChange={e=>setId({...id,shortName:e.target.value})}/></F><F l="Logo"><input type="file" accept="image/*" onChange={e=>setLogo(e.target.files?.[0]||null)}/></F><F l="N° affiliation FFBB"><input value={id.ffbb} onChange={e=>setId({...id,ffbb:e.target.value})}/></F><F l="Comité départemental"><input value={id.committee} onChange={e=>setId({...id,committee:e.target.value})}/></F><F l="Ligue régionale"><input value={id.league} onChange={e=>setId({...id,league:e.target.value})}/></F><F l="Adresse"><input value={id.address} onChange={e=>setId({...id,address:e.target.value})}/></F><F l="Code postal"><input value={id.postal} onChange={e=>setId({...id,postal:e.target.value})}/></F><F l="Ville"><input value={id.city} onChange={e=>setId({...id,city:e.target.value})}/></F><F l="Email"><input value={id.email} onChange={e=>setId({...id,email:e.target.value})}/></F><F l="Téléphone"><input value={id.phone} onChange={e=>setId({...id,phone:e.target.value})}/></F><F l="Site"><input value={id.website} onChange={e=>setId({...id,website:e.target.value})}/></F><F l="Couleur 1"><input type="color" value={id.c1} onChange={e=>setId({...id,c1:e.target.value})}/></F><F l="Couleur 2"><input type="color" value={id.c2} onChange={e=>setId({...id,c2:e.target.value})}/></F></div></section>}
 {step===2&&<section className="card"><h2>2. Organisation</h2><div className="fields"><F l="Président"><input value={org.president} onChange={e=>setOrg({...org,president:e.target.value})}/></F><F l="Responsable technique"><input value={org.technical} onChange={e=>setOrg({...org,technical:e.target.value})}/></F><F l="Responsable administratif"><input value={org.admin} onChange={e=>setOrg({...org,admin:e.target.value})}/></F><F l="Trésorier"><input value={org.treasurer} onChange={e=>setOrg({...org,treasurer:e.target.value})}/></F><F l="Licenciés approx."><input type="number" value={org.members} onChange={e=>setOrg({...org,members:Number(e.target.value)||0})}/></F><F l="Équipes approx."><input type="number" value={org.teams} onChange={e=>setOrg({...org,teams:Number(e.target.value)||0})}/></F><F l="Structure"><select value={org.scope} onChange={e=>setOrg({...org,scope:e.target.value})}><option>Masculin</option><option>Féminin</option><option>Mixte</option></select></F></div><p>Ces responsables sont d’abord des informations. Tu pourras ensuite les inviter.</p></section>}
 {step===3&&<section className="card"><h2>3. Installations</h2>{facilities.map((f,i)=><div className="facility" key={i}><F l="Gymnase"><input value={f.name} onChange={e=>setFacilities(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/></F><F l="Adresse"><input value={f.address} onChange={e=>setFacilities(a=>a.map((x,j)=>j===i?{...x,address:e.target.value}:x))}/></F><F l="Terrains"><input type="number" min="1" value={f.courts} onChange={e=>setFacilities(a=>a.map((x,j)=>j===i?{...x,courts:Number(e.target.value)||1}:x))}/></F><F l="Capacité"><input value={f.capacity} onChange={e=>setFacilities(a=>a.map((x,j)=>j===i?{...x,capacity:e.target.value}:x))}/></F><F l="Vestiaires"><input value={f.changing} onChange={e=>setFacilities(a=>a.map((x,j)=>j===i?{...x,changing:e.target.value}:x))}/></F><F l="Accès"><input value={f.access} onChange={e=>setFacilities(a=>a.map((x,j)=>j===i?{...x,access:e.target.value}:x))}/></F><F l="Créneaux"><textarea value={f.slots} onChange={e=>setFacilities(a=>a.map((x,j)=>j===i?{...x,slots:e.target.value}:x))}/></F></div>)}<button onClick={()=>setFacilities(a=>[...a,{name:"",address:"",courts:1,capacity:"",changing:"",access:"",slots:""}])}>+ Ajouter gymnase</button></section>}
 {step===4&&<section className="card"><h2>4. Saison</h2><div className="fields"><F l="Saison"><select value={season} onChange={e=>setSeason(e.target.value)}><option>2025-2026</option><option>2026-2027</option><option>2027-2028</option></select></F><F l="Date reprise"><input type="date" value={restart} onChange={e=>setRestart(e.target.value)}/></F></div><h3>Catégories engagées</h3><div className="chips">{CATS.map(c=><button key={c} className={teams.some(t=>t.category===c)?"active":""} onClick={()=>toggle(c)}>{c}</button>)}</div>{teams.map(t=><div className="teamrow" key={t.category}><b>{t.category}</b><F l="Nb équipes"><input type="number" min="1" value={t.count} onChange={e=>setTeams(a=>a.map(x=>x.category===t.category?{...x,count:Number(e.target.value)||1}:x))}/></F><F l="Genre"><select value={t.gender} onChange={e=>setTeams(a=>a.map(x=>x.category===t.category?{...x,gender:e.target.value}:x))}><option>Masculin</option><option>Féminin</option><option>Mixte</option></select></F><F l="Niveau"><select value={t.level} onChange={e=>setTeams(a=>a.map(x=>x.category===t.category?{...x,level:e.target.value}:x))}>{LEVELS.map(l=><option key={l}>{l}</option>)}</select></F><F l="Cotisation €"><input type="number" value={t.fee} onChange={e=>setTeams(a=>a.map(x=>x.category===t.category?{...x,fee:Number(e.target.value)||0}:x))}/></F></div>)}<h3>Paiements</h3><div className="checks"><label><input type="checkbox" checked={payments.bankTransfer} onChange={e=>setPayments({...payments,bankTransfer:e.target.checked})}/> Virement</label><label><input type="checkbox" checked={payments.cheque} onChange={e=>setPayments({...payments,cheque:e.target.checked})}/> Chèque</label><label><input type="checkbox" checked={payments.cash} onChange={e=>setPayments({...payments,cash:e.target.checked})}/> Liquide</label></div></section>}
 {step===5&&<section className="card"><h2>5. Configuration</h2><div className="modules">{MODS.map(([k,l])=><label key={k}><input type="checkbox" checked={mods[k]} onChange={e=>setMods({...mods,[k]:e.target.checked})}/>{l}</label>)}</div></section>}
 <footer><button disabled={step===1||saving} onClick={()=>setStep(s=>Math.max(1,s-1))}>Retour</button>{step<5?<button className="primary" onClick={()=>setStep(s=>Math.min(5,s+1))}>Continuer</button>:<button className="primary" disabled={saving} onClick={create}>{saving?"Création…":"Créer mon espace club"}</button>}</footer></div><style jsx>{`:global(body){background:#f6f2ee}.page{padding:28px 18px 60px}.shell{max-width:1050px;margin:auto}header{background:linear-gradient(135deg,#6b1a2c,#35101a);color:#fff;border-radius:23px;padding:23px}header p{color:#d4a24c;font-weight:1000;letter-spacing:.12em;margin:0}header h1{margin:5px 0}.progress{height:7px;background:#eadfd8;border-radius:99px;margin:12px 0;overflow:hidden}.progress i{display:block;height:100%;background:#d4a24c}.card{background:#fff;border:1px solid #eadfd8;border-radius:17px;padding:17px}.fields,.facility{display:grid;grid-template-columns:1fr 1fr;gap:8px}.facility{border-bottom:1px solid #eee4df;padding:10px 0}.card :global(label){display:grid;gap:4px}.card :global(label span){font-size:.66rem;font-weight:900;text-transform:uppercase;color:#7d6e66}.card :global(input),.card :global(select),.card :global(textarea){border:1px solid #ddd1ca;border-radius:8px;padding:8px}.chips{display:flex;gap:5px;flex-wrap:wrap}.chips button{border:1px solid #ddd1ca;background:#fff;border-radius:999px;padding:8px 11px}.chips .active{background:#6b1a2c;color:#fff}.teamrow{display:grid;grid-template-columns:95px repeat(4,1fr);gap:7px;align-items:end;border:1px solid #eee4df;border-radius:9px;padding:8px;margin:7px 0}.checks,.modules{display:flex;gap:10px;flex-wrap:wrap}.modules label{display:flex!important;align-items:center;gap:6px;border:1px solid #eee4df;border-radius:9px;padding:10px}footer{display:flex;justify-content:space-between;margin-top:11px}button{border:1px solid #ddd1ca;background:#fff;border-radius:9px;padding:9px 12px;font-weight:900}.primary{background:#6b1a2c;color:#fff;border-color:#6b1a2c}@media(max-width:750px){.fields,.facility,.teamrow{grid-template-columns:1fr}}`}</style></main>
}
function F({l,children}:{l:string;children:React.ReactNode}){return <label><span>{l}</span>{children}</label>}
