import {createHash,randomBytes} from "node:crypto";
import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin-server";
import {sendTransactionalEmail} from "@/lib/server-notifications";
const h=(x:string)=>createHash("sha256").update(x).digest("hex");
function esc(x:any){return String(x??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
async function context(structureId:string){const sb=await createClient();const{data:{user}}=await sb.auth.getUser();if(!user)return null;const db=createAdminClient()||sb;const [m,s]=await Promise.all([db.from("institutional_members").select("id").eq("structure_id",structureId).eq("user_id",user.id).eq("status","active").maybeSingle(),db.from("institutional_structures").select("id,name,structure_type").eq("id",structureId).maybeSingle()]);if(!m.data||!s.data||s.data.structure_type!=="league")return null;return{db,user,structure:s.data}}
export async function GET(req:Request){const u=new URL(req.url),structureId=u.searchParams.get("structureId")||"",playerId=u.searchParams.get("playerId")||"";const c=await context(structureId);if(!c)return NextResponse.json({error:"Accès refusé"},{status:403});const[t,a]=await Promise.all([c.db.from("institutional_pole_followup_templates").select("*").eq("structure_id",structureId).eq("active",true).order("created_at",{ascending:false}),c.db.from("institutional_pole_followup_assignments").select("*,institutional_pole_followup_templates(title,template_type,frequency)").eq("structure_id",structureId).order("created_at",{ascending:false})]);if(t.error||a.error)return NextResponse.json({error:t.error?.message||a.error?.message},{status:400});return NextResponse.json({templates:t.data||[],assignments:playerId?(a.data||[]).filter((x:any)=>String(x.institutional_player_id)===playerId):a.data||[]})}
export async function POST(req:Request){const b=await req.json().catch(()=>({})),structureId=String(b.structureId||"");const c=await context(structureId);if(!c)return NextResponse.json({error:"Accès refusé"},{status:403});try{
 if(b.action==="createTemplate"){const q=await c.db.from("institutional_pole_followup_templates").insert({structure_id:structureId,title:String(b.title||"").trim(),description:b.description||null,template_type:b.templateType||"form",recipient_type:b.recipientType||"partner_coach",frequency:b.frequency||"once",scope:b.scope||"player",instructions:b.instructions||null,document_text:b.documentText||null,fields:Array.isArray(b.fields)?b.fields:[],created_by:c.user.id}).select("*").single();if(q.error)throw q.error;return NextResponse.json({ok:true,template:q.data})}
 if(b.action==="deleteTemplate"){const q=await c.db.from("institutional_pole_followup_templates").update({active:false,updated_at:new Date().toISOString()}).eq("id",String(b.templateId||"")).eq("structure_id",structureId);if(q.error)throw q.error;return NextResponse.json({ok:true})}
 if(b.action==="createAssignment"||b.action==="remind"){let assignment:any=null,rawToken="";
   if(b.action==="remind"){const q=await c.db.from("institutional_pole_followup_assignments").select("*,institutional_pole_followup_templates(*)").eq("id",String(b.assignmentId||"")).eq("structure_id",structureId).single();if(q.error)throw q.error;assignment=q.data;rawToken=String(b.token||"");if(!rawToken)throw new Error("Pour des raisons de sécurité, régénère un nouveau lien plutôt que réutiliser un token masqué.")}
   else {const token=randomBytes(32).toString("hex");rawToken=token;const expiresAt=b.expiresAt||new Date(Date.now()+45*86400000).toISOString();const q=await c.db.from("institutional_pole_followup_assignments").insert({structure_id:structureId,template_id:String(b.templateId||""),institutional_player_id:b.institutionalPlayerId||null,pole_team_id:b.poleTeamId||null,partner_team_id:b.partnerTeamId||null,season_label:b.seasonLabel||null,recipient_type:b.recipientType||"custom",recipient_name:b.recipientName||null,recipient_email:b.recipientEmail||null,token_hash:h(token),status:"pending",due_at:b.dueAt||null,expires_at:expiresAt,created_by:c.user.id}).select("*,institutional_pole_followup_templates(*)").single();if(q.error)throw q.error;assignment=q.data}
   const url=`${(process.env.NEXT_PUBLIC_SITE_URL||process.env.NEXT_PUBLIC_APP_URL||new URL(req.url).origin).replace(/\/$/,"")}/suivi-pole/${rawToken}`;if(assignment.recipient_email){const tpl:any=assignment.institutional_pole_followup_templates||{};await sendTransactionalEmail({to:assignment.recipient_email,subject:`${c.structure.name} · ${tpl.title||"Suivi joueur"}`,html:`<div style="font-family:Arial;max-width:680px;margin:auto"><div style="background:#6B1A2C;color:white;padding:20px"><b>${esc(c.structure.name)}</b></div><div style="padding:22px"><h2>${esc(tpl.title||"Suivi joueur")}</h2><p>${esc(tpl.instructions||"Merci de compléter ce suivi.")}</p><p><a href="${url}" style="display:inline-block;background:#6B1A2C;color:white;padding:12px 18px;border-radius:9px;text-decoration:none;font-weight:bold">Ouvrir et remplir</a></p></div></div>`})}
   return NextResponse.json({ok:true,url,assignmentId:assignment.id})}
 throw new Error("Action inconnue");
 }catch(e:any){return NextResponse.json({error:e?.message||"Opération impossible"},{status:400})}}
