"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";

type ReporterRole="coach"|"manager"|"parent"|"other";
export default function ReferralPage(){
 const{token}=useParams<{token:string}>();
 const[s,setS]=useState<any>(null),[sent,setSent]=useState(false),[busy,setBusy]=useState(false);
 const[f,setF]=useState({reporter_role:"coach" as ReporterRole,reporter_name:"",reporter_email:"",reporter_phone:"",first_name:"",last_name:"",birthdate:"",club_name:"",category:"",venue:"",home_team:"",away_team:"",jersey_color:"",jersey_number:"",reason:""});
 useEffect(()=>{fetch(`/api/institutionnel/player-referrals/${token}`).then(r=>r.json()).then(j=>setS(j.structure||null))},[token]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);const r=await fetch(`/api/institutionnel/player-referrals/${token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return alert(j.error||"Envoi impossible");setSent(true)}
 if(!s)return <main className="wrap"><section className="card">Chargement…</section></main>;
 return <main className="wrap"><section className="card"><p className="eyebrow">{s.short_name||s.name}</p><h1>Signaler un joueur</h1><p>Vous pouvez signaler un joueur même si vous ne connaissez pas son identité. Les informations d’observation permettront à l’Institution de le retrouver.</p>{sent?<div className="success">Merci. Le signalement a bien été transmis.</div>:<form onSubmit={submit}>
 <h2>Vous êtes</h2><div className="roles">{[["coach","Entraîneur"],["manager","Dirigeant"],["parent","Parent"],["other","Autre"]].map(([v,l])=><label key={v} className={f.reporter_role===v?"role on":"role"}><input type="radio" name="role" value={v} checked={f.reporter_role===v} onChange={()=>setF({...f,reporter_role:v as ReporterRole})}/>{l}</label>)}</div>
 <div className="grid"><input required placeholder="Votre nom" value={f.reporter_name} onChange={e=>setF({...f,reporter_name:e.target.value})}/><input required type="email" placeholder="Votre email" value={f.reporter_email} onChange={e=>setF({...f,reporter_email:e.target.value})}/><input placeholder="Votre téléphone" value={f.reporter_phone} onChange={e=>setF({...f,reporter_phone:e.target.value})}/></div>
 <h2>Joueur, si vous le connaissez</h2><div className="grid"><input placeholder="Prénom du joueur (facultatif)" value={f.first_name} onChange={e=>setF({...f,first_name:e.target.value})}/><input placeholder="Nom du joueur (facultatif)" value={f.last_name} onChange={e=>setF({...f,last_name:e.target.value})}/><input type="date" value={f.birthdate} onChange={e=>setF({...f,birthdate:e.target.value})}/><input placeholder="Club actuel" value={f.club_name} onChange={e=>setF({...f,club_name:e.target.value})}/><input placeholder="Catégorie" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/></div>
 <h2>Pour pouvoir identifier le joueur</h2><div className="grid"><input required placeholder="Salle / gymnase où vous l’avez vu" value={f.venue} onChange={e=>setF({...f,venue:e.target.value})}/><input placeholder="Club / équipe 1" value={f.home_team} onChange={e=>setF({...f,home_team:e.target.value})}/><input placeholder="Club / équipe 2" value={f.away_team} onChange={e=>setF({...f,away_team:e.target.value})}/><input required placeholder="Couleur du maillot" value={f.jersey_color} onChange={e=>setF({...f,jersey_color:e.target.value})}/><input required placeholder="Numéro du joueur" value={f.jersey_number} onChange={e=>setF({...f,jersey_number:e.target.value})}/><textarea placeholder="Pourquoi ce joueur vous paraît intéressant ? Autres repères utiles…" value={f.reason} onChange={e=>setF({...f,reason:e.target.value})}/></div><button disabled={busy}>{busy?"Envoi…":"Envoyer le signalement"}</button></form>}</section><style jsx>{`.wrap{max-width:760px;margin:40px auto;padding:20px}.card{background:#fff;border:1px solid #eadfd8;border-radius:18px;padding:24px}.eyebrow{color:#d4a24c;font-weight:1000;letter-spacing:.12em;font-size:.7rem}h1{color:#6b1a2c}h2{font-size:1rem;color:#6b1a2c;margin:22px 0 8px}.roles{display:flex;gap:8px;flex-wrap:wrap}.role{border:1px solid #ddd1ca;border-radius:999px;padding:8px 12px;font-weight:800}.role.on{background:#6b1a2c;color:#fff;border-color:#6b1a2c}.role input{margin-right:6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:10px 0}.grid input,.grid textarea{border:1px solid #ddd1ca;border-radius:9px;padding:10px;font:inherit}.grid textarea{grid-column:1/-1;min-height:110px}button{border:0;border-radius:9px;padding:11px 15px;background:#6b1a2c;color:#fff;font-weight:900}.success{background:#f4fbf5;border:1px solid #b8dec0;padding:14px;border-radius:10px}@media(max-width:600px){.grid{grid-template-columns:1fr}.grid textarea{grid-column:auto}}`}</style></main>}
