"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { SESSION_QUESTIONS, buildSessionAnalysis, average } from "@/lib/development-profile";

type ExerciseReview={session_exercise_id:string;exercise_id:string|null;title:string;understanding_rating:number;mastery_rating:number;status:'not_mastered'|'in_progress'|'mastered';comment:string};

export default function SessionSelfEvaluation({sessionId}:{sessionId:string}) {
 const supabase=useMemo(()=>createClient(),[]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const [session,setSession]=useState<any>(null); const [calendarEventId,setCalendarEventId]=useState<string|null>(null);
 const [questions,setQuestions]=useState<Record<string,number>>({objectives_rating:3,clarity_rating:3,adaptation_rating:3,rhythm_rating:3,relevance_rating:3});
 const [takeaways,setTakeaways]=useState(''); const [nextChanges,setNextChanges]=useState(''); const [exercises,setExercises]=useState<ExerciseReview[]>([]); const [existingId,setExistingId]=useState<string|null>(null);
 useEffect(()=>{void load()},[sessionId]);
 async function load(){ setLoading(true); const {data:{user}}=await supabase.auth.getUser(); if(!user)return;
   const [{data:s},{data:ev},{data:rows},{data:review}] = await Promise.all([
    supabase.from('practice_sessions').select('id,title,theme,session_date,start_time,end_time,team_id,team_name').eq('id',sessionId).maybeSingle(),
    supabase.from('calendar_events').select('id').eq('session_id',sessionId).order('created_at',{ascending:true}).limit(1).maybeSingle(),
    supabase.from('practice_session_exercises').select('id,exercise_id,title,sort_order').eq('session_id',sessionId).order('sort_order'),
    supabase.from('practice_session_self_reviews').select('*').eq('session_id',sessionId).eq('user_id',user.id).maybeSingle(),
   ]); setSession(s); setCalendarEventId(ev?.id??null);
   if(review){setExistingId(review.id); setQuestions({objectives_rating:review.objectives_rating,clarity_rating:review.clarity_rating,adaptation_rating:review.adaptation_rating,rhythm_rating:review.rhythm_rating,relevance_rating:review.relevance_rating}); setTakeaways(review.takeaways??''); setNextChanges(review.next_time_changes??'');}
   const {data:er}=await supabase.from('practice_exercise_reviews').select('*').eq('session_id',sessionId).eq('user_id',user.id); const byId=new Map((er??[]).map((r:any)=>[String(r.session_exercise_id),r]));
   setExercises((rows??[]).map((r:any)=>{const old:any=byId.get(String(r.id));return {session_exercise_id:String(r.id),exercise_id:r.exercise_id??null,title:r.title,understanding_rating:old?.understanding_rating??3,mastery_rating:old?.mastery_rating??3,status:old?.status??'in_progress',comment:old?.comment??''}})); setLoading(false); }
 function patchExercise(i:number,p:Partial<ExerciseReview>){setExercises(v=>v.map((e,idx)=>idx===i?{...e,...p}:e));}
 async function save(){setSaving(true);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const analysis=buildSessionAnalysis({questions,exercises});
   const payload={user_id:user.id,session_id:sessionId,calendar_event_id:calendarEventId,team_id:session?.team_id??null,review_date:new Date().toISOString().slice(0,10),...questions,takeaways,next_time_changes:nextChanges,generated_summary:analysis.summary,generated_advice:analysis.advice,updated_at:new Date().toISOString()};
   const {error}=await supabase.from('practice_session_self_reviews').upsert(payload,{onConflict:'user_id,session_id'}); if(error){alert(error.message);setSaving(false);return;}
   for(const e of exercises){await supabase.from('practice_exercise_reviews').upsert({user_id:user.id,session_id:sessionId,session_exercise_id:e.session_exercise_id,exercise_id:e.exercise_id,exercise_title:e.title,understanding_rating:e.understanding_rating,mastery_rating:e.mastery_rating,status:e.status,comment:e.comment,updated_at:new Date().toISOString()},{onConflict:'user_id,session_id,session_exercise_id'});}
   setSaving(false);alert('Auto-évaluation enregistrée.');void load();}
 const generated=buildSessionAnalysis({questions,exercises}); const score=average(Object.values(questions)); if(loading)return <div className="ae-loading">Chargement…</div>;
 return <div className="ae"><header><div><span>AUTO-ÉVALUATION · {new Date().toLocaleDateString('fr-FR')}</span><h1>{session?.title||session?.theme||'Séance'}</h1><p>{session?.team_name||'Équipe'} · séance du {session?.session_date?new Date(session.session_date+'T12:00:00').toLocaleDateString('fr-FR'):'—'}</p></div><strong>{score.toFixed(1)}/5</strong></header>
 <section className="card"><h2>1. Mon auto-évaluation</h2>{SESSION_QUESTIONS.map(q=><Rating key={q.key} label={q.label} value={questions[q.key]??3} onChange={v=>setQuestions(x=>({...x,[q.key]:v}))}/>)}</section>
 <section className="card"><h2>2. Maîtrise des exercices</h2>{exercises.map((e,i)=><div className="exercise" key={e.session_exercise_id}><div className="exercise-head"><b>{e.title}</b><select value={e.status} onChange={x=>patchExercise(i,{status:x.target.value as any})}><option value="not_mastered">Non maîtrisé</option><option value="in_progress">En cours</option><option value="mastered">Maîtrisé</option></select></div><Rating label="Compréhension" value={e.understanding_rating} onChange={v=>patchExercise(i,{understanding_rating:v})}/><Rating label="Maîtrise" value={e.mastery_rating} onChange={v=>patchExercise(i,{mastery_rating:v})}/><textarea placeholder="Commentaire facultatif" value={e.comment} onChange={x=>patchExercise(i,{comment:x.target.value})}/></div>)}</section>
 <section className="two"><div className="card"><h2>3. Ce que je retiens</h2><textarea value={takeaways} onChange={e=>setTakeaways(e.target.value)} placeholder="Points importants de la séance…"/><h2>À modifier la prochaine fois</h2><textarea value={nextChanges} onChange={e=>setNextChanges(e.target.value)} placeholder="Ce que je souhaite faire évoluer…"/></div><div className="card analysis"><h2>4. Analyse MyBasket</h2><h3>Synthèse</h3><p>{generated.summary}</p><h3>Prochaine séance</h3><p>{generated.advice}</p></div></section>
 <div className="save"><button onClick={save} disabled={saving}>{saving?'Enregistrement…':existingId?'Mettre à jour l’auto-évaluation':'Enregistrer l’auto-évaluation'}</button></div>
 <style jsx>{`.ae{max-width:1180px;margin:auto;padding:26px;color:#24171b}.ae header{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.ae header span{color:#d4a24c;font-weight:950;font-size:12px}.ae h1{margin:4px 0;color:#6b1a2c}.ae header p{margin:0;color:#8c7e77}.ae header>strong{font-size:28px;color:#6b1a2c;background:#fff7eb;border:1px solid #eadccc;padding:12px 16px;border-radius:16px}.card{border:1px solid #eee2d6;border-radius:18px;background:#fff;padding:18px;margin-bottom:14px;box-shadow:0 10px 25px rgba(50,20,10,.05)}h2{color:#6b1a2c;margin:0 0 15px}h3{color:#d4a24c;margin:15px 0 6px}.exercise{border-top:1px solid #f0e6db;padding:15px 0}.exercise:first-of-type{border-top:0}.exercise-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.exercise-head select{border:1px solid #eadccc;border-radius:10px;padding:8px;background:#fff}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.analysis{background:#fff9ef}.analysis p{line-height:1.55}textarea{width:100%;min-height:90px;box-sizing:border-box;border:1px solid #e5ddd4;border-radius:12px;padding:11px;font:inherit;resize:vertical}.save{position:sticky;bottom:14px;display:flex;justify-content:center}.save button{border:0;background:#6b1a2c;color:#fff;border-radius:14px;padding:15px 26px;font-weight:950;cursor:pointer}@media(max-width:800px){.two{grid-template-columns:1fr}.ae{padding:16px}.ae header{align-items:flex-start}}`}</style></div>
}
function Rating({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <div className="rating"><span>{label}</span><div>{[1,2,3,4,5].map(n=><button type="button" key={n} className={n<=value?'on':''} onClick={()=>onChange(n)}>{n}</button>)}</div><b>{value}/5</b><style jsx>{`.rating{display:grid;grid-template-columns:minmax(240px,1fr) auto 42px;gap:10px;align-items:center;padding:8px 0}.rating>span{font-weight:800;color:#4c4040}.rating>div{display:flex;gap:5px}.rating button{width:34px;height:34px;border-radius:9px;border:1px solid #eadccc;background:#fff;color:#6b1a2c;font-weight:900}.rating button.on{background:#6b1a2c;color:#fff;border-color:#6b1a2c}.rating>b{text-align:right;color:#d4a24c}@media(max-width:650px){.rating{grid-template-columns:1fr 42px}.rating>div{grid-column:1/-1;grid-row:2}}`}</style></div>}
