"use client";
import {useEffect,useState} from "react";
import AttendanceSignaturePad from "./AttendanceSignaturePad";
export default function AttendanceSigningDialog({name,session,initialImage,onSave,onClose,onPhone,onRevoke,onCompleted}:{name:string;session:string;initialImage?:string;onSave:(image:string)=>Promise<void>;onClose:()=>void;onPhone:()=>Promise<{url:string;qr:string;expiresAt:string}>;onRevoke:()=>Promise<void>;onCompleted:()=>Promise<void>}){
 const [mode,setMode]=useState<"choice"|"local"|"phone">("choice"),[phone,setPhone]=useState<{url:string;qr:string;expiresAt:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!phone)return;let stopped=false,running=false;const tick=async()=>{if(running||stopped)return;running=true;try{const url=new URL(phone.url);const response=await fetch(`/api/public/training-signature/${url.pathname.split("/").pop()}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:url.hash.slice(1),action:"inspect"})});const data=await response.json();if(stopped)return;if(response.ok&&data.completed){stopped=true;await onCompleted();onClose();}else if(!response.ok){setError(data.error||"Lien indisponible");stopped=true;}}catch{if(!stopped)setError("Connexion interrompue. Vérifiez votre connexion.");}finally{running=false;}};const timer=setInterval(()=>void tick(),2500);return()=>{stopped=true;clearInterval(timer);};},[phone,onCompleted,onClose]);
 async function openPhone(){setBusy(true);setError("");try{setPhone(await onPhone());setMode("phone");}catch(e){setError(e instanceof Error?e.message:"Lien impossible");}finally{setBusy(false);}}
 async function close(){if(phone){setBusy(true);try{await onRevoke();}catch(e){setError(e instanceof Error?e.message:"Annulation impossible");setBusy(false);return;}}onClose();}
 if(mode==="local")return <AttendanceSignaturePad name={name} session={session} initialImage={initialImage} onSave={onSave} onClose={onClose}/>;
 return <div className="backdrop"><section role="dialog" aria-modal="true" aria-label="Choisir le mode de signature"><header><div><small>ÉMARGEMENT</small><h3>{name}</h3></div><button type="button" disabled={busy} aria-label="Fermer et annuler le lien téléphone" onClick={()=>void close()}>×</button></header><p>{session}</p>{mode==="choice"?<div className="choices"><button disabled={busy} onClick={()=>setMode("local")}><b>Sur cet appareil</b><span>Souris, écran tactile ou doigt</span></button><button disabled={busy} onClick={()=>void openPhone()}><b>Sur mon téléphone</b><span>Scanner un QR code pour signer au doigt</span></button></div>:phone&&<div className="phone"><img src={phone.qr} alt="QR code pour cette signature" width={220} height={220}/><b>Scannez avec l’appareil photo de votre téléphone</b><p>Ce lien concerne uniquement ce stagiaire et cette demi-journée.</p><small>Valable jusqu’à {new Date(phone.expiresAt).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})} · utilisable une fois</small><button onClick={()=>navigator.clipboard.writeText(phone.url).catch(()=>setError("Copie impossible"))}>Copier le lien</button><p>En attente de la signature…</p></div>}{error&&<p role="alert">{error}</p>}<style jsx>{`.backdrop{position:fixed;inset:0;background:#21161a99;z-index:1100;display:grid;place-items:center;padding:12px}section{background:white;border-radius:16px;padding:20px;width:min(560px,100%);box-sizing:border-box;max-height:95dvh;overflow:auto}header{display:flex;justify-content:space-between;gap:12px;align-items:center}h3{margin:4px 0;color:#6b1a2c}small,p{color:#75666b;font-size:12px}button{border:1px solid #dacbc5;border-radius:10px;background:white;color:#6b1a2c;padding:12px;cursor:pointer}header button{font-size:24px;padding:2px 10px}.choices{display:grid;gap:10px}.choices button{text-align:left;padding:18px}.choices b,.choices span{display:block}.choices span{font-size:12px;color:#75666b;margin-top:6px}.choices button:hover{background:#fff5f7}.phone{display:flex;align-items:center;flex-direction:column;text-align:center;gap:8px}.phone p{margin:4px 0}button:disabled{opacity:.5}`}</style></section></div>;
}
