"use client";
import {useEffect,useRef,useState} from "react";
export default function AttendanceSignaturePad({name,session,initialImage,onSave,onClose}:{name:string;session:string;initialImage?:string;onSave:(image:string)=>Promise<void>;onClose:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),hasInk=useRef(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!initialImage)return;const image=new Image();image.onload=()=>{canvas.current?.getContext("2d")?.drawImage(image,0,0,800,300);hasInk.current=true;};image.src=initialImage;return()=>{image.onload=null;};},[initialImage]);
 function point(event:React.PointerEvent<HTMLCanvasElement>){const rect=event.currentTarget.getBoundingClientRect();return {x:(event.clientX-rect.left)*800/rect.width,y:(event.clientY-rect.top)*300/rect.height};}
 function clear(){canvas.current?.getContext("2d")?.clearRect(0,0,800,300);hasInk.current=false;setError("");}
 async function save(){if(!hasInk.current||!canvas.current){setError("Veuillez signer avant d’enregistrer.");return;}setBusy(true);setError("");try{await onSave(canvas.current.toDataURL("image/png"));onClose();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible");}finally{setBusy(false);}}
 return <div className="backdrop"><section role="dialog" aria-modal="true" aria-label="Signature d’émargement"><h3>{name}</h3><p>{session}</p><p>Je confirme ma présence et signe ci-dessous.</p><canvas ref={canvas} width={800} height={300} onPointerDown={event=>{if(busy)return;const context=event.currentTarget.getContext("2d");if(!context)return;const p=point(event);context.strokeStyle="#262025";context.fillStyle="#262025";context.lineWidth=3;context.lineCap="round";context.lineJoin="round";context.beginPath();context.arc(p.x,p.y,1.5,0,Math.PI*2);context.fill();context.beginPath();context.moveTo(p.x,p.y);drawing.current=true;hasInk.current=true;event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(!drawing.current)return;const p=point(event),context=event.currentTarget.getContext("2d");context?.lineTo(p.x,p.y);context?.stroke();}} onPointerUp={()=>{drawing.current=false;}} onPointerCancel={()=>{drawing.current=false;}}/><small>Signature au doigt ou à la souris · conservée pour cette demi-journée.</small>{error&&<p role="alert">{error}</p>}<div className="actions"><button disabled={busy} onClick={clear}>Effacer</button><button disabled={busy} onClick={onClose}>Annuler</button><button disabled={busy} onClick={()=>void save()}>{busy?"Enregistrement…":"Enregistrer la signature"}</button></div><style jsx>{`.backdrop{position:fixed;inset:0;z-index:1100;background:#21161a99;display:grid;place-items:center;padding:12px}section{box-sizing:border-box;background:white;border-radius:16px;padding:18px;width:min(680px,100%);max-height:95dvh;overflow:auto}h3{margin:0;color:#6b1a2c}p{font-size:13px}canvas{display:block;width:100%;height:clamp(150px,35vh,250px);border:1px solid #dacbc5;border-radius:10px;background:white;touch-action:none}small{display:block;color:#75666b;margin-top:8px}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px;margin-top:16px}button{padding:10px;border:1px solid #dacbc5;border-radius:8px;background:white;color:#6b1a2c;cursor:pointer}button:last-child{background:#6b1a2c;color:white}button:disabled{opacity:.5}`}</style></section></div>;
}
