"use client";
import {createPortal} from "react-dom";
import styles from "./AttendanceSignature.module.css";
import {useEffect,useRef,useState} from "react";
export default function AttendanceSignaturePad({name,session,initialImage,onSave,onClose}:{name:string;session:string;initialImage?:string;onSave:(image:string)=>Promise<void>;onClose:()=>void}){
 const [mounted,setMounted]=useState(false);
 useEffect(()=>{setMounted(true);},[]);
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),hasInk=useRef(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!initialImage)return;const image=new Image();image.onload=()=>{canvas.current?.getContext("2d")?.drawImage(image,0,0,800,300);hasInk.current=true;};image.src=initialImage;return()=>{image.onload=null;};},[initialImage]);
 function point(event:React.PointerEvent<HTMLCanvasElement>){const rect=event.currentTarget.getBoundingClientRect();return {x:(event.clientX-rect.left)*800/rect.width,y:(event.clientY-rect.top)*300/rect.height};}
 function clear(){canvas.current?.getContext("2d")?.clearRect(0,0,800,300);hasInk.current=false;setError("");}
 async function save(){if(!hasInk.current||!canvas.current){setError("Veuillez signer avant d’enregistrer.");return;}setBusy(true);setError("");try{await onSave(canvas.current.toDataURL("image/png"));onClose();}catch(e){setError(e instanceof Error?e.message:"Enregistrement impossible");}finally{setBusy(false);}}
 if(!mounted)return null;
 return createPortal(<div className={styles.backdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-label="Signature d’émargement"><div className={styles.heading}><h3>{name}</h3><button type="button" className={styles.close} aria-label="Fermer sans enregistrer" disabled={busy} onClick={onClose}>×</button></div><p>{session}</p><p>Je confirme ma présence et signe ci-dessous.</p><canvas className={styles.canvas} ref={canvas} width={800} height={300} onPointerDown={event=>{if(busy)return;const context=event.currentTarget.getContext("2d");if(!context)return;const p=point(event);context.strokeStyle="#262025";context.fillStyle="#262025";context.lineWidth=3;context.lineCap="round";context.lineJoin="round";context.beginPath();context.arc(p.x,p.y,1.5,0,Math.PI*2);context.fill();context.beginPath();context.moveTo(p.x,p.y);drawing.current=true;hasInk.current=true;event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(!drawing.current)return;const p=point(event),context=event.currentTarget.getContext("2d");context?.lineTo(p.x,p.y);context?.stroke();}} onPointerUp={()=>{drawing.current=false;}} onPointerCancel={()=>{drawing.current=false;}}/><small className={styles.hint}>Signature au doigt ou à la souris · conservée pour cette demi-journée.</small>{error&&<p className={styles.error} role="alert">{error}</p>}<div className={styles.actions}><button type="button" disabled={busy} onClick={clear}>Effacer</button><button type="button" disabled={busy} onClick={onClose}>Annuler</button><button type="button" className={styles.primary} disabled={busy} onClick={()=>void save()}>{busy?"Enregistrement…":"Enregistrer la signature"}</button></div></section></div>,document.body);
}
