"use client";
import {createPortal} from "react-dom";
import styles from "./AttendanceSignature.module.css";
import {useEffect,useState} from "react";
import AttendanceSignaturePad from "./AttendanceSignaturePad";
export default function AttendanceSigningDialog({name,session,initialImage,onSave,onClose,onPhone,onRevoke,onCompleted}:{name:string;session:string;initialImage?:string;onSave:(image:string)=>Promise<void>;onClose:()=>void;onPhone:()=>Promise<{url:string;qr:string;expiresAt:string}>;onRevoke:()=>Promise<void>;onCompleted:()=>Promise<void>}){
 const [mounted,setMounted]=useState(false);
 useEffect(()=>{setMounted(true);},[]);
 const [mode,setMode]=useState<"choice"|"local"|"phone">("choice"),[phone,setPhone]=useState<{url:string;qr:string;expiresAt:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!phone)return;let stopped=false,running=false;const tick=async()=>{if(running||stopped)return;running=true;try{const url=new URL(phone.url);const response=await fetch(`/api/public/training-signature/${url.pathname.split("/").pop()}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:url.hash.slice(1),action:"inspect"})});const data=await response.json();if(stopped)return;if(response.ok&&data.completed){stopped=true;await onCompleted();onClose();}else if(!response.ok){setError(data.error||"Lien indisponible");stopped=true;}}catch{if(!stopped)setError("Connexion interrompue. Vérifiez votre connexion.");}finally{running=false;}};const timer=setInterval(()=>void tick(),2500);return()=>{stopped=true;clearInterval(timer);};},[phone,onCompleted,onClose]);
 async function openPhone(){setBusy(true);setError("");try{setPhone(await onPhone());setMode("phone");}catch(e){setError(e instanceof Error?e.message:"Lien impossible");}finally{setBusy(false);}}
 async function close(){if(phone){setBusy(true);try{await onRevoke();}catch(e){setError(e instanceof Error?e.message:"Annulation impossible");setBusy(false);return;}}onClose();}
 if(mode==="local")return <AttendanceSignaturePad name={name} session={session} initialImage={initialImage} onSave={onSave} onClose={onClose}/>;
 if(!mounted)return null;
 return createPortal(<div className={styles.backdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-label="Choisir le mode de signature"><header className={styles.heading}><div><small>ÉMARGEMENT</small><h3>{name}</h3></div><button type="button" className={styles.close} disabled={busy} aria-label="Fermer et annuler le lien téléphone" onClick={()=>void close()}>×</button></header><p>{session}</p>{mode==="choice"?<div className={styles.choices}><button type="button" disabled={busy} onClick={()=>setMode("local")}><b>Sur cet appareil</b><span>Souris, écran tactile ou doigt</span></button><button type="button" disabled={busy} onClick={()=>void openPhone()}><b>Sur mon téléphone</b><span>Scanner un QR code pour signer au doigt</span></button></div>:phone&&<div className={styles.phone}><img src={phone.qr} alt="QR code pour cette signature" width={220} height={220}/><b>Scannez avec l’appareil photo de votre téléphone</b><p>Ce lien concerne uniquement ce stagiaire et cette demi-journée.</p><small>Valable jusqu’à {new Date(phone.expiresAt).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})} · utilisable une fois</small><button type="button" onClick={()=>navigator.clipboard.writeText(phone.url).catch(()=>setError("Copie impossible"))}>Copier le lien</button><p>En attente de la signature…</p></div>}{error&&<p className={styles.error} role="alert">{error}</p>}</section></div>,document.body);
}
