"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type P={id:string;name:string;code:string|null};type C={id:string;program_id:string;name:string;capacity:number|null};type Cand={id:string;user_id:string;status:string;progression:number};type Req={id:string;title:string;instructions:string|null;due_at:string|null};type Sub={id:string;status:string;current_version:number;reviewer_comment:string|null};
export default function TrainingManager({institutionId}:{institutionId?:string}){const s=useMemo(()=>createClient(),[]),[ps,setPs]=useState<P[]>([]),[cs,setCs]=useState<C[]>([]),[cid,setCid]=useState(""),[cands,setCands]=useState<Cand[]>([]),[reqs,setReqs]=useState<Req[]>([]),[subs,setSubs]=useState<Sub[]>([]),[pn,setPn]=useState("DETB"),[cn,setCn]=useState("Promotion 2026/2027"),[email,setEmail]=useState(""),[rt,setRt]=useState(""),[ri,setRi]=useState(""),[rd,setRd]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[type,setType]=useState("message");
async function loadC(id:string){const[a,b,c]=await Promise.all([s.from("training_candidates").select("*").eq("cohort_id",id),s.from("training_document_requests").select("*").eq("cohort_id",id),s.from("training_document_submissions").select("*,training_document_requests!inner(cohort_id)").eq("training_document_requests.cohort_id",id)]);setCands((a.data||[]) as Cand[]);setReqs((b.data||[]) as Req[]);setSubs((c.data||[]) as unknown as Sub[])}
async function reload(){let pq=s.from("training_programs").select("*").order("created_at",{ascending:false});let cq=s.from("training_cohorts").select("*").order("created_at",{ascending:false});if(institutionId){pq=pq.eq("institution_id",institutionId);cq=cq.eq("institution_id",institutionId)}const[a,b]=await Promise.all([pq,cq]);setPs((a.data||[]) as P[]);setCs((b.data||[]) as C[]);const n=cid||b.data?.[0]?.id||"";setCid(n);if(n)await loadC(n)}useEffect(()=>{void reload()},[institutionId]);// eslint-disable-line
async function createP(){const{data:{user}}=await s.auth.getUser();if(!user)return;const q=await s.from("training_programs").insert({name:pn,code:pn,created_by:user.id,institution_id:institutionId||null}).select("*").single();if(q.error)return alert(q.error.message);setPs(a=>[q.data as P,...a])}
async function createC(){if(!ps[0])return alert("Crée un programme");const q=await s.from("training_cohorts").insert({program_id:ps[0].id,name:cn,status:"active",institution_id:institutionId||null}).select("*").single();if(q.error)return alert(q.error.message);setCid(q.data.id);await reload()}
async function addCandidate(){const r=await fetch("/api/training/candidates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cohortId:cid,email})});const j=await r.json();if(!r.ok)return alert(j.error);setEmail("");await loadC(cid)}
async function addReq(){const{data:{user}}=await s.auth.getUser();if(!user)return;const q=await s.from("training_document_requests").insert({cohort_id:cid,title:rt,instructions:ri||null,due_at:rd?new Date(`${rd}T23:59:59`).toISOString():null,is_required:true,created_by:user.id});if(q.error)return alert(q.error.message);setRt("");setRi("");setRd("");await loadC(cid)}
async function review(id:string,status:string){const comment=prompt("Commentaire examinateur")||null;const{data:{user}}=await s.auth.getUser();const q=await s.from("training_document_submissions").update({status,reviewer_id:user?.id,reviewer_comment:comment,reviewed_at:new Date().toISOString()}).eq("id",id);if(q.error)return alert(q.error.message);await loadC(cid)}
async function send(){const r=await fetch("/api/training/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"cohort",cohortId:cid,messageType:type,subject,body})});const j=await r.json();if(!r.ok)return alert(j.error);setSubject("");setBody("")}
return <main className="m"><header><p>FORMATION DES CADRES</p><h1>Gestion formation</h1></header><div className="grid"><section><h2>Programme</h2><input value={pn} onChange={e=>setPn(e.target.value)}/><button onClick={createP}>Créer programme</button></section><section><h2>Promotion</h2><input value={cn} onChange={e=>setCn(e.target.value)}/><button onClick={createC}>Créer promotion</button></section></div><section><select value={cid} onChange={async e=>{setCid(e.target.value);await loadC(e.target.value)}}><option value="">Promotion</option>{cs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></section>{cid&&<div className="grid"><section><h2>Candidats</h2><div className="row"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email candidat"/><button onClick={addCandidate}>Ajouter</button></div>{cands.map(c=><p key={c.id}>{c.user_id} · {c.status} · {c.progression}%</p>)}</section><section><h2>Commander un document</h2><input value={rt} onChange={e=>setRt(e.target.value)} placeholder="Titre"/><textarea value={ri} onChange={e=>setRi(e.target.value)} placeholder="Consignes"/><input type="date" value={rd} onChange={e=>setRd(e.target.value)}/><button onClick={addReq}>Créer la commande</button>{reqs.map(r=><p key={r.id}><b>{r.title}</b></p>)}</section><section className="full"><h2>Documents remis</h2>{subs.map(x=><div className="submission" key={x.id}><span>{x.status} · v{x.current_version}</span><div><button onClick={()=>review(x.id,"validated")}>Valider</button><button onClick={()=>review(x.id,"changes_requested")}>À corriger</button><button onClick={()=>review(x.id,"rejected")}>Refuser</button></div></div>)}</section><section className="full"><h2>Communication / convocations</h2><select value={type} onChange={e=>setType(e.target.value)}><option value="message">Message</option><option value="announcement">Annonce</option><option value="convocation">Convocation</option></select><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Objet"/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Message"/><button onClick={send}>Envoyer</button></section></div>}<style jsx>{`:global(body){background:#f6f2ee}.m{max-width:1100px;margin:auto;padding:28px 18px}header{background:#6b1a2c;color:white;border-radius:20px;padding:20px}header p{color:#d4a24c;font-weight:1000}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}section{background:white;border:1px solid #eadfd8;border-radius:14px;padding:13px;display:grid;gap:7px}.full{grid-column:1/-1}input,textarea,select{border:1px solid #ddd1ca;border-radius:8px;padding:8px}button{background:#6b1a2c;color:white;border:0;border-radius:8px;padding:8px;font-weight:900}.row,.submission{display:flex;gap:6px;justify-content:space-between}.submission{border-bottom:1px solid #eee4df;padding:7px 0}@media(max-width:800px){.grid{grid-template-columns:1fr}.full{grid-column:auto}}`}</style></main>}
