'use client';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
type R=Record<string,any>;
const points=(a:R)=>a.action_type==='shot'&&a.shot_result==='made'?(String(a.shot_type).includes('3')?3:2):Number(a.ft_made||0);
const pct=(m:number,a:number)=>a?`${Math.round(m/a*100)}%`:'—';
export default function LiveMutualizedDashboard(){
 const [s,setS]=useState<R|null>(null),[actions,setA]=useState<R[]>([]),[picks,setP]=useState<R[]>([]),[poss,setPo]=useState<R[]>([]),[groups,setG]=useState<R[]>([]),[tab,setTab]=useState('live'),[scope,setScope]=useState<'match'|'q'|'lineup'>('match'),[selected,setSelected]=useState<R|null>(null);
 const params=typeof window==='undefined'?null:new URLSearchParams(window.location.search),sid=params?.get('session'),code=params?.get('code');
 useEffect(()=>{const sb=createClient();let ch:any;const boot=async()=>{let q=sb.from('live_sessions').select('*');q=sid?q.eq('id',sid):q.eq('join_code',(code||'').toUpperCase());const {data:ss}=await q.maybeSingle();if(!ss)return;setS(ss);await load(sb,ss.id,ss.match_id,setA,setP,setPo,setG);ch=sb.channel(`coach-v3:${ss.id}`).on('postgres_changes',{event:'*',schema:'public',table:'live_sessions',filter:`id=eq.${ss.id}`},(x:any)=>setS(x.new)).on('postgres_changes',{event:'*',schema:'public',table:'match_actions',filter:`live_session_id=eq.${ss.id}`},()=>load(sb,ss.id,ss.match_id,setA,setP,setPo,setG)).on('postgres_changes',{event:'*',schema:'public',table:'live_pick_events',filter:`session_id=eq.${ss.id}`},()=>load(sb,ss.id,ss.match_id,setA,setP,setPo,setG)).on('postgres_changes',{event:'*',schema:'public',table:'live_action_groups',filter:`session_id=eq.${ss.id}`},()=>load(sb,ss.id,ss.match_id,setA,setP,setPo,setG)).on('postgres_changes',{event:'*',schema:'public',table:'live_possessions',filter:`session_id=eq.${ss.id}`},()=>load(sb,ss.id,ss.match_id,setA,setP,setPo,setG)).subscribe()};boot();return()=>{if(ch)void sb.removeChannel(ch)}},[sid,code]);
 const shown=useMemo(()=>actions.filter(a=>scope==='match'||(scope==='q'&&Number(a.q)===Number(s?.current_period))||(scope==='lineup'&&sameLineup(a.lineup,s?.current_lineup))),[actions,scope,s]);
 const possIds=useMemo(()=>new Set(shown.map(a=>a.possession_id).filter(Boolean)),[shown]);
 const filteredPicks=useMemo(()=>picks.filter(p=>scope==='match'||possIds.has(p.possession_id)),[picks,scope,possIds]);
 const players=useMemo(()=>{const m=new Map<string,R>();for(const a of shown){for(const id of [a.player_id,a.assist_player_id,a.rebound_player_id].filter(Boolean))if(!m.has(id))m.set(id,{id,pts:0,fga:0,fgm:0,ast:0,reb:0,to:0,stl:0,pf:0});const r=m.get(a.player_id);if(r){r.pts+=points(a);if(a.action_type==='shot'){r.fga++;if(a.shot_result==='made')r.fgm++}if(a.action_type==='turnover')r.to++;if(a.action_type==='steal')r.stl++;if(a.action_type==='foul')r.pf++}if(a.assist_player_id){const assist=m.get(a.assist_player_id);if(assist)assist.ast++}if(a.rebound_player_id){const rebound=m.get(a.rebound_player_id);if(rebound)rebound.reb++}}return[...m.values()].sort((a,b)=>b.pts-a.pts)},[shown]);
 const pairs=useMemo(()=>{const m=new Map<string,R>();for(const p of filteredPicks){const k=`${p.handler_player_id}|${p.screener_player_id}`,x=m.get(k)||{k,h:p.handler_player_id,s:p.screener_player_id,n:0,pts:0,linked:0,rows:[]};x.n++;x.rows.push(p);if(p.is_decisive)x.linked++;const aa=shown.filter(a=>a.action_group_id&&a.action_group_id===p.action_group_id);x.pts+=aa.reduce((z,a)=>z+points(a),0);m.set(k,x)}return[...m.values()].sort((a,b)=>b.n-a.n)},[filteredPicks,shown]);
 const lineups=useMemo(()=>{
  const groups=new Map<string,{k:string;n:number;players:string[];pts:number}>();
  for(const a of shown){
    const players=Array.isArray(a.lineup)?a.lineup.map((v:any)=>String(v)).filter(Boolean):[];
    const k=players.slice().sort().join("|")||"sans-lineup";
    const current=groups.get(k);
    const actionPoints=points(a);
    if(current){
      current.n++;
      current.pts+=actionPoints;
    }else{
      groups.set(k,{k,n:1,players,pts:actionPoints});
    }
  }
  return Array.from(groups.values()).sort((a,b)=>b.n-a.n);
},[shown]);
 const quality=useMemo(()=>({complete:groups.filter(g=>g.status==='linked').length,review:groups.filter(g=>g.status==='review').length,pending:groups.filter(g=>g.status==='open').length,total:groups.length}),[groups]);
 if(!s)return <main style={S.main}><h2>Live mutualisé</h2><p>Chargement de la session…</p></main>;
 const tabs=[['live','LIVE'],['box','BOX SCORE'],['lineups','LINEUPS'],['picks','PICKS'],['timeline','TIMELINE']];
 return <main style={S.main}><header style={S.header}><div><b style={{fontSize:22}}>MYBASKET · STATS MUTUALISÉES</b><div style={S.muted}>🟢 {s.join_code} · lecture coach temps réel</div></div><div style={S.score}>{s.score_us}<span style={S.muted}>Q{s.current_period} · {s.current_clock}</span>{s.score_them}</div><button style={S.btn} onClick={()=>window.close()}>Fermer</button></header>
 <div style={S.toolbar}>{tabs.map(([k,l])=><button key={k} style={{...S.btn,...(tab===k?S.active:{})}} onClick={()=>setTab(k)}>{l}</button>)}<span style={{flex:1}}/>{[['match','MATCH'],['q',`Q${s.current_period}`],['lineup','LINEUP ACTUEL']].map(([k,l])=><button key={k} style={{...S.btn,...(scope===k?S.active:{})}} onClick={()=>setScope(k as any)}>{l}</button>)}</div>
 <section style={S.card}><div style={S.lineup}><b>LINEUP ACTUEL</b>{(s.current_lineup||[]).map((x:string)=><button key={x} style={S.pill} onClick={()=>setSelected({kind:'player',id:x})}>{x}</button>)}<span style={{flex:1}}/><button style={S.quality} onClick={()=>setSelected({kind:'quality'})}>✓ {quality.complete} mutualisées · ⚠ {quality.review} à confirmer · ○ {quality.pending} en attente</button></div></section>
 {tab==='live'&&<><section style={S.grid}>{stat('POSSESSIONS',new Set(shown.map(a=>a.possession_id).filter(Boolean)).size)}{stat('POINTS',shown.reduce((z,a)=>z+points(a),0))}{stat('PICKS',filteredPicks.length)}{stat('ACTIONS LIÉES',quality.complete)}</section><section style={S.card}><h2>À voir tout de suite</h2>{pairs.slice(0,5).map(x=><button key={x.k} style={S.row} onClick={()=>setSelected({kind:'pair',...x})}><b>Pick {x.h} + {x.s}</b><span>{x.n} poss.</span><span>{x.pts} pts</span><span>{x.n?(x.pts/x.n).toFixed(2):'—'} PPP</span></button>)}</section><section style={S.card}><h2>Lineups les plus utilisés</h2>{lineups.slice(0,4).map(x=><button key={x.k} style={S.row} onClick={()=>setSelected({kind:'lineup',...x})}><b>{x.players.join(' · ')}</b><span>{x.n} poss.</span><span>{x.pts} pts</span></button>)}</section></>}
 {tab==='box'&&<section style={S.card}><h2>Box score live</h2><table style={S.table}><thead><tr><th>Joueur</th><th>PTS</th><th>FG</th><th>REB</th><th>PD</th><th>BP</th><th>INT</th><th>FP</th></tr></thead><tbody>{players.map(r=><tr key={r.id} style={S.click} onClick={()=>setSelected({kind:'player',...r})}><td><b>{r.id}</b></td><td>{r.pts}</td><td>{r.fgm}/{r.fga} · {pct(r.fgm,r.fga)}</td><td>{r.reb}</td><td>{r.ast}</td><td>{r.to}</td><td>{r.stl}</td><td>{r.pf}</td></tr>)}</tbody></table></section>}
 {tab==='lineups'&&<section style={S.card}><h2>Lineups</h2>{lineups.map(x=><button key={x.k} style={S.row} onClick={()=>setSelected({kind:'lineup',...x})}><b>{x.players.join(' · ')}</b><span>{x.n} poss.</span><span>{x.pts} pts</span></button>)}</section>}
 {tab==='picks'&&<section style={S.card}><h2>Pick & Roll · données mutualisées</h2>{pairs.map(x=><button key={x.k} style={S.row} onClick={()=>setSelected({kind:'pair',...x})}><b>Handler {x.h} · Screener {x.s}</b><span>{x.n} picks</span><span>{x.pts} pts</span><span>{x.n?(x.pts/x.n).toFixed(2):'—'} PPP</span></button>)}</section>}
 {tab==='timeline'&&<section style={S.card}><h2>Timeline</h2>{poss.slice().reverse().map(p=>{const pp=picks.filter(x=>x.possession_id===p.id),aa=shown.filter(a=>a.possession_id===p.id);return <button key={p.id} style={S.row} onClick={()=>setSelected({kind:'possession',...p})}><b>#{p.number} · Q{p.period} · {p.start_clock}</b><span>{pp.map(x=>`Pick ${x.handler_player_id}/${x.screener_player_id}`).join(' · ')||'—'}</span><span>{aa.reduce((z,a)=>z+points(a),0)} pts</span></button>})}</section>}
 {selected&&<Drawer item={selected} picks={picks} actions={shown} groups={groups} close={()=>setSelected(null)}/>}</main>
}
function Drawer({item,picks,actions,groups,close}:{item:R;picks:R[];actions:R[];groups:R[];close:()=>void}){let body:any=null;if(item.kind==='pair'){const rows=picks.filter(p=>p.handler_player_id===item.h&&p.screener_player_id===item.s);const by=(key:string)=>Object.entries(rows.reduce((m:R,p:R)=>{const k=p[key]||'—';m[k]=(m[k]||0)+1;return m},{}));body=<><h2>Handler {item.h} + Screener {item.s}</h2><p>{item.n} picks · {item.pts} pts · {item.n?(item.pts/item.n).toFixed(2):'—'} PPP</p><h3>Sorties</h3>{by('screener_outcome').map(([k,v])=><p key={k}>{k}: <b>{String(v)}</b></p>)}<h3>Couvertures</h3>{by('defense_coverage').map(([k,v])=><p key={k}>{k}: <b>{String(v)}</b></p>)}</>}else if(item.kind==='quality'){body=<><h2>Qualité de mutualisation</h2>{groups.filter(g=>g.status!=='linked').map(g=><p key={g.id}>Q{g.period} {g.clock||''} · {g.status==='review'?'⚠ à confirmer':'○ en attente'} · {g.handler_player_id||'—'} / {g.screener_player_id||'—'}</p>)}</>}else body=<><h2>Détail</h2><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(item,null,2)}</pre></>;return <aside style={S.drawer}><button style={S.btn} onClick={close}>✕</button>{body}</aside>}
async function load(sb:any,sid:string,mid:string,setA:any,setP:any,setPo:any,setG:any){const[a,p,po,g]=await Promise.all([sb.from('match_actions').select('*').eq('match_id',mid).order('created_at',{ascending:true}),sb.from('live_pick_events').select('*').eq('session_id',sid).order('created_at',{ascending:true}),sb.from('live_possessions').select('*').eq('session_id',sid).order('number',{ascending:true}),sb.from('live_action_groups').select('*').eq('session_id',sid).order('created_at',{ascending:true})]);setA(a.data||[]);setP(p.data||[]);setPo(po.data||[]);setG(g.data||[])}
const sameLineup=(a:any,b:any)=>Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&[...a].sort().join('|')===[...b].sort().join('|');
const stat=(label:string,value:any)=><div style={S.stat}><small>{label}</small><b>{value}</b></div>;
const S:any={main:{minHeight:'100vh',background:'#090d14',color:'#f5f7fb',padding:20,fontFamily:'Arial,sans-serif'},header:{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,position:'sticky',top:0,background:'#090d14',padding:'10px 0',zIndex:5},score:{fontSize:34,fontWeight:900,display:'flex',gap:18,alignItems:'center'},muted:{color:'#9aa5b5',fontSize:13},toolbar:{display:'flex',gap:8,flexWrap:'wrap',margin:'12px 0'},btn:{background:'#151c28',color:'white',border:'1px solid #2a3547',borderRadius:10,padding:'9px 12px',fontWeight:800,cursor:'pointer'},active:{background:'#f5f7fb',color:'#090d14'},card:{background:'#101722',border:'1px solid #202b3b',borderRadius:16,padding:16,marginBottom:14,overflowX:'auto'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:10,marginBottom:14},stat:{background:'#101722',border:'1px solid #202b3b',borderRadius:16,padding:16,display:'grid',gap:8},lineup:{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap'},pill:{border:0,borderRadius:999,padding:'8px 12px',fontWeight:900,cursor:'pointer'},quality:{background:'transparent',color:'#c9d4e4',border:0,cursor:'pointer'},table:{width:'100%',borderCollapse:'collapse',textAlign:'center'},click:{cursor:'pointer',borderTop:'1px solid #202b3b',height:44},row:{width:'100%',display:'grid',gridTemplateColumns:'2fr repeat(3,1fr)',gap:10,alignItems:'center',background:'transparent',color:'white',border:0,borderTop:'1px solid #202b3b',padding:'14px 8px',textAlign:'left',cursor:'pointer'},drawer:{position:'fixed',right:20,top:90,width:'min(440px,calc(100vw - 40px))',maxHeight:'80vh',overflow:'auto',background:'#151c28',border:'1px solid #35445a',borderRadius:16,padding:18,boxShadow:'0 20px 80px #000',zIndex:20}};
