import React from "react";
import { NextResponse } from "next/server";
import { renderToBuffer } from "@react-pdf/renderer";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin-server";
import { InstitutionPlanningPdf } from "@/lib/institutionnel/institution-planning-pdf";

function clean(value:string){return value.replace(/[\\/:*?"<>|]+/g,"-").replace(/\s+/g," ").trim().slice(0,100)||"Institution"}
export async function POST(req:Request){const sb=await createClient();const{data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:"Non connecté"},{status:401});const admin=createAdminClient();if(!admin)return NextResponse.json({error:"Service admin indisponible"},{status:503});const b=await req.json().catch(()=>({})),structureId=String(b.structureId||""),title=clean(String(b.title||"Institution"));if(!structureId)return NextResponse.json({error:"Institution manquante"},{status:400});const[{data:m},{data:st}]=await Promise.all([admin.from("institutional_members").select("id").eq("structure_id",structureId).eq("user_id",user.id).eq("status","active").maybeSingle(),admin.from("institutional_structures").select("id,name,short_name,logo_url,email,city,document_primary_color,document_secondary_color").eq("id",structureId).maybeSingle()]);if(!m||!st)return NextResponse.json({error:"Accès refusé"},{status:403});const{data:events,error}=await admin.from("institutional_events").select("id,event_date,start_time,end_time,title,event_type,location,intervenant").eq("structure_id",structureId).eq("archived",false).order("event_date").order("start_time");if(error)return NextResponse.json({error:error.message},{status:400});const buffer=await renderToBuffer(React.createElement(InstitutionPlanningPdf,{structure:st,title,events:events||[]}) as React.ReactElement<any>),filename=`Planning - ${title}.pdf`,path=`${structureId}/planning/${Date.now()}-${filename.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await admin.storage.from("institutional-documents").upload(path,buffer,{contentType:"application/pdf"});if(up.error)return NextResponse.json({error:up.error.message},{status:400});const url=admin.storage.from("institutional-documents").getPublicUrl(path).data.publicUrl;await admin.from("institutional_documents").insert({structure_id:structureId,title:filename,document_type:"planning_pdf",storage_path:path,file_url:url,content:{planning_title:title,generated_at:new Date().toISOString()},created_by:user.id});return new Response(new Uint8Array(buffer),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${filename.replaceAll('"','')}"`,"Cache-Control":"no-store"}})}
